fbref.com Tables

Total 5 tables:
1. Player Standard Stats 
   Link - https://fbref.com/en/comps/9/stats/Premier-League-Stats
   html Id - "div_stats_standard"
2. Player Goalkeeping - https://fbref.com/en/comps/9/keepers/Premier-League-Stats
3. Player Shooting - https://fbref.com/en/comps/9/shooting/Premier-League-Stats
4. Player Playing Time - https://fbref.com/en/comps/9/playingtime/Premier-League-Stats
5. Player Miscellaneous Stats - https://fbref.com/en/comps/9/misc/Premier-League-Stats

On Not Getting Blocked
There are four techniques that matter here, in order of importance:
1. Respect rate limiting — add delays between requests
The single most important thing. Between every request, sleep for a random interval rather than a fixed one. Fixed delays are easier for servers to detect as bots. Random delays mimic human behaviour.
The concept is: time.sleep(random.uniform(3, 7)) between each page request. For 5 pages this adds maybe 25 seconds total — completely acceptable.
2. Set a proper User-Agent header
By default, requests identifies itself as a Python script. That's an immediate bot signal. Set your request headers to identify as a normal browser. Look up what a standard Chrome User-Agent string looks like and pass it in your request headers.
3. Use a session object
Rather than making independent requests, use requests.Session(). This maintains cookies and connection state across requests, which looks significantly more like a real browser session than repeated cold requests.
4. Check robots.txt first
Visit fbref.com/robots.txt manually before writing any code. This tells you which paths Sports Reference explicitly disallows. If your target URLs are disallowed, you have a decision to make about approach — either use their official data export options or reach out for permission. This is both ethical practice and protects your portfolio from scrutiny.

In [1]:
from pathlib import Path

ROOT = Path().resolve().parent
FBREF_WEBPAGES_PATH = ROOT / "data" / "fbref_webpages"

In [2]:
from io import StringIO
import pandas as pd
from bs4 import BeautifulSoup, Comment

Trying to scrape the page and was getting 403 Forbidden error because Cloudflare was  actively intercepting the request before it reaches FBref's server

Will be using `playwright` and `playwright-stealth` to overcome this.

In [3]:
goalkeeping_path = FBREF_WEBPAGES_PATH / "goalkeeping.html"
standard_stats_path = FBREF_WEBPAGES_PATH / "standard_stats.html"
shooting_path = FBREF_WEBPAGES_PATH / "shooting.html"
playingtime_path = FBREF_WEBPAGES_PATH / "playingtime.html"
misc_stats_path = FBREF_WEBPAGES_PATH / "misc_stats.html"

In [4]:
def extract_data_from_table(path):
    with open(path, encoding="utf-8") as f:
        soup = BeautifulSoup(f, "html.parser")
    
    comments = soup.find_all(string=lambda text: isinstance(text, Comment))
    
    table = [comment.strip() for comment in comments if "<table" in comment][0]
    soup_table = BeautifulSoup(table)
    html = str(soup_table.table)

    df = pd.read_html(StringIO(html))[0]

    return df

In [5]:
goalkeeping_df = extract_data_from_table(goalkeeping_path)
standard_stats_df = extract_data_from_table(standard_stats_path)
shooting_df = extract_data_from_table(shooting_path)
playingtime_df = extract_data_from_table(playingtime_path)
misc_stats_df = extract_data_from_table(misc_stats_path)

In [6]:
goalkeeping_df

   Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Rk                Player             Nation
0                   1               Alisson             br BRA
1                   2       Alphonse Areola             fr FRA
2                   3     Kepa Arrizabalaga             es ESP
3                   4        Altay Bayındır             tr TUR
4                   5        Walter Benítez             ar ARG
5                   6        Daniel Bentley            eng ENG
6                   7           Marco Bizot             nl NED
7                   8           Karl Darlow            wls WAL
8                   9  Gianluigi Donnarumma             it ITA
9                  10       Martin Dúbravka             sk SVK
10                 11        Melker Ellborg             se SWE
11                 12            Angus Gunn            sct SCO
12                 13        Dean Henderson            eng ENG
13                 14        Mads Hermansen             dk DEN
14                 15                  John             br BRA
15                 16         Sam Johnstone            eng ENG
16                 17       Filip Jørgensen             dk DEN
17                 18     Caoimhín Kelleher             ie IRL
18                 19        Antonín Kinský             cz CZE
19                 20         Senne Lammens             be BEL
20                 21            Bernd Leno             de GER
21                 22  Giorgi Mamardashvili             ge GEO
22                 23     Emiliano Martínez             ar ARG
23                 24         Stefan Ortega             de GER
24                 25           Lucas Perri             br BRA
25                 Rk                Player             Nation
26                 26        Đorđe Petrović             rs SRB
27                 27       Jordan Pickford            eng ENG
28                 28             Nick Pope            eng ENG
29                 29        Aaron Ramsdale            eng ENG
30                 30            David Raya             es ESP
31                 31           Robin Roefs             nl NED
32                 32               José Sá             pt POR
33                 33        Robert Sánchez             es ESP
34                 34             Matz Sels             be BEL
35                 35        James Trafford            eng ENG
36                 36    Hákon Valdimarsson             is ISL
37                 37       Bart Verbruggen             nl NED
38                 38     Guglielmo Vicario             it ITA
39                 39              Max Weiß             de GER
40                 40       Freddie Woodman            eng ENG

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                  Pos              Squad                Age
0                  GK          Liverpool                 32
1                  GK           West Ham                 32
2                  GK            Arsenal                 30
3                  GK     Manchester Utd                 27
4                  GK     Crystal Palace                 32
5                  GK             Wolves                 32
6                  GK        Aston Villa                 34
7                  GK       Leeds United                 34
8                  GK    Manchester City                 26
9                  GK            Burnley                 36
10                 GK         Sunderland                 22
11                 GK         Nottingham                 29
12                 GK     Crystal Palace                 28
13                 GK           West Ham                 25
14                 GK         Nottingham                 29
15                 GK             Wolves                 32
16                 GK            Chelsea                 23
17                 GK          Brentford                 26
18                 GK          Tottenham                 22
19                 GK     Manchester Utd                 23
20                 GK             Fulham                 33
21                 GK          Liverpool                 24
22                 GK        Aston Villa                 32
23                 GK         Nottingham                 32
24                 GK       Leeds United                 27
25                Pos              Squad                Age
26                 GK        Bournemouth                 25
27                 GK            Everton                 31
28                 GK          Newcastle                 33
29                 GK          Newcastle                 27
30                 GK            Arsenal                 29
31                 GK         Sunderland                 22
32                 GK             Wolves                 32
33                 GK            Chelsea                 27
34                 GK         Nottingham                 33
35                 GK    Manchester City                 22
36                 GK          Brentford                 23
37                 GK           Brighton                 22
38                 GK          Tottenham                 28
39                 GK            Burnley                 21
40                 GK          Liverpool                 28

   Unnamed: 6_level_0 Playing Time                ... Performance          \
                 Born           MP  Starts   Min  ...           D   L  CS
0                1992           26      26  2340  ...           8   5   8
1                1993           20      20  1800  ...           5  11   0
2                1994            1       1    90  ...           0   0   0
3                1998            6       6   540  ...           1   3   0
4                1993            1       1    90  ...           1   0   1
5                1993            3       3   270  ...           1   2   0
6                1991            7       6   585  ...           2   1   2
7                1990           22      22  1980  ...           8   7   5
8                1999           34      34  3060  ...           9   3  15
9                1989           35      35  3150  ...           8  23   4
10               2003            3       3   270  ...           0   1   1
11               1996            1       0    45  ...           0   0   0
12               1997           37      37  3330  ...          11  15  11
13               2000           18      18  1620  ...           4   8   7
14               1996            5       5   437  ...           0   4   1
15               1993           12      12  1080  ...           2  10   0
16               2002            5       3   379  ...           2   0   0
17               1998           37      37  3330  ...          11  13  10
18               2003            7       7   630  ...           2   2   2
19               2002           32      32  2880  ...          10   4   8
20               1992           38      38  3420  ...           7  16   9
21               2000           10      10   867  ...           1   6   2
22               1992           32      32  2835  ...           6  10   8
23               1992            3       3   270  ...           1   2   1
24               1997           16      16  1440  ...           6   6   3
25               Born           MP  Starts   Min  ...           D   L  CS
26               1999           38      38  3420  ...          18   7  11
27               1994           38      38  3420  ...          10  15  11
28               1992           27      27  2416  ...           5  12   7
29               1998           12      11  1004  ...           2   5   1
30               1995           37      37  3330  ...           7   5  19
31               2003           35      35  3150  ...          12  11  10
32               1993           23      23  2070  ...           8  12   4
33               1997           35      35  3039  ...           8  14   9
34               1992           31      30  2668  ...          10  10   7
35               2002            4       4   360  ...           0   3   1
36               2001            1       1    90  ...           0   0   0
37               2002           38      38  3420  ...          11  13  10
38               1996           31      31  2790  ...           9  15   7
39               2004            3       3   270  ...           2   1   0
40               1997            3       2   213  ...           0   1   0

          Penalty Kicks                        Unnamed: 26_level_0
      CS%         PKatt  PKA  PKsv  PKm  Save%             Matches
0    30.8             2    2     0    0    0.0             Matches
1     0.0             6    5     0    1    0.0             Matches
2     0.0             0    0     0    0    NaN             Matches
3     0.0             0    0     0    0    NaN             Matches
4   100.0             1    0     0    1    NaN             Matches
5     0.0             1    1     0    0    0.0             Matches
6    33.3             1    1     0    0    0.0             Matches
7    22.7             2    2     0    0    0.0             Matches
8    44.1             1    0     1    0  100.0             Matches
9    11.4             7    6     0    1    0.0             Matches
10   33.3             0    0     0    0    NaN             Matches
11    NaN             0    0     0    0    NaN             Matches
12   29.7             6    5     1    0   16.7             Matches
13   38.9             1    1     0    0    0.0             Matches
14   20.0             1    1     0    0    0.0             Matches
15    0.0             1    1     0    0    0.0             Matches
16    0.0             0    0     0    0    NaN             Matches
17   27.0             8    5     3    0   37.5             Matches
18   28.6             1    1     0    0    0.0             Matches
19   25.0             4    4     0    0    0.0             Matches
20   23.7             4    3     0    1    0.0             Matches
21   20.0             2    1     1    0   50.0             Matches
22   25.0             1    0     1    0  100.0             Matches
23   33.3             0    0     0    0    NaN             Matches
24   18.8             4    4     0    0    0.0             Matches
25    CS%         PKatt  PKA  PKsv  PKm  Save%             Matches
26   28.9             6    6     0    0    0.0             Matches
27   28.9             4    3     1    0   25.0             Matches
28   25.9             2    2     0    0    0.0             Matches
29    9.1             3    3     0    0    0.0             Matches
30   51.4             0    0     0    0    NaN             Matches
31   28.6             3    2     1    0   33.3             Matches
32   17.4             3    3     0    0    0.0             Matches
33   25.7             2    2     0    0    0.0             Matches
34   23.3             5    4     1    0   20.0             Matches
35   25.0             1    1     0    0    0.0             Matches
36    0.0             0    0     0    0    NaN             Matches
37   26.3             6    5     1    0   16.7             Matches
38   22.6             2    2     0    0    0.0             Matches
39    0.0             1    1     0    0    0.0             Matches
40    0.0             0    0     0    0    NaN             Matches

[41 rows x 27 columns]

In [7]:
standard_stats_df

    Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Player             Nation
0                    1     Brenden Aaronson             us USA
1                    2         Jerome Abbey            eng ENG
2                    3          Zach Abbott            eng ENG
3                    4        Tammy Abraham            eng ENG
4                    5    Joshua Acheampong            eng ENG
..                 ...                  ...                ...
568                548  Oleksandr Zinchenko             ua UKR
569                549       Joshua Zirkzee             nl NED
570                550     Martín Zubimendi             es ESP
571                 Rk               Player             Nation
572                551      Martin Ødegaard             no NOR

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos              Squad                Age
0                MF,FW       Leeds United                 24
1                   MF             Wolves                 15
2                   DF         Nottingham                 19
3                   FW        Aston Villa                 27
4                   DF            Chelsea                 19
..                 ...                ...                ...
568                 DF         Nottingham                 28
569              FW,MF     Manchester Utd                 24
570                 MF            Arsenal                 26
571                Pos              Squad                Age
572                 MF            Arsenal                 26

    Unnamed: 6_level_0 Playing Time                ... Performance         \
                  Born           MP  Starts   Min  ...          PK  PKatt
0                 2000           37      30  2449  ...           0      0
1                 2009            1       0    17  ...           0      0
2                 2006            3       2   164  ...           0      0
3                 1997           12       2   286  ...           0      0
4                 2006           17       8   666  ...           0      0
..                 ...          ...     ...   ...  ...         ...    ...
568               1996            5       4   353  ...           0      0
569               2001           24       5   626  ...           0      0
570               1999           38      34  2992  ...           0      0
571               Born           MP  Starts   Min  ...          PK  PKatt
572               1998           24      16  1369  ...           0      0

                Per 90 Minutes                           Unnamed: 24_level_0
     CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
0       3     0           0.15  0.18  0.33  0.15    0.33             Matches
1       0     0           0.00  0.00  0.00  0.00    0.00             Matches
2       0     0           0.00  0.00  0.00  0.00    0.00             Matches
3       0     0           0.63  0.00  0.63  0.63    0.63             Matches
4       1     0           0.14  0.00  0.14  0.14    0.14             Matches
..    ...   ...            ...   ...   ...   ...     ...                 ...
568     0     0           0.00  0.00  0.00  0.00    0.00             Matches
569     3     0           0.29  0.14  0.43  0.29    0.43             Matches
570     4     0           0.15  0.03  0.18  0.15    0.18             Matches
571  CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
572     0     0           0.07  0.39  0.46  0.07    0.46             Matches

[573 rows x 25 columns]

In [8]:
shooting_df

    Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Player             Nation
0                    1     Brenden Aaronson             us USA
1                    2         Jerome Abbey            eng ENG
2                    3          Zach Abbott            eng ENG
3                    4        Tammy Abraham            eng ENG
4                    5    Joshua Acheampong            eng ENG
..                 ...                  ...                ...
568                548  Oleksandr Zinchenko             ua UKR
569                549       Joshua Zirkzee             nl NED
570                550     Martín Zubimendi             es ESP
571                 Rk               Player             Nation
572                551      Martin Ødegaard             no NOR

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos              Squad                Age
0                MF,FW       Leeds United                 24
1                   MF             Wolves                 15
2                   DF         Nottingham                 19
3                   FW        Aston Villa                 27
4                   DF            Chelsea                 19
..                 ...                ...                ...
568                 DF         Nottingham                 28
569              FW,MF     Manchester Utd                 24
570                 MF            Arsenal                 26
571                Pos              Squad                Age
572                 MF            Arsenal                 26

    Unnamed: 6_level_0 Unnamed: 7_level_0 Standard                        \
                  Born                90s      Gls  Sh  SoT  SoT%  Sh/90
0                 2000               27.2        4  47   17  36.2   1.73
1                 2009                0.2        0   0    0   NaN   0.00
2                 2006                1.8        0   0    0   NaN   0.00
3                 1997                3.2        2   9    3  33.3   2.83
4                 2006                7.4        1   4    2  50.0   0.54
..                 ...                ...      ...  ..  ...   ...    ...
568               1996                3.9        0   4    2  50.0   1.02
569               2001                7.0        2  25    9  36.0   3.59
570               1999               33.2        5  27    9  33.3   0.81
571               Born                90s      Gls  Sh  SoT  SoT%  Sh/90
572               1998               15.2        1  22    8  36.4   1.45

                                    Unnamed: 18_level_0
     SoT/90  G/Sh  G/SoT  PK  PKatt             Matches
0      0.62  0.09   0.24   0      0             Matches
1      0.00   NaN    NaN   0      0             Matches
2      0.00   NaN    NaN   0      0             Matches
3      0.94  0.22   0.67   0      0             Matches
4      0.27  0.25   0.50   0      0             Matches
..      ...   ...    ...  ..    ...                 ...
568    0.51  0.00   0.00   0      0             Matches
569    1.29  0.08   0.22   0      0             Matches
570    0.27  0.19   0.56   0      0             Matches
571  SoT/90  G/Sh  G/SoT  PK  PKatt             Matches
572    0.53  0.05   0.13   0      0             Matches

[573 rows x 19 columns]

In [9]:
playingtime_df

    Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Player             Nation
0                    1     Brenden Aaronson             us USA
1                    2         Jerome Abbey            eng ENG
2                    3          Zach Abbott            eng ENG
3                    4        Tammy Abraham            eng ENG
4                    5    Joshua Acheampong            eng ENG
..                 ...                  ...                ...
715                689            Leny Yoro             fr FRA
716                690  Oleksandr Zinchenko             ua UKR
717                691       Joshua Zirkzee             nl NED
718                692     Martín Zubimendi             es ESP
719                693      Martin Ødegaard             no NOR

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos              Squad                Age
0                MF,FW       Leeds United                 24
1                   MF             Wolves                 15
2                   DF         Nottingham                 19
3                   FW        Aston Villa                 27
4                   DF            Chelsea                 19
..                 ...                ...                ...
715                 DF     Manchester Utd                 19
716                 DF         Nottingham                 28
717              FW,MF     Manchester Utd                 24
718                 MF            Arsenal                 26
719                 MF            Arsenal                 26

    Unnamed: 6_level_0 Playing Time              ... Subs               \
                  Born           MP   Min Mn/MP  ... Subs Mn/Sub unSub
0                 2000           37  2449    66  ...    7     21     1
1                 2009            1    17    17  ...    1     17     1
2                 2006            3   164    55  ...    1     45    13
3                 1997           12   286    24  ...   10     14     2
4                 2006           17   666    39  ...    9     11    18
..                 ...          ...   ...   ...  ...  ...    ...   ...
715               2005           32  1740    54  ...   14     20     5
716               1996            5   353    71  ...    1     10     3
717               2001           24   626    26  ...   19     14    12
718               1999           38  2992    79  ...    4     32     0
719               1998           24  1369    57  ...    8     26     1

    Team Success                             Unnamed: 24_level_0
             PPM onG onGA  +/-  +/-90 On-Off             Matches
0           1.19  35   31   +4  +0.15  +1.17             Matches
1           1.00   0    0    0   0.00  +1.08             Matches
2           1.00   2    4   -2  -1.10  -1.07             Matches
3           1.00   4    8   -4  -1.26  -1.57             Matches
4           1.18  10   13   -3  -0.41  -0.70             Matches
..           ...  ..  ...  ...    ...    ...                 ...
715         1.72  28   33   -5  -0.26  -1.54             Matches
716         0.20   1    6   -5  -1.27  -1.33             Matches
717         1.79   9    8   +1  +0.14  -0.44             Matches
718         2.24  57   25  +32  +0.96  -1.56             Matches
719         2.17  29   13  +16  +1.05  -0.18             Matches

[720 rows x 25 columns]

In [10]:
misc_stats_df

    Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Player             Nation
0                    1     Brenden Aaronson             us USA
1                    2         Jerome Abbey            eng ENG
2                    3          Zach Abbott            eng ENG
3                    4        Tammy Abraham            eng ENG
4                    5    Joshua Acheampong            eng ENG
..                 ...                  ...                ...
568                548  Oleksandr Zinchenko             ua UKR
569                549       Joshua Zirkzee             nl NED
570                550     Martín Zubimendi             es ESP
571                 Rk               Player             Nation
572                551      Martin Ødegaard             no NOR

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos              Squad                Age
0                MF,FW       Leeds United                 24
1                   MF             Wolves                 15
2                   DF         Nottingham                 19
3                   FW        Aston Villa                 27
4                   DF            Chelsea                 19
..                 ...                ...                ...
568                 DF         Nottingham                 28
569              FW,MF     Manchester Utd                 24
570                 MF            Arsenal                 26
571                Pos              Squad                Age
572                 MF            Arsenal                 26

    Unnamed: 6_level_0 Unnamed: 7_level_0 Performance        ...            \
                  Born                90s        CrdY  CrdR  ...  Fls  Fld
0                 2000               27.2           3     0  ...   20   51
1                 2009                0.2           0     0  ...    0    0
2                 2006                1.8           0     0  ...    3    1
3                 1997                3.2           0     0  ...    2    0
4                 2006                7.4           1     0  ...    2    9
..                 ...                ...         ...   ...  ...  ...  ...
568               1996                3.9           0     0  ...    1    2
569               2001                7.0           3     0  ...    8    6
570               1999               33.2           4     0  ...   33   15
571               Born                90s        CrdY  CrdR  ...  Fls  Fld
572               1998               15.2           0     0  ...    9    9

                                           Unnamed: 20_level_0
     Off  Crs  Int  TklW  PKwon  PKcon  OG             Matches
0      5   37   17    27    NaN    NaN   0             Matches
1      1    0    1     0    NaN    NaN   0             Matches
2      0    3    2     4    NaN    NaN   0             Matches
3      0    1    0     1    NaN    NaN   0             Matches
4      2    1   12     8    NaN    NaN   0             Matches
..   ...  ...  ...   ...    ...    ...  ..                 ...
568    1   18    2     6    NaN    NaN   0             Matches
569    1    5    1     6    NaN    NaN   0             Matches
570    1   13   39    39    NaN    NaN   0             Matches
571  Off  Crs  Int  TklW  PKwon  PKcon  OG             Matches
572    2   22    7     9    NaN    NaN   0             Matches

[573 rows x 21 columns]

### Goalkeeping

#### Flatten the MultiIndex header

In [11]:
goalkeeping_df.columns

MultiIndex([( 'Unnamed: 0_level_0',      'Rk'),
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 2_level_0',  'Nation'),
            ( 'Unnamed: 3_level_0',     'Pos'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',     'Age'),
            ( 'Unnamed: 6_level_0',    'Born'),
            (       'Playing Time',      'MP'),
            (       'Playing Time',  'Starts'),
            (       'Playing Time',     'Min'),
            (       'Playing Time',     '90s'),
            (        'Performance',      'GA'),
            (        'Performance',    'GA90'),
            (        'Performance',    'SoTA'),
            (        'Performance',   'Saves'),
            (        'Performance',   'Save%'),
            (        'Performance',       'W'),
            (        'Performance',       'D'),
            (        'Performance',       'L'),
            (        'Performance',      'CS'),
            (        'Performance',     'CS%'),
            (      'Penalty Kicks',   'PKatt'),
            (      'Penalty Kicks',     'PKA'),
            (      'Penalty Kicks',    'PKsv'),
            (      'Penalty Kicks',     'PKm'),
            (      'Penalty Kicks',   'Save%'),
            ('Unnamed: 26_level_0', 'Matches')],
           )

In [12]:
goalkeeping_df

   Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Rk                Player             Nation
0                   1               Alisson             br BRA
1                   2       Alphonse Areola             fr FRA
2                   3     Kepa Arrizabalaga             es ESP
3                   4        Altay Bayındır             tr TUR
4                   5        Walter Benítez             ar ARG
5                   6        Daniel Bentley            eng ENG
6                   7           Marco Bizot             nl NED
7                   8           Karl Darlow            wls WAL
8                   9  Gianluigi Donnarumma             it ITA
9                  10       Martin Dúbravka             sk SVK
10                 11        Melker Ellborg             se SWE
11                 12            Angus Gunn            sct SCO
12                 13        Dean Henderson            eng ENG
13                 14        Mads Hermansen             dk DEN
14                 15                  John             br BRA
15                 16         Sam Johnstone            eng ENG
16                 17       Filip Jørgensen             dk DEN
17                 18     Caoimhín Kelleher             ie IRL
18                 19        Antonín Kinský             cz CZE
19                 20         Senne Lammens             be BEL
20                 21            Bernd Leno             de GER
21                 22  Giorgi Mamardashvili             ge GEO
22                 23     Emiliano Martínez             ar ARG
23                 24         Stefan Ortega             de GER
24                 25           Lucas Perri             br BRA
25                 Rk                Player             Nation
26                 26        Đorđe Petrović             rs SRB
27                 27       Jordan Pickford            eng ENG
28                 28             Nick Pope            eng ENG
29                 29        Aaron Ramsdale            eng ENG
30                 30            David Raya             es ESP
31                 31           Robin Roefs             nl NED
32                 32               José Sá             pt POR
33                 33        Robert Sánchez             es ESP
34                 34             Matz Sels             be BEL
35                 35        James Trafford            eng ENG
36                 36    Hákon Valdimarsson             is ISL
37                 37       Bart Verbruggen             nl NED
38                 38     Guglielmo Vicario             it ITA
39                 39              Max Weiß             de GER
40                 40       Freddie Woodman            eng ENG

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                  Pos              Squad                Age
0                  GK          Liverpool                 32
1                  GK           West Ham                 32
2                  GK            Arsenal                 30
3                  GK     Manchester Utd                 27
4                  GK     Crystal Palace                 32
5                  GK             Wolves                 32
6                  GK        Aston Villa                 34
7                  GK       Leeds United                 34
8                  GK    Manchester City                 26
9                  GK            Burnley                 36
10                 GK         Sunderland                 22
11                 GK         Nottingham                 29
12                 GK     Crystal Palace                 28
13                 GK           West Ham                 25
14                 GK         Nottingham                 29
15                 GK             Wolves                 32
16                 GK            Chelsea                 23
17                 GK          Brentford                 26
18                 GK          Tottenham                 22
19                 GK     Manchester Utd                 23
20                 GK             Fulham                 33
21                 GK          Liverpool                 24
22                 GK        Aston Villa                 32
23                 GK         Nottingham                 32
24                 GK       Leeds United                 27
25                Pos              Squad                Age
26                 GK        Bournemouth                 25
27                 GK            Everton                 31
28                 GK          Newcastle                 33
29                 GK          Newcastle                 27
30                 GK            Arsenal                 29
31                 GK         Sunderland                 22
32                 GK             Wolves                 32
33                 GK            Chelsea                 27
34                 GK         Nottingham                 33
35                 GK    Manchester City                 22
36                 GK          Brentford                 23
37                 GK           Brighton                 22
38                 GK          Tottenham                 28
39                 GK            Burnley                 21
40                 GK          Liverpool                 28

   Unnamed: 6_level_0 Playing Time                ... Performance          \
                 Born           MP  Starts   Min  ...           D   L  CS
0                1992           26      26  2340  ...           8   5   8
1                1993           20      20  1800  ...           5  11   0
2                1994            1       1    90  ...           0   0   0
3                1998            6       6   540  ...           1   3   0
4                1993            1       1    90  ...           1   0   1
5                1993            3       3   270  ...           1   2   0
6                1991            7       6   585  ...           2   1   2
7                1990           22      22  1980  ...           8   7   5
8                1999           34      34  3060  ...           9   3  15
9                1989           35      35  3150  ...           8  23   4
10               2003            3       3   270  ...           0   1   1
11               1996            1       0    45  ...           0   0   0
12               1997           37      37  3330  ...          11  15  11
13               2000           18      18  1620  ...           4   8   7
14               1996            5       5   437  ...           0   4   1
15               1993           12      12  1080  ...           2  10   0
16               2002            5       3   379  ...           2   0   0
17               1998           37      37  3330  ...          11  13  10
18               2003            7       7   630  ...           2   2   2
19               2002           32      32  2880  ...          10   4   8
20               1992           38      38  3420  ...           7  16   9
21               2000           10      10   867  ...           1   6   2
22               1992           32      32  2835  ...           6  10   8
23               1992            3       3   270  ...           1   2   1
24               1997           16      16  1440  ...           6   6   3
25               Born           MP  Starts   Min  ...           D   L  CS
26               1999           38      38  3420  ...          18   7  11
27               1994           38      38  3420  ...          10  15  11
28               1992           27      27  2416  ...           5  12   7
29               1998           12      11  1004  ...           2   5   1
30               1995           37      37  3330  ...           7   5  19
31               2003           35      35  3150  ...          12  11  10
32               1993           23      23  2070  ...           8  12   4
33               1997           35      35  3039  ...           8  14   9
34               1992           31      30  2668  ...          10  10   7
35               2002            4       4   360  ...           0   3   1
36               2001            1       1    90  ...           0   0   0
37               2002           38      38  3420  ...          11  13  10
38               1996           31      31  2790  ...           9  15   7
39               2004            3       3   270  ...           2   1   0
40               1997            3       2   213  ...           0   1   0

          Penalty Kicks                        Unnamed: 26_level_0
      CS%         PKatt  PKA  PKsv  PKm  Save%             Matches
0    30.8             2    2     0    0    0.0             Matches
1     0.0             6    5     0    1    0.0             Matches
2     0.0             0    0     0    0    NaN             Matches
3     0.0             0    0     0    0    NaN             Matches
4   100.0             1    0     0    1    NaN             Matches
5     0.0             1    1     0    0    0.0             Matches
6    33.3             1    1     0    0    0.0             Matches
7    22.7             2    2     0    0    0.0             Matches
8    44.1             1    0     1    0  100.0             Matches
9    11.4             7    6     0    1    0.0             Matches
10   33.3             0    0     0    0    NaN             Matches
11    NaN             0    0     0    0    NaN             Matches
12   29.7             6    5     1    0   16.7             Matches
13   38.9             1    1     0    0    0.0             Matches
14   20.0             1    1     0    0    0.0             Matches
15    0.0             1    1     0    0    0.0             Matches
16    0.0             0    0     0    0    NaN             Matches
17   27.0             8    5     3    0   37.5             Matches
18   28.6             1    1     0    0    0.0             Matches
19   25.0             4    4     0    0    0.0             Matches
20   23.7             4    3     0    1    0.0             Matches
21   20.0             2    1     1    0   50.0             Matches
22   25.0             1    0     1    0  100.0             Matches
23   33.3             0    0     0    0    NaN             Matches
24   18.8             4    4     0    0    0.0             Matches
25    CS%         PKatt  PKA  PKsv  PKm  Save%             Matches
26   28.9             6    6     0    0    0.0             Matches
27   28.9             4    3     1    0   25.0             Matches
28   25.9             2    2     0    0    0.0             Matches
29    9.1             3    3     0    0    0.0             Matches
30   51.4             0    0     0    0    NaN             Matches
31   28.6             3    2     1    0   33.3             Matches
32   17.4             3    3     0    0    0.0             Matches
33   25.7             2    2     0    0    0.0             Matches
34   23.3             5    4     1    0   20.0             Matches
35   25.0             1    1     0    0    0.0             Matches
36    0.0             0    0     0    0    NaN             Matches
37   26.3             6    5     1    0   16.7             Matches
38   22.6             2    2     0    0    0.0             Matches
39    0.0             1    1     0    0    0.0             Matches
40    0.0             0    0     0    0    NaN             Matches

[41 rows x 27 columns]

In [13]:
goalkeeping_df.columns = [lev2 if "Unnamed:" in lev1 else f"{lev1}_{lev2}" for lev1, lev2 in goalkeeping_df.columns]

In [14]:
goalkeeping_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rk                   41 non-null     str
 1   Player               41 non-null     str
 2   Nation               41 non-null     str
 3   Pos                  41 non-null     str
 4   Squad                41 non-null     str
 5   Age                  41 non-null     str
 6   Born                 41 non-null     str
 7   Playing Time_MP      41 non-null     str
 8   Playing Time_Starts  41 non-null     str
 9   Playing Time_Min     41 non-null     str
 10  Playing Time_90s     41 non-null     str
 11  Performance_GA       41 non-null     str
 12  Performance_GA90     41 non-null     str
 13  Performance_SoTA     41 non-null     str
 14  Performance_Saves    41 non-null     str
 15  Performance_Save%    40 non-null     str
 16  Performance_W        41 non-null     str
 17  Performance_D        41 non-null     str
 18  Performance_L        41 non-null     str
 19  Performance_CS       41 non-null     str
 20  Performance_CS%      40 non-null     str
 21  Penalty Kicks_PKatt  41 non-null     str
 22  Penalty Kicks_PKA    41 non-null     str
 23  Penalty Kicks_PKsv   41 non-null     str
 24  Penalty Kicks_PKm    41 non-null     str
 25  Penalty Kicks_Save%  31 non-null     str
 26  Matches              41 non-null     str
dtypes: str(27)
memory usage: 12.2 KB

In [15]:
del_index = goalkeeping_df.loc[goalkeeping_df["Rk"] == "Rk"].index[0]
goalkeeping_df.drop(index=del_index, inplace=True)

In [16]:
str_columns = ["Rk", "Player", "Nation", "Pos", "Squad", "Age", "Born", "Matches"]

In [17]:
numeric_col = goalkeeping_df.drop(columns=str_columns).columns

In [18]:
for col in numeric_col:
    goalkeeping_df[col] = goalkeeping_df[col].astype("float")

In [19]:
goalkeeping_df.info()

<class 'pandas.DataFrame'>
Index: 40 entries, 0 to 40
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rk                   40 non-null     str
 1   Player               40 non-null     str
 2   Nation               40 non-null     str
 3   Pos                  40 non-null     str
 4   Squad                40 non-null     str
 5   Age                  40 non-null     str
 6   Born                 40 non-null     str
 7   Playing Time_MP      40 non-null     float64
 8   Playing Time_Starts  40 non-null     float64
 9   Playing Time_Min     40 non-null     float64
 10  Playing Time_90s     40 non-null     float64
 11  Performance_GA       40 non-null     float64
 12  Performance_GA90     40 non-null     float64
 13  Performance_SoTA     40 non-null     float64
 14  Performance_Saves    40 non-null     float64
 15  Performance_Save%    39 non-null     float64
 16  Performance_W        40 non-null     float64
 17  Performance_D        40 non-null     float64
 18  Performance_L        40 non-null     float64
 19  Performance_CS       40 non-null     float64
 20  Performance_CS%      39 non-null     float64
 21  Penalty Kicks_PKatt  40 non-null     float64
 22  Penalty Kicks_PKA    40 non-null     float64
 23  Penalty Kicks_PKsv   40 non-null     float64
 24  Penalty Kicks_PKm    40 non-null     float64
 25  Penalty Kicks_Save%  30 non-null     float64
 26  Matches              40 non-null     str
dtypes: float64(19), str(8)
memory usage: 10.6 KB

In [20]:
goalkeeping_df[goalkeeping_df["Playing Time_Min"] > 900]["Squad"].nunique()

20

In [21]:
# goalkeeping_df = goalkeeping_df[goalkeeping_df["Playing Time_Min"] > 900]

In [22]:
goalkeeping_df.drop(columns="Matches", inplace=True)

In [23]:
goalkeeping_df

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Performance_W,Performance_D,Performance_L,Performance_CS,Performance_CS%,Penalty Kicks_PKatt,Penalty Kicks_PKA,Penalty Kicks_PKsv,Penalty Kicks_PKm,Penalty Kicks_Save%
0,1,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,...,13.0,8.0,5.0,8.0,30.8,2.0,2.0,0.0,0.0,0.0
1,2,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,...,4.0,5.0,11.0,0.0,0.0,6.0,5.0,0.0,1.0,0.0
2,3,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,4,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,5,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,NaN
5,6,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,...,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6,7,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,...,3.0,2.0,1.0,2.0,33.3,1.0,1.0,0.0,0.0,0.0
7,8,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,...,7.0,8.0,7.0,5.0,22.7,2.0,2.0,0.0,0.0,0.0
8,9,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,...,22.0,9.0,3.0,15.0,44.1,1.0,0.0,1.0,0.0,100.0
9,10,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,...,4.0,8.0,23.0,4.0,11.4,7.0,6.0,0.0,1.0,0.0
10,11,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
11,12,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN
12,13,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,...,11.0,11.0,15.0,11.0,29.7,6.0,5.0,1.0,0.0,16.7
13,14,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,...,6.0,4.0,8.0,7.0,38.9,1.0,1.0,0.0,0.0,0.0
14,15,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,...,1.0,0.0,4.0,1.0,20.0,1.0,1.0,0.0,0.0,0.0
15,16,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,...,0.0,2.0,10.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
16,17,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
17,18,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,...,13.0,11.0,13.0,10.0,27.0,8.0,5.0,3.0,0.0,37.5
18,19,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,...,3.0,2.0,2.0,2.0,28.6,1.0,1.0,0.0,0.0,0.0
19,20,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,...,18.0,10.0,4.0,8.0,25.0,4.0,4.0,0.0,0.0,0.0
20,21,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,...,15.0,7.0,16.0,9.0,23.7,4.0,3.0,0.0,1.0,0.0
21,22,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,...,3.0,1.0,6.0,2.0,20.0,2.0,1.0,1.0,0.0,50.0
22,23,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,...,16.0,6.0,10.0,8.0,25.0,1.0,0.0,1.0,0.0,100.0
23,24,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
24,25,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,...,4.0,6.0,6.0,3.0,18.8,4.0,4.0,0.0,0.0,0.0
26,26,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,...,13.0,18.0,7.0,11.0,28.9,6.0,6.0,0.0,0.0,0.0
27,27,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,...,13.0,10.0,15.0,11.0,28.9,4.0,3.0,1.0,0.0,25.0
28,28,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,...,10.0,5.0,12.0,7.0,25.9,2.0,2.0,0.0,0.0,0.0
29,29,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,...,4.0,2.0,5.0,1.0,9.1,3.0,3.0,0.0,0.0,0.0
30,30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,NaN
31,31,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,...,12.0,12.0,11.0,10.0,28.6,3.0,2.0,1.0,0.0,33.3
32,32,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,...,3.0,8.0,12.0,4.0,17.4,3.0,3.0,0.0,0.0,0.0
33,33,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,...,13.0,8.0,14.0,9.0,25.7,2.0,2.0,0.0,0.0,0.0
34,34,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,...,10.0,10.0,10.0,7.0,23.3,5.0,4.0,1.0,0.0,20.0
35,35,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,...,1.0,0.0,3.0,1.0,25.0,1.0,1.0,0.0,0.0,0.0
36,36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
37,37,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,...,14.0,11.0,13.0,10.0,26.3,6.0,5.0,1.0,0.0,16.7
38,38,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,...,7.0,9.0,15.0,7.0,22.6,2.0,2.0,0.0,0.0,0.0
39,39,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,...,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
40,40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [24]:
goalkeeping_df.info()

<class 'pandas.DataFrame'>
Index: 40 entries, 0 to 40
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rk                   40 non-null     str
 1   Player               40 non-null     str
 2   Nation               40 non-null     str
 3   Pos                  40 non-null     str
 4   Squad                40 non-null     str
 5   Age                  40 non-null     str
 6   Born                 40 non-null     str
 7   Playing Time_MP      40 non-null     float64
 8   Playing Time_Starts  40 non-null     float64
 9   Playing Time_Min     40 non-null     float64
 10  Playing Time_90s     40 non-null     float64
 11  Performance_GA       40 non-null     float64
 12  Performance_GA90     40 non-null     float64
 13  Performance_SoTA     40 non-null     float64
 14  Performance_Saves    40 non-null     float64
 15  Performance_Save%    39 non-null     float64
 16  Performance_W        40 non-null     float64
 17  Performance_D        40 non-null     float64
 18  Performance_L        40 non-null     float64
 19  Performance_CS       40 non-null     float64
 20  Performance_CS%      39 non-null     float64
 21  Penalty Kicks_PKatt  40 non-null     float64
 22  Penalty Kicks_PKA    40 non-null     float64
 23  Penalty Kicks_PKsv   40 non-null     float64
 24  Penalty Kicks_PKm    40 non-null     float64
 25  Penalty Kicks_Save%  30 non-null     float64
dtypes: float64(19), str(7)
memory usage: 10.0 KB

In [25]:
goalkeeping_df[goalkeeping_df["Penalty Kicks_Save%"].isna()]

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Performance_W,Performance_D,Performance_L,Performance_CS,Performance_CS%,Penalty Kicks_PKatt,Penalty Kicks_PKA,Penalty Kicks_PKsv,Penalty Kicks_PKm,Penalty Kicks_Save%
2,3,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,4,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,5,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,NaN
10,11,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
11,12,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN
16,17,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
23,24,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,NaN
30,30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,NaN
36,36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
40,40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [26]:
goalkeeping_df["Penalty Kicks_Save%"] = goalkeeping_df["Penalty Kicks_Save%"].fillna(0)

In [27]:
goalkeeping_df[goalkeeping_df["Penalty Kicks_Save%"].isna()]

Empty DataFrame
Columns: [Rk, Player, Nation, Pos, Squad, Age, Born, Playing Time_MP, Playing Time_Starts, Playing Time_Min, Playing Time_90s, Performance_GA, Performance_GA90, Performance_SoTA, Performance_Saves, Performance_Save%, Performance_W, Performance_D, Performance_L, Performance_CS, Performance_CS%, Penalty Kicks_PKatt, Penalty Kicks_PKA, Penalty Kicks_PKsv, Penalty Kicks_PKm, Penalty Kicks_Save%]
Index: []

[0 rows x 26 columns]

In [28]:
goalkeeping_df

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Performance_W,Performance_D,Performance_L,Performance_CS,Performance_CS%,Penalty Kicks_PKatt,Penalty Kicks_PKA,Penalty Kicks_PKsv,Penalty Kicks_PKm,Penalty Kicks_Save%
0,1,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,...,13.0,8.0,5.0,8.0,30.8,2.0,2.0,0.0,0.0,0.0
1,2,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,...,4.0,5.0,11.0,0.0,0.0,6.0,5.0,0.0,1.0,0.0
2,3,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,0.0
5,6,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,...,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6,7,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,...,3.0,2.0,1.0,2.0,33.3,1.0,1.0,0.0,0.0,0.0
7,8,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,...,7.0,8.0,7.0,5.0,22.7,2.0,2.0,0.0,0.0,0.0
8,9,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,...,22.0,9.0,3.0,15.0,44.1,1.0,0.0,1.0,0.0,100.0
9,10,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,...,4.0,8.0,23.0,4.0,11.4,7.0,6.0,0.0,1.0,0.0
10,11,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
11,12,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
12,13,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,...,11.0,11.0,15.0,11.0,29.7,6.0,5.0,1.0,0.0,16.7
13,14,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,...,6.0,4.0,8.0,7.0,38.9,1.0,1.0,0.0,0.0,0.0
14,15,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,...,1.0,0.0,4.0,1.0,20.0,1.0,1.0,0.0,0.0,0.0
15,16,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,...,0.0,2.0,10.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
16,17,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,...,13.0,11.0,13.0,10.0,27.0,8.0,5.0,3.0,0.0,37.5
18,19,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,...,3.0,2.0,2.0,2.0,28.6,1.0,1.0,0.0,0.0,0.0
19,20,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,...,18.0,10.0,4.0,8.0,25.0,4.0,4.0,0.0,0.0,0.0
20,21,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,...,15.0,7.0,16.0,9.0,23.7,4.0,3.0,0.0,1.0,0.0
21,22,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,...,3.0,1.0,6.0,2.0,20.0,2.0,1.0,1.0,0.0,50.0
22,23,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,...,16.0,6.0,10.0,8.0,25.0,1.0,0.0,1.0,0.0,100.0
23,24,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
24,25,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,...,4.0,6.0,6.0,3.0,18.8,4.0,4.0,0.0,0.0,0.0
26,26,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,...,13.0,18.0,7.0,11.0,28.9,6.0,6.0,0.0,0.0,0.0
27,27,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,...,13.0,10.0,15.0,11.0,28.9,4.0,3.0,1.0,0.0,25.0
28,28,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,...,10.0,5.0,12.0,7.0,25.9,2.0,2.0,0.0,0.0,0.0
29,29,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,...,4.0,2.0,5.0,1.0,9.1,3.0,3.0,0.0,0.0,0.0
30,30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,0.0
31,31,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,...,12.0,12.0,11.0,10.0,28.6,3.0,2.0,1.0,0.0,33.3
32,32,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,...,3.0,8.0,12.0,4.0,17.4,3.0,3.0,0.0,0.0,0.0
33,33,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,...,13.0,8.0,14.0,9.0,25.7,2.0,2.0,0.0,0.0,0.0
34,34,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,...,10.0,10.0,10.0,7.0,23.3,5.0,4.0,1.0,0.0,20.0
35,35,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,...,1.0,0.0,3.0,1.0,25.0,1.0,1.0,0.0,0.0,0.0
36,36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,37,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,...,14.0,11.0,13.0,10.0,26.3,6.0,5.0,1.0,0.0,16.7
38,38,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,...,7.0,9.0,15.0,7.0,22.6,2.0,2.0,0.0,0.0,0.0
39,39,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,...,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
40,40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
goalkeeping_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min',
       'Playing Time_90s', 'Performance_GA', 'Performance_GA90',
       'Performance_SoTA', 'Performance_Saves', 'Performance_Save%',
       'Performance_W', 'Performance_D', 'Performance_L', 'Performance_CS',
       'Performance_CS%', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKA',
       'Penalty Kicks_PKsv', 'Penalty Kicks_PKm', 'Penalty Kicks_Save%'],
      dtype='str')

In [30]:
goalkeeping_col_rename_map = {
    "Playing Time_MP": "matches_played",
    "Playing Time_Starts": "starts",
    "Playing Time_Min": "minutes",
    "Playing Time_90s": "90s_played",
    "Performance_GA": "goals_against",
    "Performance_GA90": "goals_against_per90",
    "Performance_SoTA": "shots_on_target_against",
    "Performance_Saves": "saves",
    "Performance_Save%": "save_pct",
    "Performance_W": "wins",
    "Performance_D": "draws",
    "Performance_L": "losses",
    "Performance_CS": "clean_sheets",
    "Performance_CS%": "clean_sheet_pct",
    "Penalty Kicks_PKatt": "pk_attempted",
    "Penalty Kicks_PKA": "pk_allowed",
    "Penalty Kicks_PKsv": "pk_saved",
    "Penalty Kicks_PKm": "pk_missed",
    "Penalty Kicks_Save%": "pk_save_pct"
}

goalkeeping_df = goalkeeping_df.rename(columns=goalkeeping_col_rename_map)

In [31]:
goalkeeping_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,wins,draws,losses,clean_sheets,clean_sheet_pct,pk_attempted,pk_allowed,pk_saved,pk_missed,pk_save_pct
0,1,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,...,13.0,8.0,5.0,8.0,30.8,2.0,2.0,0.0,0.0,0.0
1,2,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,...,4.0,5.0,11.0,0.0,0.0,6.0,5.0,0.0,1.0,0.0
2,3,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,0.0
5,6,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,...,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6,7,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,...,3.0,2.0,1.0,2.0,33.3,1.0,1.0,0.0,0.0,0.0
7,8,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,...,7.0,8.0,7.0,5.0,22.7,2.0,2.0,0.0,0.0,0.0
8,9,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,...,22.0,9.0,3.0,15.0,44.1,1.0,0.0,1.0,0.0,100.0
9,10,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,...,4.0,8.0,23.0,4.0,11.4,7.0,6.0,0.0,1.0,0.0
10,11,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
11,12,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
12,13,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,...,11.0,11.0,15.0,11.0,29.7,6.0,5.0,1.0,0.0,16.7
13,14,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,...,6.0,4.0,8.0,7.0,38.9,1.0,1.0,0.0,0.0,0.0
14,15,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,...,1.0,0.0,4.0,1.0,20.0,1.0,1.0,0.0,0.0,0.0
15,16,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,...,0.0,2.0,10.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
16,17,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,...,13.0,11.0,13.0,10.0,27.0,8.0,5.0,3.0,0.0,37.5
18,19,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,...,3.0,2.0,2.0,2.0,28.6,1.0,1.0,0.0,0.0,0.0
19,20,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,...,18.0,10.0,4.0,8.0,25.0,4.0,4.0,0.0,0.0,0.0
20,21,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,...,15.0,7.0,16.0,9.0,23.7,4.0,3.0,0.0,1.0,0.0
21,22,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,...,3.0,1.0,6.0,2.0,20.0,2.0,1.0,1.0,0.0,50.0
22,23,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,...,16.0,6.0,10.0,8.0,25.0,1.0,0.0,1.0,0.0,100.0
23,24,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
24,25,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,...,4.0,6.0,6.0,3.0,18.8,4.0,4.0,0.0,0.0,0.0
26,26,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,...,13.0,18.0,7.0,11.0,28.9,6.0,6.0,0.0,0.0,0.0
27,27,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,...,13.0,10.0,15.0,11.0,28.9,4.0,3.0,1.0,0.0,25.0
28,28,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,...,10.0,5.0,12.0,7.0,25.9,2.0,2.0,0.0,0.0,0.0
29,29,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,...,4.0,2.0,5.0,1.0,9.1,3.0,3.0,0.0,0.0,0.0
30,30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,0.0
31,31,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,...,12.0,12.0,11.0,10.0,28.6,3.0,2.0,1.0,0.0,33.3
32,32,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,...,3.0,8.0,12.0,4.0,17.4,3.0,3.0,0.0,0.0,0.0
33,33,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,...,13.0,8.0,14.0,9.0,25.7,2.0,2.0,0.0,0.0,0.0
34,34,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,...,10.0,10.0,10.0,7.0,23.3,5.0,4.0,1.0,0.0,20.0
35,35,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,...,1.0,0.0,3.0,1.0,25.0,1.0,1.0,0.0,0.0,0.0
36,36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,37,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,...,14.0,11.0,13.0,10.0,26.3,6.0,5.0,1.0,0.0,16.7
38,38,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,...,7.0,9.0,15.0,7.0,22.6,2.0,2.0,0.0,0.0,0.0
39,39,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,...,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
40,40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
goalkeeping_df.to_parquet(ROOT / "data" /"raw" / "fbref_goalkeeping.parquet")

### Standard Stats

In [33]:
standard_stats_df

    Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Player             Nation
0                    1     Brenden Aaronson             us USA
1                    2         Jerome Abbey            eng ENG
2                    3          Zach Abbott            eng ENG
3                    4        Tammy Abraham            eng ENG
4                    5    Joshua Acheampong            eng ENG
..                 ...                  ...                ...
568                548  Oleksandr Zinchenko             ua UKR
569                549       Joshua Zirkzee             nl NED
570                550     Martín Zubimendi             es ESP
571                 Rk               Player             Nation
572                551      Martin Ødegaard             no NOR

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   Pos              Squad                Age
0                MF,FW       Leeds United                 24
1                   MF             Wolves                 15
2                   DF         Nottingham                 19
3                   FW        Aston Villa                 27
4                   DF            Chelsea                 19
..                 ...                ...                ...
568                 DF         Nottingham                 28
569              FW,MF     Manchester Utd                 24
570                 MF            Arsenal                 26
571                Pos              Squad                Age
572                 MF            Arsenal                 26

    Unnamed: 6_level_0 Playing Time                ... Performance         \
                  Born           MP  Starts   Min  ...          PK  PKatt
0                 2000           37      30  2449  ...           0      0
1                 2009            1       0    17  ...           0      0
2                 2006            3       2   164  ...           0      0
3                 1997           12       2   286  ...           0      0
4                 2006           17       8   666  ...           0      0
..                 ...          ...     ...   ...  ...         ...    ...
568               1996            5       4   353  ...           0      0
569               2001           24       5   626  ...           0      0
570               1999           38      34  2992  ...           0      0
571               Born           MP  Starts   Min  ...          PK  PKatt
572               1998           24      16  1369  ...           0      0

                Per 90 Minutes                           Unnamed: 24_level_0
     CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
0       3     0           0.15  0.18  0.33  0.15    0.33             Matches
1       0     0           0.00  0.00  0.00  0.00    0.00             Matches
2       0     0           0.00  0.00  0.00  0.00    0.00             Matches
3       0     0           0.63  0.00  0.63  0.63    0.63             Matches
4       1     0           0.14  0.00  0.14  0.14    0.14             Matches
..    ...   ...            ...   ...   ...   ...     ...                 ...
568     0     0           0.00  0.00  0.00  0.00    0.00             Matches
569     3     0           0.29  0.14  0.43  0.29    0.43             Matches
570     4     0           0.15  0.03  0.18  0.15    0.18             Matches
571  CrdY  CrdR            Gls   Ast   G+A  G-PK  G+A-PK             Matches
572     0     0           0.07  0.39  0.46  0.07    0.46             Matches

[573 rows x 25 columns]

In [34]:
standard_stats_df.columns

MultiIndex([( 'Unnamed: 0_level_0',      'Rk'),
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 2_level_0',  'Nation'),
            ( 'Unnamed: 3_level_0',     'Pos'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',     'Age'),
            ( 'Unnamed: 6_level_0',    'Born'),
            (       'Playing Time',      'MP'),
            (       'Playing Time',  'Starts'),
            (       'Playing Time',     'Min'),
            (       'Playing Time',     '90s'),
            (        'Performance',     'Gls'),
            (        'Performance',     'Ast'),
            (        'Performance',     'G+A'),
            (        'Performance',    'G-PK'),
            (        'Performance',      'PK'),
            (        'Performance',   'PKatt'),
            (        'Performance',    'CrdY'),
            (        'Performance',    'CrdR'),
            (     'Per 90 Minutes',     'Gls'),
            (     'Per 90 Minutes',     'Ast'),
            (     'Per 90 Minutes',     'G+A'),
            (     'Per 90 Minutes',    'G-PK'),
            (     'Per 90 Minutes',  'G+A-PK'),
            ('Unnamed: 24_level_0', 'Matches')],
           )

In [35]:
standard_stats_df.columns = [lev2 if "Unnamed:" in lev1 else f"{lev1}_{lev2}" for lev1, lev2 in standard_stats_df.columns]

In [36]:
standard_stats_df

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37,30,2449,...,0,0,3,0,0.15,0.18,0.33,0.15,0.33,Matches
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1,0,17,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3,2,164,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12,2,286,...,0,0,0,0,0.63,0.00,0.63,0.63,0.63,Matches
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17,8,666,...,0,0,1,0,0.14,0.00,0.14,0.14,0.14,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,5,4,353,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,24,5,626,...,0,0,3,0,0.29,0.14,0.43,0.29,0.43,Matches
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,38,34,2992,...,0,0,4,0,0.15,0.03,0.18,0.15,0.18,Matches
571,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,Matches
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,24,16,1369,...,0,0,0,0,0.07,0.39,0.46,0.07,0.46,Matches

In [37]:
standard_stats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rk                     573 non-null    str
 1   Player                 573 non-null    str
 2   Nation                 573 non-null    str
 3   Pos                    573 non-null    str
 4   Squad                  573 non-null    str
 5   Age                    573 non-null    str
 6   Born                   573 non-null    str
 7   Playing Time_MP        573 non-null    str
 8   Playing Time_Starts    573 non-null    str
 9   Playing Time_Min       573 non-null    str
 10  Playing Time_90s       573 non-null    str
 11  Performance_Gls        573 non-null    str
 12  Performance_Ast        573 non-null    str
 13  Performance_G+A        573 non-null    str
 14  Performance_G-PK       573 non-null    str
 15  Performance_PK         573 non-null    str
 16  Performance_PKatt      573 non-null    str
 17  Performance_CrdY       573 non-null    str
 18  Performance_CrdR       573 non-null    str
 19  Per 90 Minutes_Gls     573 non-null    str
 20  Per 90 Minutes_Ast     573 non-null    str
 21  Per 90 Minutes_G+A     573 non-null    str
 22  Per 90 Minutes_G-PK    573 non-null    str
 23  Per 90 Minutes_G+A-PK  573 non-null    str
 24  Matches                573 non-null    str
dtypes: str(25)
memory usage: 160.5 KB

In [38]:
str_columns

['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'Matches']

In [39]:
standard_stats_numeric_col = standard_stats_df.drop(columns=str_columns).columns

In [40]:
del_index = standard_stats_df[standard_stats_df["Rk"] == "Rk"].index
standard_stats_df.drop(index=del_index, inplace=True)

In [41]:
for col in standard_stats_numeric_col:
    standard_stats_df[col] = standard_stats_df[col].astype("float")

In [42]:
standard_stats_df.info()

<class 'pandas.DataFrame'>
Index: 551 entries, 0 to 572
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rk                     551 non-null    str
 1   Player                 551 non-null    str
 2   Nation                 551 non-null    str
 3   Pos                    551 non-null    str
 4   Squad                  551 non-null    str
 5   Age                    551 non-null    str
 6   Born                   551 non-null    str
 7   Playing Time_MP        551 non-null    float64
 8   Playing Time_Starts    551 non-null    float64
 9   Playing Time_Min       551 non-null    float64
 10  Playing Time_90s       551 non-null    float64
 11  Performance_Gls        551 non-null    float64
 12  Performance_Ast        551 non-null    float64
 13  Performance_G+A        551 non-null    float64
 14  Performance_G-PK       551 non-null    float64
 15  Performance_PK         551 non-null    float64
 16  Performance_PKatt      551 non-null    float64
 17  Performance_CrdY       551 non-null    float64
 18  Performance_CrdR       551 non-null    float64
 19  Per 90 Minutes_Gls     551 non-null    float64
 20  Per 90 Minutes_Ast     551 non-null    float64
 21  Per 90 Minutes_G+A     551 non-null    float64
 22  Per 90 Minutes_G-PK    551 non-null    float64
 23  Per 90 Minutes_G+A-PK  551 non-null    float64
 24  Matches                551 non-null    str
dtypes: float64(17), str(8)
memory usage: 138.1 KB

In [43]:
# standard_stats_df = standard_stats_df[standard_stats_df["Playing Time_Min"]  >= 900]

In [44]:
standard_stats_df["Pos"].value_counts()

Pos
MF       192
DF       141
FW        59
GK        40
MF,FW     38
DF,MF     33
FW,MF     32
MF,DF     16
Name: count, dtype: int64

In [45]:
standard_stats_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min',
       'Playing Time_90s', 'Performance_Gls', 'Performance_Ast',
       'Performance_G+A', 'Performance_G-PK', 'Performance_PK',
       'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR',
       'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A',
       'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK', 'Matches'],
      dtype='str')

In [46]:
standard_stats_rename_map = {
    "Playing Time_MP": "matches_played",
    "Playing Time_Starts": "starts",
    "Playing Time_Min": "minutes",
    "Playing Time_90s": "90s_played",
    "Performance_Gls": "goals",
    "Performance_Ast": "assists",
    "Performance_G+A": "goals_assists",
    "Performance_G-PK": "non_penalty_goals",
    "Performance_PK": "penalty_kicks_made",
    "Performance_PKatt": "penalty_kicks_attempted",
    "Performance_CrdY": "yellow_cards",
    "Performance_CrdR": "red_cards",
    "Per 90 Minutes_Gls": "goals_per90",
    "Per 90 Minutes_Ast": "assists_per90",
    "Per 90 Minutes_G+A": "goals_assists_per90",
    "Per 90 Minutes_G-PK": "non_penalty_goals_per90",
    "Per 90 Minutes_G+A-PK": "non_penalty_goals_assists_per90",
}

In [47]:
standard_stats_df = standard_stats_df.drop(columns="Matches").rename(columns=standard_stats_rename_map)

In [48]:
standard_stats_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,...,4.0,0.0,0.0,3.0,0.0,0.15,0.18,0.33,0.15,0.33
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,...,2.0,0.0,0.0,0.0,0.0,0.63,0.00,0.63,0.63,0.63
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,...,1.0,0.0,0.0,1.0,0.0,0.14,0.00,0.14,0.14,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,32.0,18.0,1740.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,5.0,4.0,353.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,24.0,5.0,626.0,...,2.0,0.0,0.0,3.0,0.0,0.29,0.14,0.43,0.29,0.43
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,38.0,34.0,2992.0,...,5.0,0.0,0.0,4.0,0.0,0.15,0.03,0.18,0.15,0.18
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,24.0,16.0,1369.0,...,1.0,0.0,0.0,0.0,0.0,0.07,0.39,0.46,0.07,0.46

In [49]:
standard_stats_df.to_parquet(ROOT / "data" /"raw" / "fbref_standard_stats.parquet")

### Shooting

In [50]:
shooting_df.columns

MultiIndex([( 'Unnamed: 0_level_0',      'Rk'),
            ( 'Unnamed: 1_level_0',  'Player'),
            ( 'Unnamed: 2_level_0',  'Nation'),
            ( 'Unnamed: 3_level_0',     'Pos'),
            ( 'Unnamed: 4_level_0',   'Squad'),
            ( 'Unnamed: 5_level_0',     'Age'),
            ( 'Unnamed: 6_level_0',    'Born'),
            ( 'Unnamed: 7_level_0',     '90s'),
            (           'Standard',     'Gls'),
            (           'Standard',      'Sh'),
            (           'Standard',     'SoT'),
            (           'Standard',    'SoT%'),
            (           'Standard',   'Sh/90'),
            (           'Standard',  'SoT/90'),
            (           'Standard',    'G/Sh'),
            (           'Standard',   'G/SoT'),
            (           'Standard',      'PK'),
            (           'Standard',   'PKatt'),
            ('Unnamed: 18_level_0', 'Matches')],
           )

In [51]:
shooting_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   (Unnamed: 0_level_0, Rk)        573 non-null    str
 1   (Unnamed: 1_level_0, Player)    573 non-null    str
 2   (Unnamed: 2_level_0, Nation)    573 non-null    str
 3   (Unnamed: 3_level_0, Pos)       573 non-null    str
 4   (Unnamed: 4_level_0, Squad)     573 non-null    str
 5   (Unnamed: 5_level_0, Age)       573 non-null    str
 6   (Unnamed: 6_level_0, Born)      573 non-null    str
 7   (Unnamed: 7_level_0, 90s)       573 non-null    str
 8   (Standard, Gls)                 573 non-null    str
 9   (Standard, Sh)                  573 non-null    str
 10  (Standard, SoT)                 573 non-null    str
 11  (Standard, SoT%)                478 non-null    str
 12  (Standard, Sh/90)               573 non-null    str
 13  (Standard, SoT/90)              573 non-null    str
 14  (Standard, G/Sh)                478 non-null    str
 15  (Standard, G/SoT)               415 non-null    str
 16  (Standard, PK)                  573 non-null    str
 17  (Standard, PKatt)               573 non-null    str
 18  (Unnamed: 18_level_0, Matches)  573 non-null    str
dtypes: str(19)
memory usage: 127.1 KB

In [52]:
shooting_df.columns = shooting_df.columns.get_level_values(1)

In [53]:
shooting_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Gls',
       'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'PK', 'PKatt',
       'Matches'],
      dtype='str')

In [54]:
del_index = shooting_df[shooting_df["Rk"] == "Rk"].index
shooting_df.drop(index=del_index, inplace=True)

In [55]:
shooting_numeric_col = shooting_df.drop(columns=str_columns).columns

for col in shooting_numeric_col:
    shooting_df[col] = shooting_df[col].astype("float")

shooting_df.info()

<class 'pandas.DataFrame'>
Index: 551 entries, 0 to 572
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       551 non-null    str
 1   Player   551 non-null    str
 2   Nation   551 non-null    str
 3   Pos      551 non-null    str
 4   Squad    551 non-null    str
 5   Age      551 non-null    str
 6   Born     551 non-null    str
 7   90s      551 non-null    float64
 8   Gls      551 non-null    float64
 9   Sh       551 non-null    float64
 10  SoT      551 non-null    float64
 11  SoT%     456 non-null    float64
 12  Sh/90    551 non-null    float64
 13  SoT/90   551 non-null    float64
 14  G/Sh     456 non-null    float64
 15  G/SoT    393 non-null    float64
 16  PK       551 non-null    float64
 17  PKatt    551 non-null    float64
 18  Matches  551 non-null    str
dtypes: float64(11), str(8)
memory usage: 112.2 KB

In [56]:
goalkeeper_index = shooting_df[shooting_df["Pos"] == "GK"].index

In [57]:
shooting_df.fillna(0.0, inplace=True)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,4.0,47.0,17.0,36.2,1.73,0.62,0.09,0.24,0.0,0.0,Matches
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,Matches
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,Matches
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,2.0,9.0,3.0,33.3,2.83,0.94,0.22,0.67,0.0,0.0,Matches
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,4.0,2.0,50.0,0.54,0.27,0.25,0.50,0.0,0.0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,19.3,0.0,9.0,3.0,33.3,0.47,0.16,0.00,0.00,0.0,0.0,Matches
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,3.9,0.0,4.0,2.0,50.0,1.02,0.51,0.00,0.00,0.0,0.0,Matches
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,7.0,2.0,25.0,9.0,36.0,3.59,1.29,0.08,0.22,0.0,0.0,Matches
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,33.2,5.0,27.0,9.0,33.3,0.81,0.27,0.19,0.56,0.0,0.0,Matches
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,15.2,1.0,22.0,8.0,36.4,1.45,0.53,0.05,0.13,0.0,0.0,Matches

In [58]:
shooting_df = shooting_df.drop(columns="Matches")

In [59]:
shooting_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Gls',
       'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'PK', 'PKatt'],
      dtype='str')

In [60]:
shooting_col_rename_map = {
    "90s": "90s_played",
    "Gls": "goals",
    "Sh": "shots_total",
    "SoT": "shots_on_target",
    "SoT%": "shots_on_target_pct",
    "Sh/90": "shots_per90",
    "SoT/90": "shots_on_target_per90",
    "G/Sh": "goals_per_shot",
    "G/SoT": "goals_per_shot_on_target",
    "PK": "penalty_kicks_made",
    "PKatt": "penalty_kicks_attempted"
}

shooting_df = shooting_df.rename(columns=shooting_col_rename_map)

In [61]:
shooting_df.to_parquet(ROOT / "data" /"raw" / "fbref_shooting.parquet")

### Playing Time

In [62]:
playingtime_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   (Unnamed: 0_level_0, Rk)        720 non-null    str
 1   (Unnamed: 1_level_0, Player)    720 non-null    str
 2   (Unnamed: 2_level_0, Nation)    717 non-null    str
 3   (Unnamed: 3_level_0, Pos)       720 non-null    str
 4   (Unnamed: 4_level_0, Squad)     720 non-null    str
 5   (Unnamed: 5_level_0, Age)       717 non-null    str
 6   (Unnamed: 6_level_0, Born)      717 non-null    str
 7   (Playing Time, MP)              720 non-null    str
 8   (Playing Time, Min)             578 non-null    str
 9   (Playing Time, Mn/MP)           578 non-null    str
 10  (Playing Time, Min%)            578 non-null    str
 11  (Playing Time, 90s)             578 non-null    str
 12  (Starts, Starts)                720 non-null    str
 13  (Starts, Mn/Start)              510 non-null    str
 14  (Starts, Compl)                 720 non-null    str
 15  (Subs, Subs)                    720 non-null    str
 16  (Subs, Mn/Sub)                  492 non-null    str
 17  (Subs, unSub)                   720 non-null    str
 18  (Team Success, PPM)             578 non-null    str
 19  (Team Success, onG)             578 non-null    str
 20  (Team Success, onGA)            578 non-null    str
 21  (Team Success, +/-)             578 non-null    str
 22  (Team Success, +/-90)           578 non-null    str
 23  (Team Success, On-Off)          573 non-null    str
 24  (Unnamed: 24_level_0, Matches)  720 non-null    str
dtypes: str(25)
memory usage: 200.9 KB

In [63]:
playingtime_df.columns = [lev2 if "Unnamed:" in lev1 else f"{lev1}_{lev2}" for lev1, lev2 in playingtime_df.columns]

In [64]:
playingtime_del_index = playingtime_df[playingtime_df["Playing Time_MP"] == "MP"].index
playingtime_df = playingtime_df.drop(index=playingtime_del_index)

In [65]:
for col in playingtime_df.drop(columns=str_columns):
    playingtime_df[col] = playingtime_df[col].astype("float")

playingtime_df.info()

<class 'pandas.DataFrame'>
Index: 693 entries, 0 to 719
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rk                   693 non-null    str
 1   Player               693 non-null    str
 2   Nation               690 non-null    str
 3   Pos                  693 non-null    str
 4   Squad                693 non-null    str
 5   Age                  690 non-null    str
 6   Born                 690 non-null    str
 7   Playing Time_MP      693 non-null    float64
 8   Playing Time_Min     551 non-null    float64
 9   Playing Time_Mn/MP   551 non-null    float64
 10  Playing Time_Min%    551 non-null    float64
 11  Playing Time_90s     551 non-null    float64
 12  Starts_Starts        693 non-null    float64
 13  Starts_Mn/Start      483 non-null    float64
 14  Starts_Compl         693 non-null    float64
 15  Subs_Subs            693 non-null    float64
 16  Subs_Mn/Sub          465 non-null    float64
 17  Subs_unSub           693 non-null    float64
 18  Team Success_PPM     551 non-null    float64
 19  Team Success_onG     551 non-null    float64
 20  Team Success_onGA    551 non-null    float64
 21  Team Success_+/-     551 non-null    float64
 22  Team Success_+/-90   551 non-null    float64
 23  Team Success_On-Off  546 non-null    float64
 24  Matches              693 non-null    str
dtypes: float64(17), str(8)
memory usage: 173.7 KB

In [66]:
playingtime_df[playingtime_df["Nation"].isna()]

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Min,Playing Time_Mn/MP,...,Subs_Subs,Subs_Mn/Sub,Subs_unSub,Team Success_PPM,Team Success_onG,Team Success_onGA,Team Success_+/-,Team Success_+/-90,Team Success_On-Off,Matches
430,415,Conor McManus,NaN,DF,Brentford,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
624,601,Joshua Stephenson,NaN,MF,Brentford,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
711,685,Will Wright,NaN,FW,Liverpool,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches

In [67]:
playingtime_df[playingtime_df["Age"].isna()]

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Min,Playing Time_Mn/MP,...,Subs_Subs,Subs_Mn/Sub,Subs_unSub,Team Success_PPM,Team Success_onG,Team Success_onGA,Team Success_+/-,Team Success_+/-90,Team Success_On-Off,Matches
430,415,Conor McManus,NaN,DF,Brentford,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
624,601,Joshua Stephenson,NaN,MF,Brentford,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
711,685,Will Wright,NaN,FW,Liverpool,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches

In [68]:
# playingtime_df = playingtime_df[playingtime_df["Playing Time_Min"] >= 900]

In [69]:
playingtime_df.info()

<class 'pandas.DataFrame'>
Index: 693 entries, 0 to 719
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rk                   693 non-null    str
 1   Player               693 non-null    str
 2   Nation               690 non-null    str
 3   Pos                  693 non-null    str
 4   Squad                693 non-null    str
 5   Age                  690 non-null    str
 6   Born                 690 non-null    str
 7   Playing Time_MP      693 non-null    float64
 8   Playing Time_Min     551 non-null    float64
 9   Playing Time_Mn/MP   551 non-null    float64
 10  Playing Time_Min%    551 non-null    float64
 11  Playing Time_90s     551 non-null    float64
 12  Starts_Starts        693 non-null    float64
 13  Starts_Mn/Start      483 non-null    float64
 14  Starts_Compl         693 non-null    float64
 15  Subs_Subs            693 non-null    float64
 16  Subs_Mn/Sub          465 non-null    float64
 17  Subs_unSub           693 non-null    float64
 18  Team Success_PPM     551 non-null    float64
 19  Team Success_onG     551 non-null    float64
 20  Team Success_onGA    551 non-null    float64
 21  Team Success_+/-     551 non-null    float64
 22  Team Success_+/-90   551 non-null    float64
 23  Team Success_On-Off  546 non-null    float64
 24  Matches              693 non-null    str
dtypes: float64(17), str(8)
memory usage: 173.7 KB

In [70]:
playingtime_df[playingtime_df["Team Success_On-Off"].isna()]

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Min,Playing Time_Mn/MP,...,Subs_Subs,Subs_Mn/Sub,Subs_unSub,Team Success_PPM,Team Success_onG,Team Success_onGA,Team Success_+/-,Team Success_+/-90,Team Success_On-Off,Matches
11,12,Enock Agyei,be BEL,FW,Burnley,20,2005,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
15,16,Manuel Akanji,ch SUI,"DF,MF",Manchester City,30,1995,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
17,18,Yusuf Akhamrich,eng ENG,MF,Tottenham,19,2005,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
18,19,Adedamola Alabi,eng ENG,MF,Newcastle,16,2009,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
21,22,Milan Aleksić,rs SRB,FW,Sunderland,19,2005,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,668,Jack Whittaker,eng ENG,MF,Sunderland,18,2006,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
695,670,Luca Williams Barnett,eng ENG,FW,Tottenham,16,2008,0.0,NaN,NaN,...,0.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
702,676,James Wilson,sct SCO,FW,Tottenham,18,2007,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
710,684,James Wright,eng ENG,GK,Aston Villa,20,2004,0.0,NaN,NaN,...,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
711,685,Will Wright,NaN,FW,Liverpool,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches

In [71]:
playingtime_df[playingtime_df["Subs_Mn/Sub"].isna()]

,Rk,Player,Nation,Pos,Squad,Age,Born,Playing Time_MP,Playing Time_Min,Playing Time_Mn/MP,...,Subs_Subs,Subs_Mn/Sub,Subs_unSub,Team Success_PPM,Team Success_onG,Team Success_onGA,Team Success_+/-,Team Success_+/-90,Team Success_On-Off,Matches
10,11,Nayef Aguerd,ma MAR,DF,West Ham,29,1996,2.0,180.0,90.0,...,0.0,NaN,0.0,0.00,1.0,8.0,-7.0,-3.50,-3.17,Matches
11,12,Enock Agyei,be BEL,FW,Burnley,20,2005,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
12,13,Ola Aina,ng NGA,DF,Nottingham,28,1996,18.0,1588.0,88.0,...,0.0,NaN,0.0,1.39,27.0,19.0,8.0,0.45,0.99,Matches
15,16,Manuel Akanji,ch SUI,"DF,MF",Manchester City,30,1995,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
17,18,Yusuf Akhamrich,eng ENG,MF,Tottenham,19,2005,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,668,Jack Whittaker,eng ENG,MF,Sunderland,18,2006,0.0,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
695,670,Luca Williams Barnett,eng ENG,FW,Tottenham,16,2008,0.0,NaN,NaN,...,0.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
702,676,James Wilson,sct SCO,FW,Tottenham,18,2007,0.0,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
710,684,James Wright,eng ENG,GK,Aston Villa,20,2004,0.0,NaN,NaN,...,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches
711,685,Will Wright,NaN,FW,Liverpool,NaN,NaN,0.0,NaN,NaN,...,0.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Matches

In [72]:
playingtime_df["Team Success_On-Off"] = playingtime_df["Team Success_On-Off"].fillna(0)
playingtime_df["Subs_Mn/Sub"] = playingtime_df["Subs_Mn/Sub"].fillna(0)

In [73]:
playingtime_df = playingtime_df.drop(columns="Matches")

In [74]:
playingtime_df['Team Success_+/-'].min()

np.float64(-36.0)

In [75]:
playingtime_df['Team Success_+/-'].max()

np.float64(43.0)

In [76]:
playingtime_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Mn/MP',
       'Playing Time_Min%', 'Playing Time_90s', 'Starts_Starts',
       'Starts_Mn/Start', 'Starts_Compl', 'Subs_Subs', 'Subs_Mn/Sub',
       'Subs_unSub', 'Team Success_PPM', 'Team Success_onG',
       'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90',
       'Team Success_On-Off'],
      dtype='str')

In [77]:
playingtime_col_rename_map = {
    "Playing Time_MP": "matches_played",
    "Playing Time_Min": "minutes",
    "Playing Time_Mn/MP": "minutes_per_match",
    "Playing Time_Min%": "minutes_pct",
    "Playing Time_90s": "90s_played",
    "Starts_Starts": "starts",
    "Starts_Mn/Start": "minutes_per_start",
    "Starts_Compl": "complete_matches",
    "Subs_Subs": "sub_appearances",
    "Subs_Mn/Sub": "minutes_per_sub",
    "Subs_unSub": "unused_sub",
    "Team Success_PPM": "points_per_match",
    "Team Success_onG": "goals_scored_on_pitch",
    "Team Success_onGA": "goals_allowed_on_pitch",
    "Team Success_+/-": "plus_minus",
    "Team Success_+/-90": "plus_minus_per90",
    "Team Success_On-Off": "plus_minus_net_per90"
}

playingtime_df = playingtime_df.rename(columns=playingtime_col_rename_map)

In [78]:
playingtime_df.to_parquet(ROOT / "data" /"raw" / "fbref_playing_time.parquet")

### Player Miscellaneous Stats

In [79]:
misc_stats_df.columns = misc_stats_df.columns.get_level_values(1)

In [80]:
misc_stats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       573 non-null    str
 1   Player   573 non-null    str
 2   Nation   573 non-null    str
 3   Pos      573 non-null    str
 4   Squad    573 non-null    str
 5   Age      573 non-null    str
 6   Born     573 non-null    str
 7   90s      573 non-null    str
 8   CrdY     573 non-null    str
 9   CrdR     573 non-null    str
 10  2CrdY    573 non-null    str
 11  Fls      573 non-null    str
 12  Fld      573 non-null    str
 13  Off      573 non-null    str
 14  Crs      573 non-null    str
 15  Int      573 non-null    str
 16  TklW     573 non-null    str
 17  PKwon    22 non-null     str
 18  PKcon    22 non-null     str
 19  OG       573 non-null    str
 20  Matches  573 non-null    str
dtypes: str(21)
memory usage: 130.4 KB

In [81]:
misc_stats_del_index = misc_stats_df[misc_stats_df["Rk"] == "Rk"].index
misc_stats_df = misc_stats_df.drop(index=misc_stats_del_index)

In [82]:
for col in misc_stats_df.drop(columns=str_columns):
    misc_stats_df[col] = misc_stats_df[col].astype("float")

misc_stats_df.info()

<class 'pandas.DataFrame'>
Index: 551 entries, 0 to 572
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       551 non-null    str
 1   Player   551 non-null    str
 2   Nation   551 non-null    str
 3   Pos      551 non-null    str
 4   Squad    551 non-null    str
 5   Age      551 non-null    str
 6   Born     551 non-null    str
 7   90s      551 non-null    float64
 8   CrdY     551 non-null    float64
 9   CrdR     551 non-null    float64
 10  2CrdY    551 non-null    float64
 11  Fls      551 non-null    float64
 12  Fld      551 non-null    float64
 13  Off      551 non-null    float64
 14  Crs      551 non-null    float64
 15  Int      551 non-null    float64
 16  TklW     551 non-null    float64
 17  PKwon    0 non-null      float64
 18  PKcon    0 non-null      float64
 19  OG       551 non-null    float64
 20  Matches  551 non-null    str
dtypes: float64(13), str(8)
memory usage: 120.8 KB

In [83]:
misc_stats_df = misc_stats_df.drop(columns=["Matches", "PKwon", "PKcon"])

In [84]:
misc_stats_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'CrdY',
       'CrdR', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG'],
      dtype='str')

In [85]:
misc_col_rename_map = {
    "90s": "90s_played",
    "CrdY": "yellow_cards",
    "CrdR": "red_cards",
    "2CrdY": "second_yellow_card",
    "Fls": "fouls_committed",
    "Fld": "fouls_drawn",
    "Off": "offsides",
    "Crs": "crosses",
    "Int": "interceptions",
    "TklW": "tackles_won",
    "PKwon": "penalty_kicks_won",
    "PKcon": "penalty_kicks_conceded",
    "OG": "own_goals"
}

In [86]:
misc_stats_df = misc_stats_df.rename(columns=misc_col_rename_map)

In [87]:
misc_stats_df.to_parquet(ROOT / "data" /"raw" / "fbref_misc_stats.parquet")