In [1]:
import pandas as pd

In [2]:
from pathlib import Path

ROOT = Path().resolve().parent
RAW_DATA = ROOT / "data" / "raw"

In [3]:
goalkeeping_df = pd.read_parquet(RAW_DATA / "fbref_goalkeeping.parquet")
misc_stats_df = pd.read_parquet(RAW_DATA / "fbref_misc_stats.parquet")
playingtime_df = pd.read_parquet(RAW_DATA / "fbref_playing_time.parquet")
shooting_df = pd.read_parquet(RAW_DATA / "fbref_shooting.parquet")
standard_stats_df = pd.read_parquet(RAW_DATA / "fbref_standard_stats.parquet")

In [4]:
goalkeeping_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,wins,draws,losses,clean_sheets,clean_sheet_pct,pk_attempted,pk_allowed,pk_saved,pk_missed,pk_save_pct
0,1,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,...,13.0,8.0,5.0,8.0,30.8,2.0,2.0,0.0,0.0,0.0
1,2,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,...,4.0,5.0,11.0,0.0,0.0,6.0,5.0,0.0,1.0,0.0
2,3,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,0.0
5,6,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,...,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6,7,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,...,3.0,2.0,1.0,2.0,33.3,1.0,1.0,0.0,0.0,0.0
7,8,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,...,7.0,8.0,7.0,5.0,22.7,2.0,2.0,0.0,0.0,0.0
8,9,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,...,22.0,9.0,3.0,15.0,44.1,1.0,0.0,1.0,0.0,100.0
9,10,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,...,4.0,8.0,23.0,4.0,11.4,7.0,6.0,0.0,1.0,0.0
10,11,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
11,12,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
12,13,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,...,11.0,11.0,15.0,11.0,29.7,6.0,5.0,1.0,0.0,16.7
13,14,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,...,6.0,4.0,8.0,7.0,38.9,1.0,1.0,0.0,0.0,0.0
14,15,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,...,1.0,0.0,4.0,1.0,20.0,1.0,1.0,0.0,0.0,0.0
15,16,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,...,0.0,2.0,10.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
16,17,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,...,13.0,11.0,13.0,10.0,27.0,8.0,5.0,3.0,0.0,37.5
18,19,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,...,3.0,2.0,2.0,2.0,28.6,1.0,1.0,0.0,0.0,0.0
19,20,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,...,18.0,10.0,4.0,8.0,25.0,4.0,4.0,0.0,0.0,0.0
20,21,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,...,15.0,7.0,16.0,9.0,23.7,4.0,3.0,0.0,1.0,0.0
21,22,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,...,3.0,1.0,6.0,2.0,20.0,2.0,1.0,1.0,0.0,50.0
22,23,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,...,16.0,6.0,10.0,8.0,25.0,1.0,0.0,1.0,0.0,100.0
23,24,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
24,25,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,...,4.0,6.0,6.0,3.0,18.8,4.0,4.0,0.0,0.0,0.0
26,26,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,...,13.0,18.0,7.0,11.0,28.9,6.0,6.0,0.0,0.0,0.0
27,27,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,...,13.0,10.0,15.0,11.0,28.9,4.0,3.0,1.0,0.0,25.0
28,28,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,...,10.0,5.0,12.0,7.0,25.9,2.0,2.0,0.0,0.0,0.0
29,29,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,...,4.0,2.0,5.0,1.0,9.1,3.0,3.0,0.0,0.0,0.0
30,30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,0.0
31,31,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,...,12.0,12.0,11.0,10.0,28.6,3.0,2.0,1.0,0.0,33.3
32,32,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,...,3.0,8.0,12.0,4.0,17.4,3.0,3.0,0.0,0.0,0.0
33,33,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,...,13.0,8.0,14.0,9.0,25.7,2.0,2.0,0.0,0.0,0.0
34,34,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,...,10.0,10.0,10.0,7.0,23.3,5.0,4.0,1.0,0.0,20.0
35,35,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,...,1.0,0.0,3.0,1.0,25.0,1.0,1.0,0.0,0.0,0.0
36,36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,37,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,...,14.0,11.0,13.0,10.0,26.3,6.0,5.0,1.0,0.0,16.7
38,38,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,...,7.0,9.0,15.0,7.0,22.6,2.0,2.0,0.0,0.0,0.0
39,39,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,...,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
40,40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
misc_stats_df

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,3.0,0.0,0.0,20.0,51.0,5.0,37.0,17.0,27.0,0.0
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,3.0,1.0,0.0,3.0,2.0,4.0,0.0
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,0.0,0.0,2.0,9.0,2.0,1.0,12.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,19.3,1.0,0.0,0.0,17.0,5.0,2.0,3.0,31.0,20.0,0.0
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,3.9,0.0,0.0,0.0,1.0,2.0,1.0,18.0,2.0,6.0,0.0
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,7.0,3.0,0.0,0.0,8.0,6.0,1.0,5.0,1.0,6.0,0.0
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,33.2,4.0,0.0,0.0,33.0,15.0,1.0,13.0,39.0,39.0,0.0
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,15.2,0.0,0.0,0.0,9.0,9.0,2.0,22.0,7.0,9.0,0.0

In [6]:
playingtime_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,2449.0,66.0,...,2.0,7.0,21.0,1.0,1.19,35.0,31.0,4.0,0.15,1.17
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,17.0,17.0,...,0.0,1.0,17.0,1.0,1.00,0.0,0.0,0.0,0.00,1.08
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,164.0,55.0,...,0.0,1.0,45.0,13.0,1.00,2.0,4.0,-2.0,-1.10,-1.07
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,286.0,24.0,...,1.0,10.0,14.0,2.0,1.00,4.0,8.0,-4.0,-1.26,-1.57
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,666.0,39.0,...,1.0,9.0,11.0,18.0,1.18,10.0,13.0,-3.0,-0.41,-0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,689,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,32.0,1740.0,54.0,...,9.0,14.0,20.0,5.0,1.72,28.0,33.0,-5.0,-0.26,-1.54
716,690,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,5.0,353.0,71.0,...,3.0,1.0,10.0,3.0,0.20,1.0,6.0,-5.0,-1.27,-1.33
717,691,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,24.0,626.0,26.0,...,2.0,19.0,14.0,12.0,1.79,9.0,8.0,1.0,0.14,-0.44
718,692,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,38.0,2992.0,79.0,...,22.0,4.0,32.0,0.0,2.24,57.0,25.0,32.0,0.96,-1.56
719,693,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,24.0,1369.0,57.0,...,7.0,8.0,26.0,1.0,2.17,29.0,13.0,16.0,1.05,-0.18

In [7]:
shooting_df

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,goals,shots_total,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,penalty_kicks_made,penalty_kicks_attempted
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,4.0,47.0,17.0,36.2,1.73,0.62,0.09,0.24,0.0,0.0
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,2.0,9.0,3.0,33.3,2.83,0.94,0.22,0.67,0.0,0.0
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,4.0,2.0,50.0,0.54,0.27,0.25,0.50,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,19.3,0.0,9.0,3.0,33.3,0.47,0.16,0.00,0.00,0.0,0.0
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,3.9,0.0,4.0,2.0,50.0,1.02,0.51,0.00,0.00,0.0,0.0
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,7.0,2.0,25.0,9.0,36.0,3.59,1.29,0.08,0.22,0.0,0.0
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,33.2,5.0,27.0,9.0,33.3,0.81,0.27,0.19,0.56,0.0,0.0
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,15.2,1.0,22.0,8.0,36.4,1.45,0.53,0.05,0.13,0.0,0.0

In [8]:
standard_stats_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,...,4.0,0.0,0.0,3.0,0.0,0.15,0.18,0.33,0.15,0.33
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,...,2.0,0.0,0.0,0.0,0.0,0.63,0.00,0.63,0.63,0.63
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,...,1.0,0.0,0.0,1.0,0.0,0.14,0.00,0.14,0.14,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,32.0,18.0,1740.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,5.0,4.0,353.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,24.0,5.0,626.0,...,2.0,0.0,0.0,3.0,0.0,0.29,0.14,0.43,0.29,0.43
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,38.0,34.0,2992.0,...,5.0,0.0,0.0,4.0,0.0,0.15,0.03,0.18,0.15,0.18
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,24.0,16.0,1369.0,...,1.0,0.0,0.0,0.0,0.0,0.07,0.39,0.46,0.07,0.46

### Handling Players Played for Multiple Clubs during the season

In [9]:
dfs = {
    "goalkeeping": goalkeeping_df,
    "shooting": shooting_df,
    "playingtime": playingtime_df,
    "misc_stats": misc_stats_df,
    "standard_stats": standard_stats_df
}

In [10]:
for name, df in dfs.items():
    print(f"--- {name} ---")
    print(f"Total rows: {len(df)}")
    print(f"Unique Players: {df['Player'].nunique()}")
    print()

--- goalkeeping ---
Total rows: 40
Unique Players: 40

--- shooting ---
Total rows: 551
Unique Players: 537

--- playingtime ---
Total rows: 693
Unique Players: 677

--- misc_stats ---
Total rows: 551
Unique Players: 537

--- standard_stats ---
Total rows: 551
Unique Players: 537

In [11]:
shooting_df[shooting_df["Player"].duplicated()]

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,goals,shots_total,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,penalty_kicks_made,penalty_kicks_attempted
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,6.3,0.0,8.0,3.0,37.5,1.26,0.47,0.00,0.00,0.0,0.0
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,0.4,0.0,2.0,0.0,0.0,4.62,0.00,0.00,0.00,0.0,0.0
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,1.2,0.0,5.0,0.0,0.0,4.02,0.00,0.00,0.00,0.0,0.0
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,20.1,7.0,57.0,18.0,31.6,2.83,0.89,0.12,0.39,0.0,0.0
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,2.4,0.0,7.0,3.0,42.9,2.89,1.24,0.00,0.00,0.0,0.0
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,1.0,17.0,5.0,29.4,1.13,0.33,0.06,0.20,0.0,0.0
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,6.5,0.0,8.0,5.0,62.5,1.22,0.77,0.00,0.00,0.0,0.0
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,2.9,0.0,12.0,2.0,16.7,4.20,0.70,0.00,0.00,0.0,0.0
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,12.4,0.0,17.0,3.0,17.6,1.38,0.24,0.00,0.00,0.0,0.0
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,3.5,0.0,5.0,1.0,20.0,1.43,0.29,0.00,0.00,0.0,0.0
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,15.5,7.0,34.0,14.0,41.2,2.19,0.90,0.21,0.50,0.0,0.0
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,10.0,3.0,23.0,7.0,30.4,2.29,0.70,0.13,0.43,0.0,0.0
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,1.3,0.0,2.0,0.0,0.0,1.49,0.00,0.00,0.00,0.0,0.0
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,7.6,0.0,3.0,2.0,66.7,0.39,0.26,0.00,0.00,0.0,0.0

In [12]:
shooting_df[shooting_df["Player"].duplicated(keep=False)]

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,goals,shots_total,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,penalty_kicks_made,penalty_kicks_attempted
58,57,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,5.2,0.0,4.0,0.0,0.0,0.77,0.00,0.00,0.00,0.0,0.0
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,6.3,0.0,8.0,3.0,37.5,1.26,0.47,0.00,0.00,0.0,0.0
75,74,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,0.5,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,0.4,0.0,2.0,0.0,0.0,4.62,0.00,0.00,0.00,0.0,0.0
154,150,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,1.2,0.0,5.0,0.0,0.0,4.02,0.00,0.00,0.00,0.0,0.0
162,157,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,0.9,0.0,6.0,2.0,33.3,6.51,2.17,0.00,0.00,0.0,0.0
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,20.1,7.0,57.0,18.0,31.6,2.83,0.89,0.12,0.39,0.0,0.0
185,179,Tyrique George,eng ENG,FW,Chelsea,19,2006,1.6,0.0,3.0,2.0,66.7,1.86,1.24,0.00,0.00,0.0,0.0
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,2.4,0.0,7.0,3.0,42.9,2.89,1.24,0.00,0.00,0.0,0.0
205,199,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,2.0,15.0,4.0,26.7,0.75,0.20,0.13,0.50,0.0,0.0
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,1.0,17.0,5.0,29.4,1.13,0.33,0.06,0.20,0.0,0.0
208,201,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,3.7,1.0,3.0,1.0,33.3,0.82,0.27,0.33,1.00,0.0,0.0
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,6.5,0.0,8.0,5.0,62.5,1.22,0.77,0.00,0.00,0.0,0.0
213,206,Marc Guiu,es ESP,FW,Sunderland,19,2006,0.2,0.0,1.0,0.0,0.0,6.00,0.00,0.00,0.00,0.0,0.0
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,2.9,0.0,12.0,2.0,16.7,4.20,0.70,0.00,0.00,0.0,0.0
264,255,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,6.8,2.0,6.0,2.0,33.3,0.89,0.30,0.33,1.00,0.0,0.0
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,12.4,0.0,17.0,3.0,17.6,1.38,0.24,0.00,0.00,0.0,0.0
321,310,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,6.7,1.0,6.0,4.0,66.7,0.89,0.60,0.17,0.25,0.0,0.0
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,3.5,0.0,5.0,1.0,20.0,1.43,0.29,0.00,0.00,0.0,0.0
474,457,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,10.0,49.0,27.0,55.1,2.45,1.35,0.18,0.33,1.0,2.0
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,15.5,7.0,34.0,14.0,41.2,2.19,0.90,0.21,0.50,0.0,0.0
495,477,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,15.6,1.0,21.0,7.0,33.3,1.35,0.45,0.00,0.00,1.0,2.0
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,10.0,3.0,23.0,7.0,30.4,2.29,0.70,0.13,0.43,0.0,0.0
518,500,Adama Traoré,es ESP,MF,Fulham,29,1996,3.0,0.0,5.0,1.0,20.0,1.64,0.33,0.00,0.00,0.0,0.0
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,1.3,0.0,2.0,0.0,0.0,1.49,0.00,0.00,0.00,0.0,0.0
542,523,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,4.6,0.0,2.0,0.0,0.0,0.44,0.00,0.00,0.00,0.0,0.0
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,7.6,0.0,3.0,2.0,66.7,0.39,0.26,0.00,0.00,0.0,0.0

In [13]:
misc_stats_df[misc_stats_df["Player"].duplicated(keep=False)]

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
58,57,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,5.2,1.0,0.0,0.0,5.0,9.0,0.0,5.0,3.0,5.0,0.0
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,6.3,0.0,0.0,0.0,4.0,8.0,0.0,9.0,6.0,7.0,0.0
75,74,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,0.4,1.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0
154,150,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,1.2,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0
162,157,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,0.9,0.0,0.0,0.0,2.0,1.0,0.0,4.0,0.0,1.0,0.0
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,20.1,1.0,0.0,0.0,14.0,38.0,1.0,8.0,11.0,13.0,0.0
185,179,Tyrique George,eng ENG,FW,Chelsea,19,2006,1.6,2.0,0.0,0.0,6.0,1.0,2.0,1.0,0.0,2.0,0.0
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,2.4,0.0,0.0,0.0,3.0,1.0,2.0,10.0,2.0,3.0,0.0
205,199,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,4.0,0.0,0.0,14.0,18.0,0.0,10.0,24.0,19.0,0.0
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,2.0,0.0,0.0,11.0,20.0,0.0,7.0,25.0,12.0,0.0
208,201,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,3.7,0.0,0.0,0.0,4.0,8.0,1.0,1.0,2.0,2.0,0.0
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,6.5,0.0,0.0,0.0,11.0,12.0,0.0,10.0,3.0,9.0,0.0
213,206,Marc Guiu,es ESP,FW,Sunderland,19,2006,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,2.9,1.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,0.0,0.0
264,255,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,6.8,2.0,0.0,0.0,2.0,4.0,8.0,23.0,2.0,9.0,0.0
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,12.4,4.0,0.0,0.0,18.0,11.0,6.0,45.0,2.0,7.0,0.0
321,310,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,6.7,1.0,0.0,0.0,9.0,10.0,0.0,28.0,7.0,11.0,0.0
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,3.5,2.0,0.0,0.0,4.0,5.0,0.0,15.0,7.0,3.0,0.0
474,457,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,6.0,0.0,0.0,37.0,14.0,12.0,28.0,6.0,20.0,0.0
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,15.5,1.0,0.0,0.0,17.0,7.0,7.0,21.0,6.0,11.0,0.0
495,477,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,15.6,2.0,0.0,0.0,30.0,11.0,9.0,3.0,3.0,2.0,0.0
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,10.0,2.0,0.0,0.0,21.0,10.0,1.0,0.0,1.0,0.0,0.0
518,500,Adama Traoré,es ESP,MF,Fulham,29,1996,3.0,0.0,0.0,0.0,6.0,8.0,3.0,15.0,0.0,1.0,0.0
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,1.3,1.0,0.0,0.0,1.0,0.0,2.0,12.0,0.0,1.0,0.0
542,523,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,4.6,0.0,0.0,0.0,4.0,2.0,0.0,22.0,6.0,2.0,0.0
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,7.6,1.0,0.0,0.0,4.0,11.0,0.0,52.0,15.0,4.0,0.0

In [14]:
playingtime_df[playingtime_df["Player"].duplicated(keep=False)]

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
76,75,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,9.0,468.0,52.0,...,2.0,4.0,20.0,4.0,1.67,10.0,5.0,5.0,0.96,-0.17
78,76,Oscar Bobb,no NOR,MF,Fulham,22,2003,14.0,571.0,41.0,...,0.0,8.0,23.0,0.0,1.29,7.0,7.0,0.0,0.00,0.13
98,96,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,1.0,45.0,45.0,...,0.0,0.0,0.0,4.0,1.00,0.0,1.0,-1.0,-2.00,-2.19
99,97,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,3.0,39.0,13.0,...,0.0,3.0,13.0,5.0,0.33,0.0,3.0,-3.0,-6.92,-6.82
188,182,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,1.0,1.0,1.0,...,0.0,1.0,1.0,2.0,3.00,1.0,0.0,1.0,90.00,89.76
189,183,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,4.0,112.0,28.0,...,0.0,3.0,22.0,4.0,1.25,2.0,2.0,0.0,0.00,-0.19
197,191,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,1.0,83.0,83.0,...,0.0,0.0,0.0,0.0,1.00,0.0,0.0,0.0,0.00,0.27
198,192,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,32.0,1812.0,57.0,...,5.0,11.0,24.0,4.0,2.09,37.0,14.0,23.0,1.14,-0.03
224,217,Tyrique George,eng ENG,FW,Chelsea,19,2006,4.0,145.0,36.0,...,0.0,4.0,36.0,4.0,1.00,5.0,2.0,3.0,1.86,1.78
225,218,Tyrique George,eng ENG,MF,Everton,19,2006,11.0,218.0,20.0,...,0.0,10.0,16.0,2.0,0.73,5.0,7.0,-2.0,-0.83,-0.80
251,243,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,1800.0,90.0,...,20.0,0.0,0.0,0.0,1.35,22.0,23.0,-1.0,-0.05,0.45
252,244,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,1350.0,90.0,...,15.0,0.0,0.0,0.0,2.33,31.0,12.0,19.0,1.27,0.27
253,245,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,8.0,330.0,41.0,...,1.0,5.0,23.0,0.0,1.38,8.0,5.0,3.0,0.82,1.20
254,246,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,13.0,588.0,45.0,...,0.0,7.0,27.0,5.0,1.77,9.0,10.0,-1.0,-0.15,-0.41
258,250,Marc Guiu,es ESP,FW,Sunderland,19,2006,2.0,15.0,8.0,...,0.0,2.0,8.0,1.0,1.50,1.0,1.0,0.0,0.00,0.16
260,251,Marc Guiu,es ESP,FW,Chelsea,19,2006,8.0,257.0,32.0,...,0.0,7.0,26.0,17.0,1.63,6.0,2.0,4.0,1.40,1.34
296,286,Igor,br BRA,DF,Brighton,27,1998,0.0,NaN,NaN,...,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.00
297,287,Igor,br BRA,DF,West Ham,27,1998,4.0,105.0,26.0,...,1.0,3.0,5.0,9.0,2.00,4.0,3.0,1.0,0.86,1.40
318,307,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,16.0,610.0,38.0,...,1.0,10.0,15.0,2.0,1.38,13.0,5.0,8.0,1.18,1.72
319,308,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,18.0,1112.0,62.0,...,4.0,5.0,24.0,1.0,1.00,7.0,19.0,-12.0,-0.97,-1.05
390,376,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,13.0,604.0,46.0,...,1.0,6.0,13.0,2.0,1.23,5.0,8.0,-3.0,-0.45,-0.77
391,377,Douglas Luiz,br BRA,MF,Nottingham,27,1998,8.0,315.0,39.0,...,0.0,3.0,19.0,6.0,0.63,1.0,7.0,-6.0,-1.71,-1.80
503,485,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,270.0,90.0,...,3.0,0.0,0.0,8.0,0.33,1.0,4.0,-3.0,-1.00,-1.00
504,486,Stefan Ortega,de GER,GK,Manchester City,32,1992,0.0,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.00
591,570,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,1798.0,90.0,...,18.0,0.0,0.0,0.0,1.25,31.0,38.0,-7.0,-0.35,-0.96
592,571,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,17.0,1398.0,82.0,...,9.0,0.0,0.0,0.0,2.06,28.0,14.0,14.0,0.90,-0.35
627,604,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,22.0,1404.0,64.0,...,7.0,8.0,31.0,0.0,0.36,6.0,26.0,-20.0,-1.28,-0.34
628,605,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,14.0,903.0,65.0,...,3.0,2.0,26.0,0.0,1.14,12.0,15.0,-3.0,-0.30,-0.05
655,631,Adama Traoré,es ESP,MF,Fulham,29,1996,15.0,274.0,18.0,...,0.0,14.0,14.0,6.0,1.20,4.0,7.0,-3.0,-0.99,-0.96
656,632,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,9.0,121.0,13.0,...,0.0,9.0,13.0,3.0,1.22,1.0,5.0,-4.0,-2.98,-2.57
683,658,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,5.0,413.0,83.0,...,2.0,0.0,0.0,1.0,0.60,2.0,11.0,-9.0,-1.96,-1.66
684,659,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,13.0,684.0,53.0,...,4.0,6.0,18.0,1.0,0.54,6.0,16.0,-10.0,-1.32,-0.43

In [15]:
standard_stats_df[standard_stats_df["Player"].duplicated(keep=False)]

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
58,57,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,9.0,5.0,468.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.19,0.19,0.00,0.19
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,14.0,6.0,571.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
75,74,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,1.0,1.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,3.0,0.0,39.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
154,150,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,4.0,1.0,112.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
162,157,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,1.0,1.0,83.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,32.0,21.0,1812.0,...,7.0,0.0,0.0,1.0,0.0,0.35,0.10,0.45,0.35,0.45
185,179,Tyrique George,eng ENG,FW,Chelsea,19,2006,4.0,0.0,145.0,...,0.0,0.0,0.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,11.0,1.0,218.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
205,199,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,20.0,1800.0,...,2.0,0.0,0.0,4.0,0.0,0.10,0.10,0.20,0.10,0.20
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,15.0,1350.0,...,1.0,0.0,0.0,2.0,0.0,0.07,0.07,0.13,0.07,0.13
208,201,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,8.0,3.0,330.0,...,1.0,0.0,0.0,0.0,0.0,0.27,0.27,0.55,0.27,0.55
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,13.0,6.0,588.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.15,0.15,0.00,0.15
213,206,Marc Guiu,es ESP,FW,Sunderland,19,2006,2.0,0.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,8.0,1.0,257.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.35,0.35,0.00,0.35
264,255,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,16.0,6.0,610.0,...,2.0,0.0,0.0,2.0,0.0,0.30,0.00,0.30,0.30,0.30
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,18.0,13.0,1112.0,...,0.0,0.0,0.0,4.0,0.0,0.00,0.08,0.08,0.00,0.08
321,310,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,13.0,7.0,604.0,...,1.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,8.0,5.0,315.0,...,0.0,0.0,0.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00
474,457,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,20.0,1798.0,...,9.0,1.0,2.0,6.0,0.0,0.50,0.15,0.65,0.45,0.60
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,17.0,17.0,1397.0,...,7.0,0.0,0.0,1.0,0.0,0.45,0.06,0.52,0.45,0.52
495,477,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,22.0,14.0,1404.0,...,0.0,1.0,2.0,2.0,0.0,0.06,0.06,0.13,0.00,0.06
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,14.0,12.0,903.0,...,3.0,0.0,0.0,2.0,0.0,0.30,0.00,0.30,0.30,0.30
518,500,Adama Traoré,es ESP,MF,Fulham,29,1996,15.0,1.0,274.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,9.0,0.0,121.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
542,523,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,5.0,5.0,413.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,13.0,7.0,684.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.13,0.13,0.00,0.13

In [16]:
# shooting 28
# Misc Stats - 28
# Playing time - 32
# Standard Stats - 28

Players that played for Multiple clubs in the Season

In [17]:
shooting_dup_df = shooting_df[shooting_df["Player"].duplicated(keep=False)]
misc_stats_dup_df = misc_stats_df[misc_stats_df["Player"].duplicated(keep=False)]
playingtime_dup_df = playingtime_df[playingtime_df["Player"].duplicated(keep=False)]
standard_stats_dup_df = standard_stats_df[standard_stats_df["Player"].duplicated(keep=False)]

Dataframe without duplicate clubs

In [18]:
shooting_without_dup = shooting_df[~shooting_df["Player"].duplicated(keep=False)]
misc_stats_without_dup = misc_stats_df[~misc_stats_df["Player"].duplicated(keep=False)]
playingtime_without_dup = playingtime_df[~playingtime_df["Player"].duplicated(keep=False)]
standard_stats_without_dup = standard_stats_df[~standard_stats_df["Player"].duplicated(keep=False)]

In [19]:
shooting_without_dup

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,goals,shots_total,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,penalty_kicks_made,penalty_kicks_attempted
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,4.0,47.0,17.0,36.2,1.73,0.62,0.09,0.24,0.0,0.0
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,2.0,9.0,3.0,33.3,2.83,0.94,0.22,0.67,0.0,0.0
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,4.0,2.0,50.0,0.54,0.27,0.25,0.50,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,19.3,0.0,9.0,3.0,33.3,0.47,0.16,0.00,0.00,0.0,0.0
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,3.9,0.0,4.0,2.0,50.0,1.02,0.51,0.00,0.00,0.0,0.0
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,7.0,2.0,25.0,9.0,36.0,3.59,1.29,0.08,0.22,0.0,0.0
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,33.2,5.0,27.0,9.0,33.3,0.81,0.27,0.19,0.56,0.0,0.0
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,15.2,1.0,22.0,8.0,36.4,1.45,0.53,0.05,0.13,0.0,0.0

In [20]:
shooting_dup_df["Player"].unique().tolist()

['Oscar Bobb',
 'Facundo Buonanotte',
 'Harvey Elliott',
 'Eberechi Eze',
 'Tyrique George',
 'Marc Guéhi',
 'Evann Guessand',
 'Marc Guiu',
 'Brennan Johnson',
 'Douglas Luiz',
 'Antoine Semenyo',
 'Jørgen Strand Larsen',
 'Adama Traoré',
 'James Ward-Prowse']

In [21]:
shooting_dup_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s_played',
       'goals', 'shots_total', 'shots_on_target', 'shots_on_target_pct',
       'shots_per90', 'shots_on_target_per90', 'goals_per_shot',
       'goals_per_shot_on_target', 'penalty_kicks_made',
       'penalty_kicks_attempted'],
      dtype='str')

In [22]:
counting_stats = ["Player", "90s_played", "goals", "shots_total", "shots_on_target", "penalty_kicks_made", "penalty_kicks_attempted"]

In [23]:
shooting_agg_df = shooting_dup_df[counting_stats].groupby("Player").sum()
shooting_agg_df

,90s_played,goals,shots_total,shots_on_target,penalty_kicks_made,penalty_kicks_attempted
Player,,,,,,
Adama Traoré,4.3,0.0,7.0,1.0,0.0,0.0
Antoine Semenyo,35.5,17.0,83.0,41.0,1.0,2.0
Brennan Johnson,19.2,2.0,23.0,5.0,0.0,0.0
Douglas Luiz,10.2,1.0,11.0,5.0,0.0,0.0
Eberechi Eze,21.0,7.0,63.0,20.0,0.0,0.0
Evann Guessand,10.2,1.0,11.0,6.0,0.0,0.0
Facundo Buonanotte,0.9,0.0,2.0,0.0,0.0,0.0
Harvey Elliott,1.2,0.0,5.0,0.0,0.0,0.0
James Ward-Prowse,12.2,0.0,5.0,2.0,0.0,0.0
Jørgen Strand Larsen,25.6,4.0,44.0,14.0,1.0,2.0
Marc Guiu,3.1,0.0,13.0,2.0,0.0,0.0
Marc Guéhi,35.0,3.0,32.0,9.0,0.0,0.0
Oscar Bobb,11.5,0.0,12.0,3.0,0.0,0.0
Tyrique George,4.0,0.0,10.0,5.0,0.0,0.0

In [24]:
shooting_agg_df["Squad"] = shooting_dup_df.groupby("Player")["Squad"].agg(lambda x: " / ".join(x))

In [25]:
shooting_agg_df

,90s_played,goals,shots_total,shots_on_target,penalty_kicks_made,penalty_kicks_attempted,Squad
Player,,,,,,,
Adama Traoré,4.3,0.0,7.0,1.0,0.0,0.0,Fulham / West Ham
Antoine Semenyo,35.5,17.0,83.0,41.0,1.0,2.0,Bournemouth / Manchester City
Brennan Johnson,19.2,2.0,23.0,5.0,0.0,0.0,Tottenham / Crystal Palace
Douglas Luiz,10.2,1.0,11.0,5.0,0.0,0.0,Aston Villa / Nottingham
Eberechi Eze,21.0,7.0,63.0,20.0,0.0,0.0,Crystal Palace / Arsenal
Evann Guessand,10.2,1.0,11.0,6.0,0.0,0.0,Crystal Palace / Aston Villa
Facundo Buonanotte,0.9,0.0,2.0,0.0,0.0,0.0,Chelsea / Leeds United
Harvey Elliott,1.2,0.0,5.0,0.0,0.0,0.0,Liverpool / Aston Villa
James Ward-Prowse,12.2,0.0,5.0,2.0,0.0,0.0,West Ham / Burnley
Jørgen Strand Larsen,25.6,4.0,44.0,14.0,1.0,2.0,Wolves / Crystal Palace
Marc Guiu,3.1,0.0,13.0,2.0,0.0,0.0,Sunderland / Chelsea
Marc Guéhi,35.0,3.0,32.0,9.0,0.0,0.0,Crystal Palace / Manchester City
Oscar Bobb,11.5,0.0,12.0,3.0,0.0,0.0,Manchester City / Fulham
Tyrique George,4.0,0.0,10.0,5.0,0.0,0.0,Chelsea / Everton

In [26]:
shooting_agg_df["Pos"] = shooting_dup_df.groupby("Player")["Pos"].agg(lambda x: str(set(",".join(x).split(","))).replace("{", "").replace("}", "").replace("'", ""))

In [27]:
shooting_agg_df

,90s_played,goals,shots_total,shots_on_target,penalty_kicks_made,penalty_kicks_attempted,Squad,Pos
Player,,,,,,,,
Adama Traoré,4.3,0.0,7.0,1.0,0.0,0.0,Fulham / West Ham,"MF, FW"
Antoine Semenyo,35.5,17.0,83.0,41.0,1.0,2.0,Bournemouth / Manchester City,"MF, FW"
Brennan Johnson,19.2,2.0,23.0,5.0,0.0,0.0,Tottenham / Crystal Palace,"MF, FW"
Douglas Luiz,10.2,1.0,11.0,5.0,0.0,0.0,Aston Villa / Nottingham,MF
Eberechi Eze,21.0,7.0,63.0,20.0,0.0,0.0,Crystal Palace / Arsenal,"MF, FW"
Evann Guessand,10.2,1.0,11.0,6.0,0.0,0.0,Crystal Palace / Aston Villa,MF
Facundo Buonanotte,0.9,0.0,2.0,0.0,0.0,0.0,Chelsea / Leeds United,MF
Harvey Elliott,1.2,0.0,5.0,0.0,0.0,0.0,Liverpool / Aston Villa,"MF, FW"
James Ward-Prowse,12.2,0.0,5.0,2.0,0.0,0.0,West Ham / Burnley,MF
Jørgen Strand Larsen,25.6,4.0,44.0,14.0,1.0,2.0,Wolves / Crystal Palace,FW
Marc Guiu,3.1,0.0,13.0,2.0,0.0,0.0,Sunderland / Chelsea,FW
Marc Guéhi,35.0,3.0,32.0,9.0,0.0,0.0,Crystal Palace / Manchester City,DF
Oscar Bobb,11.5,0.0,12.0,3.0,0.0,0.0,Manchester City / Fulham,"MF, FW"
Tyrique George,4.0,0.0,10.0,5.0,0.0,0.0,Chelsea / Everton,"MF, FW"

In [28]:
identifier_col = ["Nation", "Age", "Born"]
identifier_df = shooting_dup_df.groupby("Player")[identifier_col].first()

In [29]:
identifier_df

                       Nation Age  Born
Player
Adama Traoré           es ESP  29  1996
Antoine Semenyo        gh GHA  25  2000
Brennan Johnson       wls WAL  24  2001
Douglas Luiz           br BRA  27  1998
Eberechi Eze          eng ENG  27  1998
Evann Guessand         ci CIV  24  2001
Facundo Buonanotte     ar ARG  20  2004
Harvey Elliott        eng ENG  22  2003
James Ward-Prowse     eng ENG  30  1994
Jørgen Strand Larsen   no NOR  25  2000
Marc Guiu              es ESP  19  2006
Marc Guéhi            eng ENG  25  2000
Oscar Bobb             no NOR  22  2003
Tyrique George        eng ENG  19  2006

In [30]:
shooting_agg_df = pd.merge(identifier_df, shooting_agg_df, on="Player")

In [31]:
shooting_agg_df.columns

Index(['Nation', 'Age', 'Born', '90s_played', 'goals', 'shots_total',
       'shots_on_target', 'penalty_kicks_made', 'penalty_kicks_attempted',
       'Squad', 'Pos'],
      dtype='str')

In [32]:
set(shooting_df[shooting_df["Player"].duplicated(keep=False)].columns) - set(shooting_agg_df.columns)

{'Player',
 'Rk',
 'goals_per_shot',
 'goals_per_shot_on_target',
 'shots_on_target_pct',
 'shots_on_target_per90',
 'shots_per90'}

In [33]:
shooting_agg_df["shots_on_target_pct"] = (shooting_agg_df["shots_on_target"] / shooting_agg_df["shots_total"]).round(2)

In [34]:
shooting_agg_df["goals_per_shot"] = (shooting_agg_df["goals"] / shooting_agg_df["shots_total"]).round(2)

In [35]:
shooting_agg_df["goals_per_shot_on_target"] = (shooting_agg_df["goals"] / shooting_agg_df["shots_on_target"]).round(2).fillna(0)

In [36]:
shooting_agg_df["shots_per90"] = (shooting_agg_df["shots_total"] / shooting_agg_df["90s_played"]).round(2)

In [37]:
shooting_agg_df["shots_on_target_per90"] = (shooting_agg_df["shots_on_target"] / shooting_agg_df["90s_played"]).round(2)

In [38]:
shooting_agg_df

,Nation,Age,Born,90s_played,goals,shots_total,shots_on_target,penalty_kicks_made,penalty_kicks_attempted,Squad,Pos,shots_on_target_pct,goals_per_shot,goals_per_shot_on_target,shots_per90,shots_on_target_per90
Player,,,,,,,,,,,,,,,,
Adama Traoré,es ESP,29,1996,4.3,0.0,7.0,1.0,0.0,0.0,Fulham / West Ham,"MF, FW",0.14,0.00,0.00,1.63,0.23
Antoine Semenyo,gh GHA,25,2000,35.5,17.0,83.0,41.0,1.0,2.0,Bournemouth / Manchester City,"MF, FW",0.49,0.20,0.41,2.34,1.15
Brennan Johnson,wls WAL,24,2001,19.2,2.0,23.0,5.0,0.0,0.0,Tottenham / Crystal Palace,"MF, FW",0.22,0.09,0.40,1.20,0.26
Douglas Luiz,br BRA,27,1998,10.2,1.0,11.0,5.0,0.0,0.0,Aston Villa / Nottingham,MF,0.45,0.09,0.20,1.08,0.49
Eberechi Eze,eng ENG,27,1998,21.0,7.0,63.0,20.0,0.0,0.0,Crystal Palace / Arsenal,"MF, FW",0.32,0.11,0.35,3.00,0.95
Evann Guessand,ci CIV,24,2001,10.2,1.0,11.0,6.0,0.0,0.0,Crystal Palace / Aston Villa,MF,0.55,0.09,0.17,1.08,0.59
Facundo Buonanotte,ar ARG,20,2004,0.9,0.0,2.0,0.0,0.0,0.0,Chelsea / Leeds United,MF,0.00,0.00,0.00,2.22,0.00
Harvey Elliott,eng ENG,22,2003,1.2,0.0,5.0,0.0,0.0,0.0,Liverpool / Aston Villa,"MF, FW",0.00,0.00,0.00,4.17,0.00
James Ward-Prowse,eng ENG,30,1994,12.2,0.0,5.0,2.0,0.0,0.0,West Ham / Burnley,MF,0.40,0.00,0.00,0.41,0.16
Jørgen Strand Larsen,no NOR,25,2000,25.6,4.0,44.0,14.0,1.0,2.0,Wolves / Crystal Palace,FW,0.32,0.09,0.29,1.72,0.55
Marc Guiu,es ESP,19,2006,3.1,0.0,13.0,2.0,0.0,0.0,Sunderland / Chelsea,FW,0.15,0.00,0.00,4.19,0.65
Marc Guéhi,eng ENG,25,2000,35.0,3.0,32.0,9.0,0.0,0.0,Crystal Palace / Manchester City,DF,0.28,0.09,0.33,0.91,0.26
Oscar Bobb,no NOR,22,2003,11.5,0.0,12.0,3.0,0.0,0.0,Manchester City / Fulham,"MF, FW",0.25,0.00,0.00,1.04,0.26
Tyrique George,eng ENG,19,2006,4.0,0.0,10.0,5.0,0.0,0.0,Chelsea / Everton,"MF, FW",0.50,0.00,0.00,2.50,1.25

In [39]:
set(shooting_without_dup) - set(shooting_agg_df)

{'Player', 'Rk'}

In [40]:
shooting_agg_df = shooting_agg_df.reset_index()

In [41]:
shooting_clean_df = pd.concat([shooting_without_dup, shooting_agg_df], ignore_index=True)

In [42]:
shooting_clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rk                        523 non-null    str
 1   Player                    537 non-null    str
 2   Nation                    537 non-null    str
 3   Pos                       537 non-null    str
 4   Squad                     537 non-null    str
 5   Age                       537 non-null    str
 6   Born                      537 non-null    str
 7   90s_played                537 non-null    float64
 8   goals                     537 non-null    float64
 9   shots_total               537 non-null    float64
 10  shots_on_target           537 non-null    float64
 11  shots_on_target_pct       537 non-null    float64
 12  shots_per90               537 non-null    float64
 13  shots_on_target_per90     537 non-null    float64
 14  goals_per_shot            537 non-null    float64
 15  goals_per_shot_on_target  537 non-null    float64
 16  penalty_kicks_made        537 non-null    float64
 17  penalty_kicks_attempted   537 non-null    float64
dtypes: float64(11), str(7)
memory usage: 97.5 KB

In [43]:
shooting_clean_df = shooting_clean_df.drop(columns="Rk")

In [44]:
misc_stats_dup_df

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
58,57,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,5.2,1.0,0.0,0.0,5.0,9.0,0.0,5.0,3.0,5.0,0.0
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,6.3,0.0,0.0,0.0,4.0,8.0,0.0,9.0,6.0,7.0,0.0
75,74,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,0.4,1.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0
154,150,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,1.2,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0
162,157,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,0.9,0.0,0.0,0.0,2.0,1.0,0.0,4.0,0.0,1.0,0.0
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,20.1,1.0,0.0,0.0,14.0,38.0,1.0,8.0,11.0,13.0,0.0
185,179,Tyrique George,eng ENG,FW,Chelsea,19,2006,1.6,2.0,0.0,0.0,6.0,1.0,2.0,1.0,0.0,2.0,0.0
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,2.4,0.0,0.0,0.0,3.0,1.0,2.0,10.0,2.0,3.0,0.0
205,199,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,4.0,0.0,0.0,14.0,18.0,0.0,10.0,24.0,19.0,0.0
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,2.0,0.0,0.0,11.0,20.0,0.0,7.0,25.0,12.0,0.0
208,201,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,3.7,0.0,0.0,0.0,4.0,8.0,1.0,1.0,2.0,2.0,0.0
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,6.5,0.0,0.0,0.0,11.0,12.0,0.0,10.0,3.0,9.0,0.0
213,206,Marc Guiu,es ESP,FW,Sunderland,19,2006,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,2.9,1.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,0.0,0.0
264,255,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,6.8,2.0,0.0,0.0,2.0,4.0,8.0,23.0,2.0,9.0,0.0
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,12.4,4.0,0.0,0.0,18.0,11.0,6.0,45.0,2.0,7.0,0.0
321,310,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,6.7,1.0,0.0,0.0,9.0,10.0,0.0,28.0,7.0,11.0,0.0
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,3.5,2.0,0.0,0.0,4.0,5.0,0.0,15.0,7.0,3.0,0.0
474,457,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,6.0,0.0,0.0,37.0,14.0,12.0,28.0,6.0,20.0,0.0
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,15.5,1.0,0.0,0.0,17.0,7.0,7.0,21.0,6.0,11.0,0.0
495,477,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,15.6,2.0,0.0,0.0,30.0,11.0,9.0,3.0,3.0,2.0,0.0
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,10.0,2.0,0.0,0.0,21.0,10.0,1.0,0.0,1.0,0.0,0.0
518,500,Adama Traoré,es ESP,MF,Fulham,29,1996,3.0,0.0,0.0,0.0,6.0,8.0,3.0,15.0,0.0,1.0,0.0
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,1.3,1.0,0.0,0.0,1.0,0.0,2.0,12.0,0.0,1.0,0.0
542,523,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,4.6,0.0,0.0,0.0,4.0,2.0,0.0,22.0,6.0,2.0,0.0
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,7.6,1.0,0.0,0.0,4.0,11.0,0.0,52.0,15.0,4.0,0.0

In [45]:
misc_stats_without_dup

,Rk,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,3.0,0.0,0.0,20.0,51.0,5.0,37.0,17.0,27.0,0.0
1,2,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,3,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,3.0,1.0,0.0,3.0,2.0,4.0,0.0
3,4,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
4,5,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,0.0,0.0,2.0,9.0,2.0,1.0,12.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,547,Leny Yoro,fr FRA,DF,Manchester Utd,19,2005,19.3,1.0,0.0,0.0,17.0,5.0,2.0,3.0,31.0,20.0,0.0
568,548,Oleksandr Zinchenko,ua UKR,DF,Nottingham,28,1996,3.9,0.0,0.0,0.0,1.0,2.0,1.0,18.0,2.0,6.0,0.0
569,549,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,24,2001,7.0,3.0,0.0,0.0,8.0,6.0,1.0,5.0,1.0,6.0,0.0
570,550,Martín Zubimendi,es ESP,MF,Arsenal,26,1999,33.2,4.0,0.0,0.0,33.0,15.0,1.0,13.0,39.0,39.0,0.0
572,551,Martin Ødegaard,no NOR,MF,Arsenal,26,1998,15.2,0.0,0.0,0.0,9.0,9.0,2.0,22.0,7.0,9.0,0.0

In [46]:
misc_stats_agg = misc_stats_dup_df.groupby("Player")["Squad"].agg(lambda x: " / ".join(x))

In [47]:
misc_stats_agg

Player
Adama Traoré                           Fulham / West Ham
Antoine Semenyo            Bournemouth / Manchester City
Brennan Johnson               Tottenham / Crystal Palace
Douglas Luiz                    Aston Villa / Nottingham
Eberechi Eze                    Crystal Palace / Arsenal
Evann Guessand              Crystal Palace / Aston Villa
Facundo Buonanotte                Chelsea / Leeds United
Harvey Elliott                   Liverpool / Aston Villa
James Ward-Prowse                     West Ham / Burnley
Jørgen Strand Larsen             Wolves / Crystal Palace
Marc Guiu                           Sunderland / Chelsea
Marc Guéhi              Crystal Palace / Manchester City
Oscar Bobb                      Manchester City / Fulham
Tyrique George                         Chelsea / Everton
Name: Squad, dtype: str

In [48]:
pos_df = misc_stats_dup_df.groupby("Player")["Pos"].agg(lambda x: str(set(",".join(x).split(","))).replace("{", "").replace("}", "").replace("'", ""))

In [49]:
misc_stats_agg = pd.merge(misc_stats_agg, pos_df, on="Player")

In [50]:
identifier_col = ["Nation", "Age", "Born"]
identifier_df = misc_stats_dup_df.groupby("Player")[identifier_col].first()

In [51]:
misc_stats_agg = pd.merge(misc_stats_agg, identifier_df, on="Player")

In [52]:
misc_stats_agg

,Squad,Pos,Nation,Age,Born
Player,,,,,
Adama Traoré,Fulham / West Ham,"MF, FW",es ESP,29,1996
Antoine Semenyo,Bournemouth / Manchester City,"MF, FW",gh GHA,25,2000
Brennan Johnson,Tottenham / Crystal Palace,"MF, FW",wls WAL,24,2001
Douglas Luiz,Aston Villa / Nottingham,MF,br BRA,27,1998
Eberechi Eze,Crystal Palace / Arsenal,"MF, FW",eng ENG,27,1998
Evann Guessand,Crystal Palace / Aston Villa,MF,ci CIV,24,2001
Facundo Buonanotte,Chelsea / Leeds United,MF,ar ARG,20,2004
Harvey Elliott,Liverpool / Aston Villa,"MF, FW",eng ENG,22,2003
James Ward-Prowse,West Ham / Burnley,MF,eng ENG,30,1994
Jørgen Strand Larsen,Wolves / Crystal Palace,FW,no NOR,25,2000
Marc Guiu,Sunderland / Chelsea,FW,es ESP,19,2006
Marc Guéhi,Crystal Palace / Manchester City,DF,eng ENG,25,2000
Oscar Bobb,Manchester City / Fulham,"MF, FW",no NOR,22,2003
Tyrique George,Chelsea / Everton,"MF, FW",eng ENG,19,2006

In [53]:
counting_stats_df = misc_stats_dup_df.drop(columns=["Rk", "Squad", "Pos", "Nation", "Age", "Born"]).groupby("Player").sum()

In [54]:
misc_stats_agg = pd.merge(misc_stats_agg, counting_stats_df, on="Player").reset_index()

In [55]:
misc_stats_agg

,Player,Squad,Pos,Nation,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
0,Adama Traoré,Fulham / West Ham,"MF, FW",es ESP,29,1996,4.3,1.0,0.0,0.0,7.0,8.0,5.0,27.0,0.0,2.0,0.0
1,Antoine Semenyo,Bournemouth / Manchester City,"MF, FW",gh GHA,25,2000,35.5,7.0,0.0,0.0,54.0,21.0,19.0,49.0,12.0,31.0,0.0
2,Brennan Johnson,Tottenham / Crystal Palace,"MF, FW",wls WAL,24,2001,19.2,6.0,0.0,0.0,20.0,15.0,14.0,68.0,4.0,16.0,0.0
3,Douglas Luiz,Aston Villa / Nottingham,MF,br BRA,27,1998,10.2,3.0,0.0,0.0,13.0,15.0,0.0,43.0,14.0,14.0,0.0
4,Eberechi Eze,Crystal Palace / Arsenal,"MF, FW",eng ENG,27,1998,21.0,1.0,0.0,0.0,16.0,39.0,1.0,12.0,11.0,14.0,0.0
5,Evann Guessand,Crystal Palace / Aston Villa,MF,ci CIV,24,2001,10.2,0.0,0.0,0.0,15.0,20.0,1.0,11.0,5.0,11.0,0.0
6,Facundo Buonanotte,Chelsea / Leeds United,MF,ar ARG,20,2004,0.9,1.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0
7,Harvey Elliott,Liverpool / Aston Villa,"MF, FW",eng ENG,22,2003,1.2,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0
8,James Ward-Prowse,West Ham / Burnley,MF,eng ENG,30,1994,12.2,1.0,0.0,0.0,8.0,13.0,0.0,74.0,21.0,6.0,0.0
9,Jørgen Strand Larsen,Wolves / Crystal Palace,FW,no NOR,25,2000,25.6,4.0,0.0,0.0,51.0,21.0,10.0,3.0,4.0,2.0,0.0
10,Marc Guiu,Sunderland / Chelsea,FW,es ESP,19,2006,3.1,1.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,0.0,0.0
11,Marc Guéhi,Crystal Palace / Manchester City,DF,eng ENG,25,2000,35.0,6.0,0.0,0.0,25.0,38.0,0.0,17.0,49.0,31.0,0.0
12,Oscar Bobb,Manchester City / Fulham,"MF, FW",no NOR,22,2003,11.5,1.0,0.0,0.0,9.0,17.0,0.0,14.0,9.0,12.0,0.0
13,Tyrique George,Chelsea / Everton,"MF, FW",eng ENG,19,2006,4.0,2.0,0.0,0.0,9.0,2.0,4.0,11.0,2.0,5.0,0.0

In [56]:
misc_stats_clean_df = pd.concat([misc_stats_without_dup, misc_stats_agg], ignore_index=True).drop(columns=["Rk"])
misc_stats_clean_df

,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,3.0,0.0,0.0,20.0,51.0,5.0,37.0,17.0,27.0,0.0
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,3.0,1.0,0.0,3.0,2.0,4.0,0.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,0.0,0.0,2.0,9.0,2.0,1.0,12.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,25.6,4.0,0.0,0.0,51.0,21.0,10.0,3.0,4.0,2.0,0.0
533,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,3.1,1.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,0.0,0.0
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,6.0,0.0,0.0,25.0,38.0,0.0,17.0,49.0,31.0,0.0
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,11.5,1.0,0.0,0.0,9.0,17.0,0.0,14.0,9.0,12.0,0.0
536,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,4.0,2.0,0.0,0.0,9.0,2.0,4.0,11.0,2.0,5.0,0.0

In [57]:
misc_stats_clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player              537 non-null    str
 1   Nation              537 non-null    str
 2   Pos                 537 non-null    str
 3   Squad               537 non-null    str
 4   Age                 537 non-null    str
 5   Born                537 non-null    str
 6   90s_played          537 non-null    float64
 7   yellow_cards        537 non-null    float64
 8   red_cards           537 non-null    float64
 9   second_yellow_card  537 non-null    float64
 10  fouls_committed     537 non-null    float64
 11  fouls_drawn         537 non-null    float64
 12  offsides            537 non-null    float64
 13  crosses             537 non-null    float64
 14  interceptions       537 non-null    float64
 15  tackles_won         537 non-null    float64
 16  own_goals           537 non-null    float64
dtypes: float64(11), str(6)
memory usage: 91.8 KB

In [58]:
standard_stats_dup_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
58,57,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,9.0,5.0,468.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.19,0.19,0.00,0.19
59,58,Oscar Bobb,no NOR,MF,Fulham,22,2003,14.0,6.0,571.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
75,74,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,1.0,1.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
76,75,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,3.0,0.0,39.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
154,150,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
156,151,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,4.0,1.0,112.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
162,157,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,1.0,1.0,83.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
163,158,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,32.0,21.0,1812.0,...,7.0,0.0,0.0,1.0,0.0,0.35,0.10,0.45,0.35,0.45
185,179,Tyrique George,eng ENG,FW,Chelsea,19,2006,4.0,0.0,145.0,...,0.0,0.0,0.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00
186,180,Tyrique George,eng ENG,MF,Everton,19,2006,11.0,1.0,218.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
205,199,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,20.0,1800.0,...,2.0,0.0,0.0,4.0,0.0,0.10,0.10,0.20,0.10,0.20
206,200,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,15.0,1350.0,...,1.0,0.0,0.0,2.0,0.0,0.07,0.07,0.13,0.07,0.13
208,201,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,8.0,3.0,330.0,...,1.0,0.0,0.0,0.0,0.0,0.27,0.27,0.55,0.27,0.55
209,202,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,13.0,6.0,588.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.15,0.15,0.00,0.15
213,206,Marc Guiu,es ESP,FW,Sunderland,19,2006,2.0,0.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
214,207,Marc Guiu,es ESP,FW,Chelsea,19,2006,8.0,1.0,257.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.35,0.35,0.00,0.35
264,255,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,16.0,6.0,610.0,...,2.0,0.0,0.0,2.0,0.0,0.30,0.00,0.30,0.30,0.30
265,256,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,18.0,13.0,1112.0,...,0.0,0.0,0.0,4.0,0.0,0.00,0.08,0.08,0.00,0.08
321,310,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,13.0,7.0,604.0,...,1.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15
322,311,Douglas Luiz,br BRA,MF,Nottingham,27,1998,8.0,5.0,315.0,...,0.0,0.0,0.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00
474,457,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,20.0,1798.0,...,9.0,1.0,2.0,6.0,0.0,0.50,0.15,0.65,0.45,0.60
475,458,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,17.0,17.0,1397.0,...,7.0,0.0,0.0,1.0,0.0,0.45,0.06,0.52,0.45,0.52
495,477,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,22.0,14.0,1404.0,...,0.0,1.0,2.0,2.0,0.0,0.06,0.06,0.13,0.00,0.06
496,478,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,14.0,12.0,903.0,...,3.0,0.0,0.0,2.0,0.0,0.30,0.00,0.30,0.30,0.30
518,500,Adama Traoré,es ESP,MF,Fulham,29,1996,15.0,1.0,274.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
520,501,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,9.0,0.0,121.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
542,523,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,5.0,5.0,413.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
543,524,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,13.0,7.0,684.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.13,0.13,0.00,0.13

In [59]:
standard_stats_dup_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'matches_played', 'starts', 'minutes', '90s_played', 'goals', 'assists',
       'goals_assists', 'non_penalty_goals', 'penalty_kicks_made',
       'penalty_kicks_attempted', 'yellow_cards', 'red_cards', 'goals_per90',
       'assists_per90', 'goals_assists_per90', 'non_penalty_goals_per90',
       'non_penalty_goals_assists_per90'],
      dtype='str')

In [60]:
set(list(shooting_clean_df.columns) + list(misc_stats_clean_df.columns))

{'90s_played',
 'Age',
 'Born',
 'Nation',
 'Player',
 'Pos',
 'Squad',
 'crosses',
 'fouls_committed',
 'fouls_drawn',
 'goals',
 'goals_per_shot',
 'goals_per_shot_on_target',
 'interceptions',
 'offsides',
 'own_goals',
 'penalty_kicks_attempted',
 'penalty_kicks_made',
 'red_cards',
 'second_yellow_card',
 'shots_on_target',
 'shots_on_target_pct',
 'shots_on_target_per90',
 'shots_per90',
 'shots_total',
 'tackles_won',
 'yellow_cards'}

In [61]:
set(standard_stats_without_dup.columns).intersection(set(list(shooting_clean_df.columns) + list(misc_stats_clean_df.columns)))

{'90s_played',
 'Age',
 'Born',
 'Nation',
 'Player',
 'Pos',
 'Squad',
 'goals',
 'penalty_kicks_attempted',
 'penalty_kicks_made',
 'red_cards',
 'yellow_cards'}

In [62]:
set(standard_stats_without_dup.columns) - set(list(shooting_clean_df.columns) + list(misc_stats_clean_df.columns))

{'Rk',
 'assists',
 'assists_per90',
 'goals_assists',
 'goals_assists_per90',
 'goals_per90',
 'matches_played',
 'minutes',
 'non_penalty_goals',
 'non_penalty_goals_assists_per90',
 'non_penalty_goals_per90',
 'starts'}

In [63]:
standard_stats_dup_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'matches_played', 'starts', 'minutes', '90s_played', 'goals', 'assists',
       'goals_assists', 'non_penalty_goals', 'penalty_kicks_made',
       'penalty_kicks_attempted', 'yellow_cards', 'red_cards', 'goals_per90',
       'assists_per90', 'goals_assists_per90', 'non_penalty_goals_per90',
       'non_penalty_goals_assists_per90'],
      dtype='str')

In [64]:
to_agg_col = ["matches_played", "starts", "minutes", "90s_played", "goals", "assists", "goals_assists", "non_penalty_goals", "penalty_kicks_made", "penalty_kicks_attempted"]

In [65]:
standard_stats_agg = standard_stats_dup_df.groupby("Player")[to_agg_col].sum()

In [66]:
standard_stats_agg["Squad"] = standard_stats_dup_df.groupby("Player")["Squad"].agg(lambda x: " / ".join(x))

In [67]:
standard_stats_agg["Pos"] = standard_stats_dup_df.groupby("Player")["Pos"].agg(lambda x: str(set(",".join(x).split(","))).replace("{", "").replace("}", "").replace("'", ""))

In [68]:
identifier_df = standard_stats_dup_df.groupby("Player")[identifier_col].first()

In [69]:
standard_stats_agg = pd.merge(standard_stats_agg, identifier_df, on="Player")

In [70]:
standard_stats_agg["goals_per90"] = (standard_stats_agg["goals"] / standard_stats_agg["90s_played"]).round(2)

In [71]:
standard_stats_agg["assists_per90"] = (standard_stats_agg["assists"] / standard_stats_agg["90s_played"]).round(2)

In [72]:
standard_stats_agg["goals_assists_per90"] = (standard_stats_agg["non_penalty_goals"] / standard_stats_agg["90s_played"]).round(2)

In [73]:
standard_stats_agg["non_penalty_goals_assists_per90"] = ((standard_stats_agg["non_penalty_goals"] + standard_stats_agg["assists"]) / standard_stats_agg["90s_played"]).round(2)

In [74]:
standard_stats_agg["non_penalty_goals_per90"] = (standard_stats_agg["assists"] / standard_stats_agg["90s_played"]).round(2)

In [75]:
standard_stats_agg

,matches_played,starts,minutes,90s_played,goals,assists,goals_assists,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,Squad,Pos,Nation,Age,Born,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_assists_per90,non_penalty_goals_per90
Player,,,,,,,,,,,,,,,,,,,,
Adama Traoré,24.0,1.0,395.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,Fulham / West Ham,"MF, FW",es ESP,29,1996,0.00,0.00,0.00,0.00,0.00
Antoine Semenyo,37.0,37.0,3195.0,35.5,17.0,4.0,21.0,16.0,1.0,2.0,Bournemouth / Manchester City,"MF, FW",gh GHA,25,2000,0.48,0.11,0.45,0.56,0.11
Brennan Johnson,34.0,19.0,1722.0,19.2,2.0,1.0,3.0,2.0,0.0,0.0,Tottenham / Crystal Palace,"MF, FW",wls WAL,24,2001,0.10,0.05,0.10,0.16,0.05
Douglas Luiz,21.0,12.0,919.0,10.2,1.0,0.0,1.0,1.0,0.0,0.0,Aston Villa / Nottingham,MF,br BRA,27,1998,0.10,0.00,0.10,0.10,0.00
Eberechi Eze,33.0,22.0,1895.0,21.0,7.0,2.0,9.0,7.0,0.0,0.0,Crystal Palace / Arsenal,"MF, FW",eng ENG,27,1998,0.33,0.10,0.33,0.43,0.10
Evann Guessand,21.0,9.0,918.0,10.2,1.0,2.0,3.0,1.0,0.0,0.0,Crystal Palace / Aston Villa,MF,ci CIV,24,2001,0.10,0.20,0.10,0.29,0.20
Facundo Buonanotte,4.0,1.0,84.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,Chelsea / Leeds United,MF,ar ARG,20,2004,0.00,0.00,0.00,0.00,0.00
Harvey Elliott,5.0,1.0,113.0,1.2,0.0,0.0,0.0,0.0,0.0,0.0,Liverpool / Aston Villa,"MF, FW",eng ENG,22,2003,0.00,0.00,0.00,0.00,0.00
James Ward-Prowse,18.0,12.0,1097.0,12.2,0.0,1.0,1.0,0.0,0.0,0.0,West Ham / Burnley,MF,eng ENG,30,1994,0.00,0.08,0.00,0.08,0.08
Jørgen Strand Larsen,36.0,26.0,2307.0,25.6,4.0,1.0,5.0,3.0,1.0,2.0,Wolves / Crystal Palace,FW,no NOR,25,2000,0.16,0.04,0.12,0.16,0.04
Marc Guiu,10.0,1.0,272.0,3.1,0.0,1.0,1.0,0.0,0.0,0.0,Sunderland / Chelsea,FW,es ESP,19,2006,0.00,0.32,0.00,0.32,0.32
Marc Guéhi,35.0,35.0,3150.0,35.0,3.0,3.0,6.0,3.0,0.0,0.0,Crystal Palace / Manchester City,DF,eng ENG,25,2000,0.09,0.09,0.09,0.17,0.09
Oscar Bobb,23.0,11.0,1039.0,11.5,0.0,1.0,1.0,0.0,0.0,0.0,Manchester City / Fulham,"MF, FW",no NOR,22,2003,0.00,0.09,0.00,0.09,0.09
Tyrique George,15.0,1.0,363.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,Chelsea / Everton,"MF, FW",eng ENG,19,2006,0.00,0.00,0.00,0.00,0.00

In [76]:
standard_stats_agg = standard_stats_agg.reset_index()

In [77]:
standard_stats_without_dup.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'matches_played', 'starts', 'minutes', '90s_played', 'goals', 'assists',
       'goals_assists', 'non_penalty_goals', 'penalty_kicks_made',
       'penalty_kicks_attempted', 'yellow_cards', 'red_cards', 'goals_per90',
       'assists_per90', 'goals_assists_per90', 'non_penalty_goals_per90',
       'non_penalty_goals_assists_per90'],
      dtype='str')

In [78]:
standard_stats_cleaned_df = pd.concat([standard_stats_without_dup, standard_stats_agg], ignore_index=True).drop(columns=["Rk"])

In [79]:
standard_stats_cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Player                           537 non-null    str
 1   Nation                           537 non-null    str
 2   Pos                              537 non-null    str
 3   Squad                            537 non-null    str
 4   Age                              537 non-null    str
 5   Born                             537 non-null    str
 6   matches_played                   537 non-null    float64
 7   starts                           537 non-null    float64
 8   minutes                          537 non-null    float64
 9   90s_played                       537 non-null    float64
 10  goals                            537 non-null    float64
 11  assists                          537 non-null    float64
 12  goals_assists                    537 non-null    float64
 13  non_penalty_goals                537 non-null    float64
 14  penalty_kicks_made               537 non-null    float64
 15  penalty_kicks_attempted          537 non-null    float64
 16  yellow_cards                     523 non-null    float64
 17  red_cards                        523 non-null    float64
 18  goals_per90                      537 non-null    float64
 19  assists_per90                    537 non-null    float64
 20  goals_assists_per90              537 non-null    float64
 21  non_penalty_goals_per90          537 non-null    float64
 22  non_penalty_goals_assists_per90  537 non-null    float64
dtypes: float64(17), str(6)
memory usage: 117.0 KB

In [80]:
standard_stats_cleaned_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,4.0,0.0,0.0,3.0,0.0,0.15,0.18,0.33,0.15,0.33
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,0.2,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,1.8,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,3.2,...,2.0,0.0,0.0,0.0,0.0,0.63,0.00,0.63,0.63,0.63
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,7.4,...,1.0,0.0,0.0,1.0,0.0,0.14,0.00,0.14,0.14,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,3.0,1.0,2.0,NaN,NaN,0.16,0.04,0.12,0.04,0.16
533,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,1.0,272.0,3.1,...,0.0,0.0,0.0,NaN,NaN,0.00,0.32,0.00,0.32,0.32
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,3.0,0.0,0.0,NaN,NaN,0.09,0.09,0.09,0.09,0.17
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,0.0,0.0,0.0,NaN,NaN,0.00,0.09,0.00,0.09,0.09
536,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,1.0,363.0,4.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.00,0.00,0.00,0.00

In [81]:
set(playingtime_dup_df["Player"].unique().tolist()) - set(standard_stats_dup_df["Player"].unique().tolist())

{'Igor', 'Stefan Ortega'}

In [82]:
playingtime_dup_df[playingtime_dup_df["Player"].isin(["Igor", "Stefan Ortega"])]

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
296,286,Igor,br BRA,DF,Brighton,27,1998,0.0,NaN,NaN,...,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0
297,287,Igor,br BRA,DF,West Ham,27,1998,4.0,105.0,26.0,...,1.0,3.0,5.0,9.0,2.00,4.0,3.0,1.0,0.86,1.4
503,485,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,270.0,90.0,...,3.0,0.0,0.0,8.0,0.33,1.0,4.0,-3.0,-1.00,-1.0
504,486,Stefan Ortega,de GER,GK,Manchester City,32,1992,0.0,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0

In [83]:
playingtime_dup_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
76,75,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,9.0,468.0,52.0,...,2.0,4.0,20.0,4.0,1.67,10.0,5.0,5.0,0.96,-0.17
78,76,Oscar Bobb,no NOR,MF,Fulham,22,2003,14.0,571.0,41.0,...,0.0,8.0,23.0,0.0,1.29,7.0,7.0,0.0,0.00,0.13
98,96,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,1.0,45.0,45.0,...,0.0,0.0,0.0,4.0,1.00,0.0,1.0,-1.0,-2.00,-2.19
99,97,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,3.0,39.0,13.0,...,0.0,3.0,13.0,5.0,0.33,0.0,3.0,-3.0,-6.92,-6.82
188,182,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,1.0,1.0,1.0,...,0.0,1.0,1.0,2.0,3.00,1.0,0.0,1.0,90.00,89.76
189,183,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,4.0,112.0,28.0,...,0.0,3.0,22.0,4.0,1.25,2.0,2.0,0.0,0.00,-0.19
197,191,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,1.0,83.0,83.0,...,0.0,0.0,0.0,0.0,1.00,0.0,0.0,0.0,0.00,0.27
198,192,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,32.0,1812.0,57.0,...,5.0,11.0,24.0,4.0,2.09,37.0,14.0,23.0,1.14,-0.03
224,217,Tyrique George,eng ENG,FW,Chelsea,19,2006,4.0,145.0,36.0,...,0.0,4.0,36.0,4.0,1.00,5.0,2.0,3.0,1.86,1.78
225,218,Tyrique George,eng ENG,MF,Everton,19,2006,11.0,218.0,20.0,...,0.0,10.0,16.0,2.0,0.73,5.0,7.0,-2.0,-0.83,-0.80
251,243,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,1800.0,90.0,...,20.0,0.0,0.0,0.0,1.35,22.0,23.0,-1.0,-0.05,0.45
252,244,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,1350.0,90.0,...,15.0,0.0,0.0,0.0,2.33,31.0,12.0,19.0,1.27,0.27
253,245,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,8.0,330.0,41.0,...,1.0,5.0,23.0,0.0,1.38,8.0,5.0,3.0,0.82,1.20
254,246,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,13.0,588.0,45.0,...,0.0,7.0,27.0,5.0,1.77,9.0,10.0,-1.0,-0.15,-0.41
258,250,Marc Guiu,es ESP,FW,Sunderland,19,2006,2.0,15.0,8.0,...,0.0,2.0,8.0,1.0,1.50,1.0,1.0,0.0,0.00,0.16
260,251,Marc Guiu,es ESP,FW,Chelsea,19,2006,8.0,257.0,32.0,...,0.0,7.0,26.0,17.0,1.63,6.0,2.0,4.0,1.40,1.34
296,286,Igor,br BRA,DF,Brighton,27,1998,0.0,NaN,NaN,...,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.00
297,287,Igor,br BRA,DF,West Ham,27,1998,4.0,105.0,26.0,...,1.0,3.0,5.0,9.0,2.00,4.0,3.0,1.0,0.86,1.40
318,307,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,16.0,610.0,38.0,...,1.0,10.0,15.0,2.0,1.38,13.0,5.0,8.0,1.18,1.72
319,308,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,18.0,1112.0,62.0,...,4.0,5.0,24.0,1.0,1.00,7.0,19.0,-12.0,-0.97,-1.05
390,376,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,13.0,604.0,46.0,...,1.0,6.0,13.0,2.0,1.23,5.0,8.0,-3.0,-0.45,-0.77
391,377,Douglas Luiz,br BRA,MF,Nottingham,27,1998,8.0,315.0,39.0,...,0.0,3.0,19.0,6.0,0.63,1.0,7.0,-6.0,-1.71,-1.80
503,485,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,270.0,90.0,...,3.0,0.0,0.0,8.0,0.33,1.0,4.0,-3.0,-1.00,-1.00
504,486,Stefan Ortega,de GER,GK,Manchester City,32,1992,0.0,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.00
591,570,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,1798.0,90.0,...,18.0,0.0,0.0,0.0,1.25,31.0,38.0,-7.0,-0.35,-0.96
592,571,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,17.0,1398.0,82.0,...,9.0,0.0,0.0,0.0,2.06,28.0,14.0,14.0,0.90,-0.35
627,604,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,22.0,1404.0,64.0,...,7.0,8.0,31.0,0.0,0.36,6.0,26.0,-20.0,-1.28,-0.34
628,605,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,14.0,903.0,65.0,...,3.0,2.0,26.0,0.0,1.14,12.0,15.0,-3.0,-0.30,-0.05
655,631,Adama Traoré,es ESP,MF,Fulham,29,1996,15.0,274.0,18.0,...,0.0,14.0,14.0,6.0,1.20,4.0,7.0,-3.0,-0.99,-0.96
656,632,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,9.0,121.0,13.0,...,0.0,9.0,13.0,3.0,1.22,1.0,5.0,-4.0,-2.98,-2.57
683,658,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,5.0,413.0,83.0,...,2.0,0.0,0.0,1.0,0.60,2.0,11.0,-9.0,-1.96,-1.66
684,659,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,13.0,684.0,53.0,...,4.0,6.0,18.0,1.0,0.54,6.0,16.0,-10.0,-1.32,-0.43

In [84]:
playingtime_dup_df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       'matches_played', 'minutes', 'minutes_per_match', 'minutes_pct',
       '90s_played', 'starts', 'minutes_per_start', 'complete_matches',
       'sub_appearances', 'minutes_per_sub', 'unused_sub', 'points_per_match',
       'goals_scored_on_pitch', 'goals_allowed_on_pitch', 'plus_minus',
       'plus_minus_per90', 'plus_minus_net_per90'],
      dtype='str')

In [85]:
playingtime_dup_df

,Rk,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
76,75,Oscar Bobb,no NOR,"MF,FW",Manchester City,22,2003,9.0,468.0,52.0,...,2.0,4.0,20.0,4.0,1.67,10.0,5.0,5.0,0.96,-0.17
78,76,Oscar Bobb,no NOR,MF,Fulham,22,2003,14.0,571.0,41.0,...,0.0,8.0,23.0,0.0,1.29,7.0,7.0,0.0,0.00,0.13
98,96,Facundo Buonanotte,ar ARG,MF,Chelsea,20,2004,1.0,45.0,45.0,...,0.0,0.0,0.0,4.0,1.00,0.0,1.0,-1.0,-2.00,-2.19
99,97,Facundo Buonanotte,ar ARG,MF,Leeds United,20,2004,3.0,39.0,13.0,...,0.0,3.0,13.0,5.0,0.33,0.0,3.0,-3.0,-6.92,-6.82
188,182,Harvey Elliott,eng ENG,"FW,MF",Liverpool,22,2003,1.0,1.0,1.0,...,0.0,1.0,1.0,2.0,3.00,1.0,0.0,1.0,90.00,89.76
189,183,Harvey Elliott,eng ENG,MF,Aston Villa,22,2003,4.0,112.0,28.0,...,0.0,3.0,22.0,4.0,1.25,2.0,2.0,0.0,0.00,-0.19
197,191,Eberechi Eze,eng ENG,MF,Crystal Palace,27,1998,1.0,83.0,83.0,...,0.0,0.0,0.0,0.0,1.00,0.0,0.0,0.0,0.00,0.27
198,192,Eberechi Eze,eng ENG,"MF,FW",Arsenal,27,1998,32.0,1812.0,57.0,...,5.0,11.0,24.0,4.0,2.09,37.0,14.0,23.0,1.14,-0.03
224,217,Tyrique George,eng ENG,FW,Chelsea,19,2006,4.0,145.0,36.0,...,0.0,4.0,36.0,4.0,1.00,5.0,2.0,3.0,1.86,1.78
225,218,Tyrique George,eng ENG,MF,Everton,19,2006,11.0,218.0,20.0,...,0.0,10.0,16.0,2.0,0.73,5.0,7.0,-2.0,-0.83,-0.80
251,243,Marc Guéhi,eng ENG,DF,Crystal Palace,25,2000,20.0,1800.0,90.0,...,20.0,0.0,0.0,0.0,1.35,22.0,23.0,-1.0,-0.05,0.45
252,244,Marc Guéhi,eng ENG,DF,Manchester City,25,2000,15.0,1350.0,90.0,...,15.0,0.0,0.0,0.0,2.33,31.0,12.0,19.0,1.27,0.27
253,245,Evann Guessand,ci CIV,MF,Crystal Palace,24,2001,8.0,330.0,41.0,...,1.0,5.0,23.0,0.0,1.38,8.0,5.0,3.0,0.82,1.20
254,246,Evann Guessand,ci CIV,MF,Aston Villa,24,2001,13.0,588.0,45.0,...,0.0,7.0,27.0,5.0,1.77,9.0,10.0,-1.0,-0.15,-0.41
258,250,Marc Guiu,es ESP,FW,Sunderland,19,2006,2.0,15.0,8.0,...,0.0,2.0,8.0,1.0,1.50,1.0,1.0,0.0,0.00,0.16
260,251,Marc Guiu,es ESP,FW,Chelsea,19,2006,8.0,257.0,32.0,...,0.0,7.0,26.0,17.0,1.63,6.0,2.0,4.0,1.40,1.34
296,286,Igor,br BRA,DF,Brighton,27,1998,0.0,NaN,NaN,...,0.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,0.00
297,287,Igor,br BRA,DF,West Ham,27,1998,4.0,105.0,26.0,...,1.0,3.0,5.0,9.0,2.00,4.0,3.0,1.0,0.86,1.40
318,307,Brennan Johnson,wls WAL,"MF,FW",Tottenham,24,2001,16.0,610.0,38.0,...,1.0,10.0,15.0,2.0,1.38,13.0,5.0,8.0,1.18,1.72
319,308,Brennan Johnson,wls WAL,"MF,FW",Crystal Palace,24,2001,18.0,1112.0,62.0,...,4.0,5.0,24.0,1.0,1.00,7.0,19.0,-12.0,-0.97,-1.05
390,376,Douglas Luiz,br BRA,MF,Aston Villa,27,1998,13.0,604.0,46.0,...,1.0,6.0,13.0,2.0,1.23,5.0,8.0,-3.0,-0.45,-0.77
391,377,Douglas Luiz,br BRA,MF,Nottingham,27,1998,8.0,315.0,39.0,...,0.0,3.0,19.0,6.0,0.63,1.0,7.0,-6.0,-1.71,-1.80
503,485,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,270.0,90.0,...,3.0,0.0,0.0,8.0,0.33,1.0,4.0,-3.0,-1.00,-1.00
504,486,Stefan Ortega,de GER,GK,Manchester City,32,1992,0.0,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.00
591,570,Antoine Semenyo,gh GHA,MF,Bournemouth,25,2000,20.0,1798.0,90.0,...,18.0,0.0,0.0,0.0,1.25,31.0,38.0,-7.0,-0.35,-0.96
592,571,Antoine Semenyo,gh GHA,"MF,FW",Manchester City,25,2000,17.0,1398.0,82.0,...,9.0,0.0,0.0,0.0,2.06,28.0,14.0,14.0,0.90,-0.35
627,604,Jørgen Strand Larsen,no NOR,FW,Wolves,25,2000,22.0,1404.0,64.0,...,7.0,8.0,31.0,0.0,0.36,6.0,26.0,-20.0,-1.28,-0.34
628,605,Jørgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,14.0,903.0,65.0,...,3.0,2.0,26.0,0.0,1.14,12.0,15.0,-3.0,-0.30,-0.05
655,631,Adama Traoré,es ESP,MF,Fulham,29,1996,15.0,274.0,18.0,...,0.0,14.0,14.0,6.0,1.20,4.0,7.0,-3.0,-0.99,-0.96
656,632,Adama Traoré,es ESP,"FW,MF",West Ham,29,1996,9.0,121.0,13.0,...,0.0,9.0,13.0,3.0,1.22,1.0,5.0,-4.0,-2.98,-2.57
683,658,James Ward-Prowse,eng ENG,MF,West Ham,30,1994,5.0,413.0,83.0,...,2.0,0.0,0.0,1.0,0.60,2.0,11.0,-9.0,-1.96,-1.66
684,659,James Ward-Prowse,eng ENG,MF,Burnley,30,1994,13.0,684.0,53.0,...,4.0,6.0,18.0,1.0,0.54,6.0,16.0,-10.0,-1.32,-0.43

In [86]:
counting_stats = ["matches_played", "minutes", "starts", "complete_matches", "sub_appearances", "unused_sub", "goals_scored_on_pitch", "goals_allowed_on_pitch", "plus_minus", "points_per_match", "plus_minus_net_per90"]

In [87]:
playingtime_agg_df = playingtime_dup_df.groupby("Player")[counting_stats].sum()

In [88]:
squad_df = playingtime_dup_df.groupby("Player")["Squad"].agg(lambda x: " / ".join(x))

In [89]:
playingtime_agg_df = pd.merge(playingtime_agg_df, squad_df, on="Player")

In [90]:
pos_df = playingtime_dup_df.groupby("Player")["Pos"].agg(lambda x: str(set(",".join(x).split(","))).replace("{", "").replace("}", "").replace("'", ""))

In [91]:
playingtime_agg_df = pd.merge(playingtime_agg_df, pos_df, on="Player")

In [92]:
playingtime_agg_df

,matches_played,minutes,starts,complete_matches,sub_appearances,unused_sub,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,points_per_match,plus_minus_net_per90,Squad,Pos
Player,,,,,,,,,,,,,
Adama Traoré,24.0,395.0,1.0,0.0,23.0,9.0,5.0,12.0,-7.0,2.42,-3.53,Fulham / West Ham,"MF, FW"
Antoine Semenyo,37.0,3196.0,37.0,27.0,0.0,0.0,59.0,52.0,7.0,3.31,-1.31,Bournemouth / Manchester City,"MF, FW"
Brennan Johnson,34.0,1722.0,19.0,5.0,15.0,3.0,20.0,24.0,-4.0,2.38,0.67,Tottenham / Crystal Palace,"MF, FW"
Douglas Luiz,21.0,919.0,12.0,1.0,9.0,8.0,6.0,15.0,-9.0,1.86,-2.57,Aston Villa / Nottingham,MF
Eberechi Eze,33.0,1895.0,22.0,5.0,11.0,4.0,37.0,14.0,23.0,3.09,0.24,Crystal Palace / Arsenal,"MF, FW"
Evann Guessand,21.0,918.0,9.0,1.0,12.0,5.0,17.0,15.0,2.0,3.15,0.79,Crystal Palace / Aston Villa,MF
Facundo Buonanotte,4.0,84.0,1.0,0.0,3.0,9.0,0.0,4.0,-4.0,1.33,-9.01,Chelsea / Leeds United,MF
Harvey Elliott,5.0,113.0,1.0,0.0,4.0,6.0,3.0,2.0,1.0,4.25,89.57,Liverpool / Aston Villa,"MF, FW"
Igor,4.0,105.0,1.0,1.0,3.0,15.0,4.0,3.0,1.0,2.00,1.40,Brighton / West Ham,DF
James Ward-Prowse,18.0,1097.0,12.0,6.0,6.0,2.0,8.0,27.0,-19.0,1.14,-2.09,West Ham / Burnley,MF
Jørgen Strand Larsen,36.0,2307.0,26.0,10.0,10.0,0.0,18.0,41.0,-23.0,1.50,-0.39,Wolves / Crystal Palace,FW
Marc Guiu,10.0,272.0,1.0,0.0,9.0,18.0,7.0,3.0,4.0,3.13,1.50,Sunderland / Chelsea,FW
Marc Guéhi,35.0,3150.0,35.0,35.0,0.0,0.0,53.0,35.0,18.0,3.68,0.72,Crystal Palace / Manchester City,DF
Oscar Bobb,23.0,1039.0,11.0,2.0,12.0,4.0,17.0,12.0,5.0,2.96,-0.04,Manchester City / Fulham,"MF, FW"
Stefan Ortega,3.0,270.0,3.0,3.0,0.0,9.0,1.0,4.0,-3.0,0.33,-1.00,Nottingham / Manchester City,GK
Tyrique George,15.0,363.0,1.0,0.0,14.0,6.0,10.0,9.0,1.0,1.73,0.98,Chelsea / Everton,"MF, FW"

In [93]:
playingtime_agg_df["minutes_per_match"] = (playingtime_agg_df["minutes"] / playingtime_agg_df["matches_played"]).round(1)

In [94]:
playingtime_agg_df["minutes_per_start"] = (playingtime_agg_df["minutes"] / playingtime_agg_df["starts"]).round(1)

In [95]:
playingtime_agg_df["minutes_per_sub"] = (playingtime_agg_df["minutes"] / playingtime_agg_df["sub_appearances"]).round(1)

In [96]:
playingtime_agg_df["minutes_per_sub"] = (playingtime_agg_df["minutes"] / playingtime_agg_df["sub_appearances"]).round(1)

In [97]:
playingtime_agg_df["minutes_pct"] = (playingtime_agg_df["minutes"] / 3420).round(1)

In [98]:
playingtime_agg_df["90s_played"] = (playingtime_agg_df["minutes"] / 90).round(1)

In [99]:
playingtime_agg_df["plus_minus_per90"] = (playingtime_agg_df["plus_minus"] / playingtime_agg_df["90s_played"]).round(1)

In [100]:
playingtime_agg_df = pd.merge(playingtime_agg_df, identifier_df, on="Player")

In [101]:
playingtime_agg_df = playingtime_agg_df.reset_index()
playingtime_agg_df

,Player,matches_played,minutes,starts,complete_matches,sub_appearances,unused_sub,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,...,Pos,minutes_per_match,minutes_per_start,minutes_per_sub,minutes_pct,90s_played,plus_minus_per90,Nation,Age,Born
0,Adama Traoré,24.0,395.0,1.0,0.0,23.0,9.0,5.0,12.0,-7.0,...,"MF, FW",16.5,395.0,17.2,0.1,4.4,-1.6,es ESP,29,1996
1,Antoine Semenyo,37.0,3196.0,37.0,27.0,0.0,0.0,59.0,52.0,7.0,...,"MF, FW",86.4,86.4,inf,0.9,35.5,0.2,gh GHA,25,2000
2,Brennan Johnson,34.0,1722.0,19.0,5.0,15.0,3.0,20.0,24.0,-4.0,...,"MF, FW",50.6,90.6,114.8,0.5,19.1,-0.2,wls WAL,24,2001
3,Douglas Luiz,21.0,919.0,12.0,1.0,9.0,8.0,6.0,15.0,-9.0,...,MF,43.8,76.6,102.1,0.3,10.2,-0.9,br BRA,27,1998
4,Eberechi Eze,33.0,1895.0,22.0,5.0,11.0,4.0,37.0,14.0,23.0,...,"MF, FW",57.4,86.1,172.3,0.6,21.1,1.1,eng ENG,27,1998
5,Evann Guessand,21.0,918.0,9.0,1.0,12.0,5.0,17.0,15.0,2.0,...,MF,43.7,102.0,76.5,0.3,10.2,0.2,ci CIV,24,2001
6,Facundo Buonanotte,4.0,84.0,1.0,0.0,3.0,9.0,0.0,4.0,-4.0,...,MF,21.0,84.0,28.0,0.0,0.9,-4.4,ar ARG,20,2004
7,Harvey Elliott,5.0,113.0,1.0,0.0,4.0,6.0,3.0,2.0,1.0,...,"MF, FW",22.6,113.0,28.2,0.0,1.3,0.8,eng ENG,22,2003
8,James Ward-Prowse,18.0,1097.0,12.0,6.0,6.0,2.0,8.0,27.0,-19.0,...,MF,60.9,91.4,182.8,0.3,12.2,-1.6,eng ENG,30,1994
9,Jørgen Strand Larsen,36.0,2307.0,26.0,10.0,10.0,0.0,18.0,41.0,-23.0,...,FW,64.1,88.7,230.7,0.7,25.6,-0.9,no NOR,25,2000
10,Marc Guiu,10.0,272.0,1.0,0.0,9.0,18.0,7.0,3.0,4.0,...,FW,27.2,272.0,30.2,0.1,3.0,1.3,es ESP,19,2006
11,Marc Guéhi,35.0,3150.0,35.0,35.0,0.0,0.0,53.0,35.0,18.0,...,DF,90.0,90.0,inf,0.9,35.0,0.5,eng ENG,25,2000
12,Oscar Bobb,23.0,1039.0,11.0,2.0,12.0,4.0,17.0,12.0,5.0,...,"MF, FW",45.2,94.5,86.6,0.3,11.5,0.4,no NOR,22,2003
13,Tyrique George,15.0,363.0,1.0,0.0,14.0,6.0,10.0,9.0,1.0,...,"MF, FW",24.2,363.0,25.9,0.1,4.0,0.2,eng ENG,19,2006

In [102]:
playingtime_cleaned_df = pd.concat([playingtime_without_dup, playingtime_agg_df], ignore_index=True).drop(columns=["Rk"])

In [103]:
playingtime_cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Player                  675 non-null    str
 1   Nation                  672 non-null    str
 2   Pos                     675 non-null    str
 3   Squad                   675 non-null    str
 4   Age                     672 non-null    str
 5   Born                    672 non-null    str
 6   matches_played          675 non-null    float64
 7   minutes                 535 non-null    float64
 8   minutes_per_match       535 non-null    float64
 9   minutes_pct             535 non-null    float64
 10  90s_played              535 non-null    float64
 11  starts                  675 non-null    float64
 12  minutes_per_start       472 non-null    float64
 13  complete_matches        675 non-null    float64
 14  sub_appearances         675 non-null    float64
 15  minutes_per_sub         675 non-null    float64
 16  unused_sub              675 non-null    float64
 17  points_per_match        535 non-null    float64
 18  goals_scored_on_pitch   535 non-null    float64
 19  goals_allowed_on_pitch  535 non-null    float64
 20  plus_minus              535 non-null    float64
 21  plus_minus_per90        535 non-null    float64
 22  plus_minus_net_per90    675 non-null    float64
dtypes: float64(17), str(6)
memory usage: 147.0 KB

In [104]:
playingtime_cleaned_df[playingtime_cleaned_df["Nation"].isna()]

,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,minutes_pct,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
392,Conor McManus,NaN,DF,Brentford,NaN,NaN,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0
574,Joshua Stephenson,NaN,MF,Brentford,NaN,NaN,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,0.0
652,Will Wright,NaN,FW,Liverpool,NaN,NaN,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,4.0,NaN,NaN,NaN,NaN,NaN,0.0

In [105]:
playingtime_cleaned_df[playingtime_cleaned_df["minutes"] >= 900]

,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,minutes_pct,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,2449.0,66.0,71.6,...,2.0,7.0,21.0,1.0,1.19,35.0,31.0,4.0,0.15,1.17
5,Tyler Adams,us USA,MF,Bournemouth,26,1999,25.0,1773.0,71.0,51.8,...,10.0,4.0,28.0,1.0,1.52,25.0,28.0,-3.0,-0.15,-0.53
8,Amine Adli,ma MAR,MF,Bournemouth,25,2000,31.0,1093.0,35.0,32.0,...,2.0,21.0,17.0,6.0,1.48,18.0,17.0,1.0,0.08,-0.03
9,Emmanuel Agbadou,ci CIV,DF,Wolves,28,1997,14.0,1101.0,79.0,32.2,...,11.0,2.0,38.0,4.0,0.14,6.0,27.0,-21.0,-1.72,-0.94
12,Ola Aina,ng NGA,DF,Nottingham,28,1996,18.0,1588.0,88.0,46.4,...,15.0,0.0,0.0,0.0,1.39,27.0,19.0,8.0,0.45,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,Evann Guessand,ci CIV,MF,Crystal Palace / Aston Villa,24,2001,21.0,918.0,43.7,0.3,...,1.0,12.0,76.5,5.0,3.15,17.0,15.0,2.0,0.20,0.79
669,James Ward-Prowse,eng ENG,MF,West Ham / Burnley,30,1994,18.0,1097.0,60.9,0.3,...,6.0,6.0,182.8,2.0,1.14,8.0,27.0,-19.0,-1.60,-2.09
670,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,2307.0,64.1,0.7,...,10.0,10.0,230.7,0.0,1.50,18.0,41.0,-23.0,-0.90,-0.39
672,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,3150.0,90.0,0.9,...,35.0,0.0,inf,0.0,3.68,53.0,35.0,18.0,0.50,0.72
673,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,1039.0,45.2,0.3,...,2.0,12.0,86.6,4.0,2.96,17.0,12.0,5.0,0.40,-0.04

In [106]:
goalkeeping_df["Player"].nunique()

40

In [107]:
goalkeeping_df = goalkeeping_df.drop(columns=["Rk"])

#### Merging all Dataframe to Master Dataset

In [108]:
standard_stats_cleaned_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,non_penalty_goals,penalty_kicks_made,penalty_kicks_attempted,yellow_cards,red_cards,goals_per90,assists_per90,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,4.0,0.0,0.0,3.0,0.0,0.15,0.18,0.33,0.15,0.33
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,0.2,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,1.8,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,3.2,...,2.0,0.0,0.0,0.0,0.0,0.63,0.00,0.63,0.63,0.63
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,7.4,...,1.0,0.0,0.0,1.0,0.0,0.14,0.00,0.14,0.14,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,3.0,1.0,2.0,NaN,NaN,0.16,0.04,0.12,0.04,0.16
533,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,1.0,272.0,3.1,...,0.0,0.0,0.0,NaN,NaN,0.00,0.32,0.00,0.32,0.32
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,3.0,0.0,0.0,NaN,NaN,0.09,0.09,0.09,0.09,0.17
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,0.0,0.0,0.0,NaN,NaN,0.00,0.09,0.00,0.09,0.09
536,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,1.0,363.0,4.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.00,0.00,0.00,0.00

In [109]:
shooting_clean_df

,Player,Nation,Pos,Squad,Age,Born,90s_played,goals,shots_total,shots_on_target,shots_on_target_pct,shots_per90,shots_on_target_per90,goals_per_shot,goals_per_shot_on_target,penalty_kicks_made,penalty_kicks_attempted
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,4.0,47.0,17.0,36.20,1.73,0.62,0.09,0.24,0.0,0.0
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,2.0,9.0,3.0,33.30,2.83,0.94,0.22,0.67,0.0,0.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,4.0,2.0,50.00,0.54,0.27,0.25,0.50,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,25.6,4.0,44.0,14.0,0.32,1.72,0.55,0.09,0.29,1.0,2.0
533,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,3.1,0.0,13.0,2.0,0.15,4.19,0.65,0.00,0.00,0.0,0.0
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,3.0,32.0,9.0,0.28,0.91,0.26,0.09,0.33,0.0,0.0
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,11.5,0.0,12.0,3.0,0.25,1.04,0.26,0.00,0.00,0.0,0.0
536,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,4.0,0.0,10.0,5.0,0.50,2.50,1.25,0.00,0.00,0.0,0.0

In [110]:
misc_stats_clean_df

,Player,Nation,Pos,Squad,Age,Born,90s_played,yellow_cards,red_cards,second_yellow_card,fouls_committed,fouls_drawn,offsides,crosses,interceptions,tackles_won,own_goals
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,27.2,3.0,0.0,0.0,20.0,51.0,5.0,37.0,17.0,27.0,0.0
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,0.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,1.8,0.0,0.0,0.0,3.0,1.0,0.0,3.0,2.0,4.0,0.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,3.2,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,7.4,1.0,0.0,0.0,2.0,9.0,2.0,1.0,12.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,25.6,4.0,0.0,0.0,51.0,21.0,10.0,3.0,4.0,2.0,0.0
533,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,3.1,1.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,0.0,0.0
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,6.0,0.0,0.0,25.0,38.0,0.0,17.0,49.0,31.0,0.0
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,11.5,1.0,0.0,0.0,9.0,17.0,0.0,14.0,9.0,12.0,0.0
536,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,4.0,2.0,0.0,0.0,9.0,2.0,4.0,11.0,2.0,5.0,0.0

In [111]:
playingtime_cleaned_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,minutes_pct,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,2449.0,66.0,71.6,...,2.0,7.0,21.0,1.0,1.19,35.0,31.0,4.0,0.15,1.17
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,17.0,17.0,0.5,...,0.0,1.0,17.0,1.0,1.00,0.0,0.0,0.0,0.00,1.08
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,164.0,55.0,4.8,...,0.0,1.0,45.0,13.0,1.00,2.0,4.0,-2.0,-1.10,-1.07
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,286.0,24.0,8.4,...,1.0,10.0,14.0,2.0,1.00,4.0,8.0,-4.0,-1.26,-1.57
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,666.0,39.0,19.5,...,1.0,9.0,11.0,18.0,1.18,10.0,13.0,-3.0,-0.41,-0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,2307.0,64.1,0.7,...,10.0,10.0,230.7,0.0,1.50,18.0,41.0,-23.0,-0.90,-0.39
671,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,272.0,27.2,0.1,...,0.0,9.0,30.2,18.0,3.13,7.0,3.0,4.0,1.30,1.50
672,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,3150.0,90.0,0.9,...,35.0,0.0,inf,0.0,3.68,53.0,35.0,18.0,0.50,0.72
673,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,1039.0,45.2,0.3,...,2.0,12.0,86.6,4.0,2.96,17.0,12.0,5.0,0.40,-0.04
674,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,363.0,24.2,0.1,...,0.0,14.0,25.9,6.0,1.73,10.0,9.0,1.0,0.20,0.98

In [112]:
goalkeeping_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,wins,draws,losses,clean_sheets,clean_sheet_pct,pk_attempted,pk_allowed,pk_saved,pk_missed,pk_save_pct
0,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,26.0,...,13.0,8.0,5.0,8.0,30.8,2.0,2.0,0.0,0.0,0.0
1,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,20.0,...,4.0,5.0,11.0,0.0,0.0,6.0,5.0,0.0,1.0,0.0
2,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,6.0,...,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,1.0,...,0.0,1.0,0.0,1.0,100.0,1.0,0.0,0.0,1.0,0.0
5,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,3.0,...,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,6.5,...,3.0,2.0,1.0,2.0,33.3,1.0,1.0,0.0,0.0,0.0
7,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,22.0,...,7.0,8.0,7.0,5.0,22.7,2.0,2.0,0.0,0.0,0.0
8,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,34.0,...,22.0,9.0,3.0,15.0,44.1,1.0,0.0,1.0,0.0,100.0
9,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,35.0,...,4.0,8.0,23.0,4.0,11.4,7.0,6.0,0.0,1.0,0.0
10,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,3.0,...,2.0,0.0,1.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
11,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,0.5,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
12,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,37.0,...,11.0,11.0,15.0,11.0,29.7,6.0,5.0,1.0,0.0,16.7
13,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,18.0,...,6.0,4.0,8.0,7.0,38.9,1.0,1.0,0.0,0.0,0.0
14,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,4.9,...,1.0,0.0,4.0,1.0,20.0,1.0,1.0,0.0,0.0,0.0
15,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,12.0,...,0.0,2.0,10.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
16,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,4.2,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,37.0,...,13.0,11.0,13.0,10.0,27.0,8.0,5.0,3.0,0.0,37.5
18,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,7.0,...,3.0,2.0,2.0,2.0,28.6,1.0,1.0,0.0,0.0,0.0
19,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,32.0,...,18.0,10.0,4.0,8.0,25.0,4.0,4.0,0.0,0.0,0.0
20,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,38.0,...,15.0,7.0,16.0,9.0,23.7,4.0,3.0,0.0,1.0,0.0
21,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,9.6,...,3.0,1.0,6.0,2.0,20.0,2.0,1.0,1.0,0.0,50.0
22,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,31.5,...,16.0,6.0,10.0,8.0,25.0,1.0,0.0,1.0,0.0,100.0
23,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,3.0,...,0.0,1.0,2.0,1.0,33.3,0.0,0.0,0.0,0.0,0.0
24,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,16.0,...,4.0,6.0,6.0,3.0,18.8,4.0,4.0,0.0,0.0,0.0
26,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,38.0,...,13.0,18.0,7.0,11.0,28.9,6.0,6.0,0.0,0.0,0.0
27,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,38.0,...,13.0,10.0,15.0,11.0,28.9,4.0,3.0,1.0,0.0,25.0
28,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,26.8,...,10.0,5.0,12.0,7.0,25.9,2.0,2.0,0.0,0.0,0.0
29,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,11.2,...,4.0,2.0,5.0,1.0,9.1,3.0,3.0,0.0,0.0,0.0
30,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,37.0,...,25.0,7.0,5.0,19.0,51.4,0.0,0.0,0.0,0.0,0.0
31,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,35.0,...,12.0,12.0,11.0,10.0,28.6,3.0,2.0,1.0,0.0,33.3
32,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,23.0,...,3.0,8.0,12.0,4.0,17.4,3.0,3.0,0.0,0.0,0.0
33,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,33.8,...,13.0,8.0,14.0,9.0,25.7,2.0,2.0,0.0,0.0,0.0
34,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,29.6,...,10.0,10.0,10.0,7.0,23.3,5.0,4.0,1.0,0.0,20.0
35,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,4.0,...,1.0,0.0,3.0,1.0,25.0,1.0,1.0,0.0,0.0,0.0
36,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,38.0,...,14.0,11.0,13.0,10.0,26.3,6.0,5.0,1.0,0.0,16.7
38,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,31.0,...,7.0,9.0,15.0,7.0,22.6,2.0,2.0,0.0,0.0,0.0
39,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,3.0,...,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
40,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,2.4,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [113]:
master_df = standard_stats_cleaned_df.copy()

In [114]:
cols_to_add = list(set(shooting_clean_df.columns).difference(set(master_df.columns)))
cols_to_add.append("Player")

In [115]:
merge_to_master = shooting_clean_df[cols_to_add]

In [116]:
master_df = pd.merge(master_df, merge_to_master, on="Player")

In [117]:
master_df[master_df["Pos"] == "GK"]

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_assists_per90,non_penalty_goals_per90,non_penalty_goals_assists_per90,goals_per_shot,shots_total,shots_on_target_pct,shots_on_target_per90,shots_on_target,goals_per_shot_on_target,shots_per90
17,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,26.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
27,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,20.0,...,0.05,0.0,0.05,0.0,0.0,0.0,0.00,0.0,0.0,0.00
32,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,1.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
45,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,6.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
47,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,1.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
49,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,3.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
55,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,6.5,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
107,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,22.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
128,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,34.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
134,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,35.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
144,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,3.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
191,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,0.5,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
205,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,37.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
208,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,18.0,...,0.06,0.0,0.06,0.0,0.0,0.0,0.00,0.0,0.0,0.00
237,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,4.9,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
238,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,12.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
243,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,4.2,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
252,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,37.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
258,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,7.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
272,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,32.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
277,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,38.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
302,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,9.6,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
310,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,31.5,...,0.03,0.0,0.03,0.0,0.0,0.0,0.00,0.0,0.0,0.00
374,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,3.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
383,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,16.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
384,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,38.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
385,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,38.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
389,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,26.8,...,0.00,0.0,0.00,0.0,1.0,100.0,0.04,1.0,0.0,0.04
392,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,11.2,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
394,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,37.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
410,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,35.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
416,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,23.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
421,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,33.8,...,0.03,0.0,0.03,0.0,0.0,0.0,0.00,0.0,0.0,0.00
435,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,29.6,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
474,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,4.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
487,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,1.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
491,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,38.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
492,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,31.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
498,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,3.0,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00
513,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,2.4,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00

In [118]:
list(set(misc_stats_clean_df.columns).difference(set(master_df.columns)))

['second_yellow_card',
 'own_goals',
 'tackles_won',
 'fouls_committed',
 'fouls_drawn',
 'offsides',
 'crosses',
 'interceptions']

In [119]:
set(misc_stats_clean_df.columns).intersection(set(master_df.columns))

{'90s_played',
 'Age',
 'Born',
 'Nation',
 'Player',
 'Pos',
 'Squad',
 'red_cards',
 'yellow_cards'}

In [120]:
cols_to_add = list(set(misc_stats_clean_df.columns).difference(set(master_df.columns)))
cols_to_add.append("Player")

In [121]:
cols_to_add

['second_yellow_card',
 'own_goals',
 'tackles_won',
 'fouls_committed',
 'fouls_drawn',
 'offsides',
 'crosses',
 'interceptions',
 'Player']

In [122]:
merge_to_master = misc_stats_clean_df[cols_to_add]

In [123]:
merge_to_master

,second_yellow_card,own_goals,tackles_won,fouls_committed,fouls_drawn,offsides,crosses,interceptions,Player
0,0.0,0.0,27.0,20.0,51.0,5.0,37.0,17.0,Brenden Aaronson
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Jerome Abbey
2,0.0,0.0,4.0,3.0,1.0,0.0,3.0,2.0,Zach Abbott
3,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,Tammy Abraham
4,0.0,0.0,8.0,2.0,9.0,2.0,1.0,12.0,Joshua Acheampong
...,...,...,...,...,...,...,...,...,...
532,0.0,0.0,2.0,51.0,21.0,10.0,3.0,4.0,Jørgen Strand Larsen
533,0.0,0.0,0.0,9.0,2.0,2.0,0.0,0.0,Marc Guiu
534,0.0,0.0,31.0,25.0,38.0,0.0,17.0,49.0,Marc Guéhi
535,0.0,0.0,12.0,9.0,17.0,0.0,14.0,9.0,Oscar Bobb
536,0.0,0.0,5.0,9.0,2.0,4.0,11.0,2.0,Tyrique George

In [124]:
master_df = pd.merge(master_df, merge_to_master, on="Player")

In [125]:
master_df[master_df["minutes"] >= 900]

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_per_shot_on_target,shots_per90,second_yellow_card,own_goals,tackles_won,fouls_committed,fouls_drawn,offsides,crosses,interceptions
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,0.24,1.73,0.0,0.0,27.0,20.0,51.0,5.0,37.0,17.0
5,Tyler Adams,us USA,MF,Bournemouth,26,1999,25.0,21.0,1772.0,19.7,...,0.33,0.51,0.0,0.0,24.0,36.0,13.0,1.0,3.0,30.0
8,Amine Adli,ma MAR,MF,Bournemouth,25,2000,31.0,10.0,1094.0,12.2,...,0.33,1.65,0.0,0.0,17.0,29.0,23.0,5.0,39.0,6.0
9,Emmanuel Agbadou,ci CIV,DF,Wolves,28,1997,14.0,12.0,1101.0,12.2,...,0.00,0.82,0.0,0.0,21.0,10.0,5.0,1.0,13.0,14.0
11,Ola Aina,ng NGA,DF,Nottingham,28,1996,18.0,18.0,1588.0,17.6,...,0.00,0.68,0.0,0.0,21.0,13.0,15.0,0.0,39.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Evann Guessand,ci CIV,MF,Crystal Palace / Aston Villa,24,2001,21.0,9.0,918.0,10.2,...,0.17,1.08,0.0,0.0,11.0,15.0,20.0,1.0,11.0,5.0
531,James Ward-Prowse,eng ENG,MF,West Ham / Burnley,30,1994,18.0,12.0,1097.0,12.2,...,0.00,0.41,0.0,0.0,6.0,8.0,13.0,0.0,74.0,21.0
532,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,0.29,1.72,0.0,0.0,2.0,51.0,21.0,10.0,3.0,4.0
534,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,0.33,0.91,0.0,0.0,31.0,25.0,38.0,0.0,17.0,49.0
535,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,0.00,1.04,0.0,0.0,12.0,9.0,17.0,0.0,14.0,9.0

In [126]:
playingtime_cleaned_df[playingtime_cleaned_df["minutes"] >= 900]

,Player,Nation,Pos,Squad,Age,Born,matches_played,minutes,minutes_per_match,minutes_pct,...,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,2449.0,66.0,71.6,...,2.0,7.0,21.0,1.0,1.19,35.0,31.0,4.0,0.15,1.17
5,Tyler Adams,us USA,MF,Bournemouth,26,1999,25.0,1773.0,71.0,51.8,...,10.0,4.0,28.0,1.0,1.52,25.0,28.0,-3.0,-0.15,-0.53
8,Amine Adli,ma MAR,MF,Bournemouth,25,2000,31.0,1093.0,35.0,32.0,...,2.0,21.0,17.0,6.0,1.48,18.0,17.0,1.0,0.08,-0.03
9,Emmanuel Agbadou,ci CIV,DF,Wolves,28,1997,14.0,1101.0,79.0,32.2,...,11.0,2.0,38.0,4.0,0.14,6.0,27.0,-21.0,-1.72,-0.94
12,Ola Aina,ng NGA,DF,Nottingham,28,1996,18.0,1588.0,88.0,46.4,...,15.0,0.0,0.0,0.0,1.39,27.0,19.0,8.0,0.45,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,Evann Guessand,ci CIV,MF,Crystal Palace / Aston Villa,24,2001,21.0,918.0,43.7,0.3,...,1.0,12.0,76.5,5.0,3.15,17.0,15.0,2.0,0.20,0.79
669,James Ward-Prowse,eng ENG,MF,West Ham / Burnley,30,1994,18.0,1097.0,60.9,0.3,...,6.0,6.0,182.8,2.0,1.14,8.0,27.0,-19.0,-1.60,-2.09
670,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,2307.0,64.1,0.7,...,10.0,10.0,230.7,0.0,1.50,18.0,41.0,-23.0,-0.90,-0.39
672,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,3150.0,90.0,0.9,...,35.0,0.0,inf,0.0,3.68,53.0,35.0,18.0,0.50,0.72
673,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,1039.0,45.2,0.3,...,2.0,12.0,86.6,4.0,2.96,17.0,12.0,5.0,0.40,-0.04

In [127]:
miss_players = list(set(playingtime_cleaned_df["Player"]).difference(set(master_df["Player"])))

In [128]:
miss_players_df = playingtime_cleaned_df[playingtime_cleaned_df["Player"].isin(miss_players)]

In [129]:
numerical_df = miss_players_df.select_dtypes(include="number")
numerical_df.describe()

,matches_played,minutes,minutes_per_match,minutes_pct,90s_played,starts,minutes_per_start,complete_matches,sub_appearances,minutes_per_sub,unused_sub,points_per_match,goals_scored_on_pitch,goals_allowed_on_pitch,plus_minus,plus_minus_per90,plus_minus_net_per90
count,140.0,0.0,0.0,0.0,0.0,140.0,0.0,140.0,140.0,140.0,140.000000,0.0,0.0,0.0,0.0,0.0,140.0
mean,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,4.371429,NaN,NaN,NaN,NaN,NaN,0.0
std,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,6.430976,NaN,NaN,NaN,NaN,NaN,0.0
min,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,1.000000,NaN,NaN,NaN,NaN,NaN,0.0
25%,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,1.000000,NaN,NaN,NaN,NaN,NaN,0.0
50%,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,2.000000,NaN,NaN,NaN,NaN,NaN,0.0
75%,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,5.000000,NaN,NaN,NaN,NaN,NaN,0.0
max,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,38.000000,NaN,NaN,NaN,NaN,NaN,0.0

In [130]:
index_to_del = miss_players_df.index

In [131]:
playingtime_cleaned_df = playingtime_cleaned_df.drop(index=index_to_del)

In [132]:
cols_to_add = list(set(playingtime_cleaned_df.columns).difference(set(master_df.columns)))
cols_to_add.append("Player")

In [133]:
cols_to_add

['goals_allowed_on_pitch',
 'complete_matches',
 'minutes_per_start',
 'plus_minus_net_per90',
 'minutes_per_match',
 'sub_appearances',
 'plus_minus_per90',
 'plus_minus',
 'goals_scored_on_pitch',
 'minutes_pct',
 'minutes_per_sub',
 'points_per_match',
 'unused_sub',
 'Player']

In [134]:
merge_to_master = playingtime_cleaned_df[cols_to_add]

In [135]:
master_df = pd.merge(master_df, merge_to_master, on="Player")

In [136]:
master_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,plus_minus_net_per90,minutes_per_match,sub_appearances,plus_minus_per90,plus_minus,goals_scored_on_pitch,minutes_pct,minutes_per_sub,points_per_match,unused_sub
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,1.17,66.0,7.0,0.15,4.0,35.0,71.6,21.0,1.19,1.0
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,0.2,...,1.08,17.0,1.0,0.00,0.0,0.0,0.5,17.0,1.00,1.0
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,1.8,...,-1.07,55.0,1.0,-1.10,-2.0,2.0,4.8,45.0,1.00,13.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,3.2,...,-1.57,24.0,10.0,-1.26,-4.0,4.0,8.4,14.0,1.00,2.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,7.4,...,-0.70,39.0,9.0,-0.41,-3.0,10.0,19.5,11.0,1.18,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,-0.39,64.1,10.0,-0.90,-23.0,18.0,0.7,230.7,1.50,0.0
531,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,1.0,272.0,3.1,...,1.50,27.2,9.0,1.30,4.0,7.0,0.1,30.2,3.13,18.0
532,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,0.72,90.0,0.0,0.50,18.0,53.0,0.9,inf,3.68,0.0
533,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,-0.04,45.2,12.0,0.40,5.0,17.0,0.3,86.6,2.96,4.0
534,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,1.0,363.0,4.0,...,0.98,24.2,14.0,0.20,1.0,10.0,0.1,25.9,1.73,6.0

Filtering out Players that haven't played more than 900 mins this season

In [137]:
master_df = master_df[master_df["minutes"] >= 900]

In [139]:
master_df[master_df.isna().any(axis=1)]

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,plus_minus_net_per90,minutes_per_match,sub_appearances,plus_minus_per90,plus_minus,goals_scored_on_pitch,minutes_pct,minutes_per_sub,points_per_match,unused_sub
522,Antoine Semenyo,gh GHA,"MF, FW",Bournemouth / Manchester City,25,2000,37.0,37.0,3195.0,35.5,...,-1.31,86.4,0.0,0.2,7.0,59.0,0.9,inf,3.31,0.0
523,Brennan Johnson,wls WAL,"MF, FW",Tottenham / Crystal Palace,24,2001,34.0,19.0,1722.0,19.2,...,0.67,50.6,15.0,-0.2,-4.0,20.0,0.5,114.8,2.38,3.0
524,Douglas Luiz,br BRA,MF,Aston Villa / Nottingham,27,1998,21.0,12.0,919.0,10.2,...,-2.57,43.8,9.0,-0.9,-9.0,6.0,0.3,102.1,1.86,8.0
525,Eberechi Eze,eng ENG,"MF, FW",Crystal Palace / Arsenal,27,1998,33.0,22.0,1895.0,21.0,...,0.24,57.4,11.0,1.1,23.0,37.0,0.6,172.3,3.09,4.0
526,Evann Guessand,ci CIV,MF,Crystal Palace / Aston Villa,24,2001,21.0,9.0,918.0,10.2,...,0.79,43.7,12.0,0.2,2.0,17.0,0.3,76.5,3.15,5.0
529,James Ward-Prowse,eng ENG,MF,West Ham / Burnley,30,1994,18.0,12.0,1097.0,12.2,...,-2.09,60.9,6.0,-1.6,-19.0,8.0,0.3,182.8,1.14,2.0
530,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,-0.39,64.1,10.0,-0.9,-23.0,18.0,0.7,230.7,1.50,0.0
532,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,0.72,90.0,0.0,0.5,18.0,53.0,0.9,inf,3.68,0.0
533,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,-0.04,45.2,12.0,0.4,5.0,17.0,0.3,86.6,2.96,4.0

In [140]:
master_df[master_df.isna().any(axis=1)]["Player"].to_list()

['Antoine Semenyo',
 'Brennan Johnson',
 'Douglas Luiz',
 'Eberechi Eze',
 'Evann Guessand',
 'James Ward-Prowse',
 'Jørgen Strand Larsen',
 'Marc Guéhi',
 'Oscar Bobb']

In [141]:
missing_na_players_list = ['Antoine Semenyo',
 'Brennan Johnson',
 'Douglas Luiz',
 'Eberechi Eze',
 'Evann Guessand',
 'James Ward-Prowse',
 'Jørgen Strand Larsen',
 'Marc Guéhi',
 'Oscar Bobb']

In [142]:
["yellow_cards", "red_cards", "plus_minus_net_per90", "points_per_match"]

['yellow_cards', 'red_cards', 'plus_minus_net_per90', 'points_per_match']

In [143]:
misc_stats_clean_df[["Player", "yellow_cards", "red_cards"]]

                   Player  yellow_cards  red_cards
0        Brenden Aaronson           3.0        0.0
1            Jerome Abbey           0.0        0.0
2             Zach Abbott           0.0        0.0
3           Tammy Abraham           0.0        0.0
4       Joshua Acheampong           1.0        0.0
..                    ...           ...        ...
532  Jørgen Strand Larsen           4.0        0.0
533             Marc Guiu           1.0        0.0
534            Marc Guéhi           6.0        0.0
535            Oscar Bobb           1.0        0.0
536        Tyrique George           2.0        0.0

[537 rows x 3 columns]

In [144]:
misc_stats_agg.loc[misc_stats_agg["Player"].isin(missing_na_players_list), ["Player", "yellow_cards", "red_cards"]]

                  Player  yellow_cards  red_cards
1        Antoine Semenyo           7.0        0.0
2        Brennan Johnson           6.0        0.0
3           Douglas Luiz           3.0        0.0
4           Eberechi Eze           1.0        0.0
5         Evann Guessand           0.0        0.0
8      James Ward-Prowse           1.0        0.0
9   Jørgen Strand Larsen           4.0        0.0
11            Marc Guéhi           6.0        0.0
12            Oscar Bobb           1.0        0.0

In [145]:
master_df.loc[master_df["Player"].isin(missing_na_players_list), ["Player", "yellow_cards", "red_cards"]]

                   Player  yellow_cards  red_cards
522       Antoine Semenyo           NaN        NaN
523       Brennan Johnson           NaN        NaN
524          Douglas Luiz           NaN        NaN
525          Eberechi Eze           NaN        NaN
526        Evann Guessand           NaN        NaN
529     James Ward-Prowse           NaN        NaN
530  Jørgen Strand Larsen           NaN        NaN
532            Marc Guéhi           NaN        NaN
533            Oscar Bobb           NaN        NaN

In [146]:
fill_cols = ["yellow_cards", "red_cards"]

master_df = master_df.set_index("Player")
misc_lookup = misc_stats_agg.set_index("Player")[fill_cols]

master_df.update(misc_lookup)

In [147]:
fill_cols = ["points_per_match", "plus_minus_net_per90"]

In [151]:
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 51 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Player                           340 non-null    str
 1   Nation                           340 non-null    str
 2   Pos                              340 non-null    str
 3   Squad                            340 non-null    str
 4   Age                              340 non-null    str
 5   Born                             340 non-null    str
 6   matches_played                   340 non-null    float64
 7   starts                           340 non-null    float64
 8   minutes                          340 non-null    float64
 9   90s_played                       340 non-null    float64
 10  goals                            340 non-null    float64
 11  assists                          340 non-null    float64
 12  goals_assists                    340 non-null    float64
 13  non_penalty_goals                340 non-null    float64
 14  penalty_kicks_made               340 non-null    float64
 15  penalty_kicks_attempted          340 non-null    float64
 16  yellow_cards                     340 non-null    float64
 17  red_cards                        340 non-null    float64
 18  goals_per90                      340 non-null    float64
 19  assists_per90                    340 non-null    float64
 20  goals_assists_per90              340 non-null    float64
 21  non_penalty_goals_per90          340 non-null    float64
 22  non_penalty_goals_assists_per90  340 non-null    float64
 23  goals_per_shot                   340 non-null    float64
 24  shots_total                      340 non-null    float64
 25  shots_on_target_pct              340 non-null    float64
 26  shots_on_target_per90            340 non-null    float64
 27  shots_on_target                  340 non-null    float64
 28  goals_per_shot_on_target         340 non-null    float64
 29  shots_per90                      340 non-null    float64
 30  second_yellow_card               340 non-null    float64
 31  own_goals                        340 non-null    float64
 32  tackles_won                      340 non-null    float64
 33  fouls_committed                  340 non-null    float64
 34  fouls_drawn                      340 non-null    float64
 35  offsides                         340 non-null    float64
 36  crosses                          340 non-null    float64
 37  interceptions                    340 non-null    float64
 38  goals_allowed_on_pitch           340 non-null    float64
 39  complete_matches                 340 non-null    float64
 40  minutes_per_start                340 non-null    float64
 41  plus_minus_net_per90             340 non-null    float64
 42  minutes_per_match                340 non-null    float64
 43  sub_appearances                  340 non-null    float64
 44  plus_minus_per90                 340 non-null    float64
 45  plus_minus                       340 non-null    float64
 46  goals_scored_on_pitch            340 non-null    float64
 47  minutes_pct                      340 non-null    float64
 48  minutes_per_sub                  340 non-null    float64
 49  points_per_match                 340 non-null    float64
 50  unused_sub                       340 non-null    float64
dtypes: float64(45), str(6)
memory usage: 148.6 KB

In [149]:
master_df = master_df.reset_index()

In [150]:
master_df.to_parquet(ROOT / "data" / "processed" / "master_dataset.parquet")