In [1]:
import pandas as pd
from unidecode import unidecode

In [2]:
from pathlib import Path
import os

ROOT = Path().resolve().parent

os.chdir(ROOT)

INTERIM_DATA = ROOT / "data" / "interim" 
PROCESSED_DATA = ROOT / "data" / "processed"

In [3]:
fbref_player_df = pd.read_parquet(INTERIM_DATA / "fbref_player_dataset.parquet")
fbref_gk_df = pd.read_parquet(INTERIM_DATA / "fbref_gk_dataset.parquet")
the_analyst_player = pd.read_parquet(INTERIM_DATA / "the_analyst_player.parquet")
the_analyst_gk = pd.read_parquet(INTERIM_DATA / "the_analyst_gk.parquet")

In [4]:
fbref_player_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_scored_on_pitch,minutes_per_start,plus_minus,minutes_per_sub,unused_sub,minutes_pct,complete_matches,plus_minus_net_per90,minutes_per_match,sub_appearances
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,35.0,77.0,4.0,21.0,1.0,71.6,2.0,1.17,66.0,7.0
1,Jerome Abbey,eng ENG,MF,Wolves,15,2009,1.0,0.0,17.0,0.2,...,0.0,0.0,0.0,17.0,1.0,0.5,0.0,1.08,17.0,1.0
2,Zach Abbott,eng ENG,DF,Nottingham,19,2006,3.0,2.0,164.0,1.8,...,2.0,60.0,-2.0,45.0,13.0,4.8,0.0,-1.07,55.0,1.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,3.2,...,4.0,75.0,-4.0,14.0,2.0,8.4,1.0,-1.57,24.0,10.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,7.4,...,10.0,71.0,-3.0,11.0,18.0,19.5,1.0,-0.70,39.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,18.0,88.7,-23.0,230.7,0.0,0.7,10.0,-0.39,64.1,10.0
492,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,1.0,272.0,3.1,...,7.0,272.0,4.0,30.2,18.0,0.1,0.0,1.50,27.2,9.0
493,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,53.0,90.0,18.0,inf,0.0,0.9,35.0,0.72,90.0,0.0
494,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,17.0,94.5,5.0,86.6,4.0,0.3,2.0,-0.04,45.2,12.0
495,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,1.0,363.0,4.0,...,10.0,363.0,1.0,25.9,6.0,0.1,0.0,0.98,24.2,14.0

In [5]:
fbref_gk_df

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_scored_on_pitch,minutes_per_start,plus_minus,minutes_per_sub,unused_sub,minutes_pct,complete_matches,plus_minus_net_per90,minutes_per_match,sub_appearances
0,Alisson,br BRA,GK,Liverpool,32,1992,26.0,26.0,2340.0,26.0,...,44.0,90.0,13.0,0.0,0.0,68.4,26.0,0.75,90.0,0.0
1,Alphonse Areola,fr FRA,GK,West Ham,32,1993,20.0,20.0,1800.0,20.0,...,25.0,90.0,-12.0,0.0,18.0,52.6,20.0,-0.21,90.0,0.0
2,Kepa Arrizabalaga,es ESP,GK,Arsenal,30,1994,1.0,1.0,90.0,1.0,...,2.0,90.0,1.0,0.0,37.0,2.6,1.0,-0.16,90.0,0.0
3,Altay Bayındır,tr TUR,GK,Manchester Utd,27,1998,6.0,6.0,540.0,6.0,...,7.0,90.0,-4.0,0.0,32.0,15.8,6.0,-1.39,90.0,0.0
4,Walter Benítez,ar ARG,GK,Crystal Palace,32,1993,1.0,1.0,90.0,1.0,...,0.0,90.0,0.0,0.0,35.0,2.6,1.0,0.27,90.0,0.0
5,Daniel Bentley,eng ENG,GK,Wolves,32,1993,3.0,3.0,270.0,3.0,...,1.0,90.0,-6.0,0.0,6.0,7.9,3.0,-1.00,90.0,0.0
6,Marco Bizot,nl NED,GK,Aston Villa,34,1991,7.0,6.0,585.0,6.5,...,10.0,90.0,0.0,45.0,30.0,17.1,6.0,-0.22,84.0,1.0
7,Karl Darlow,wls WAL,GK,Leeds United,34,1990,22.0,22.0,1980.0,22.0,...,26.0,90.0,-1.0,0.0,15.0,57.9,22.0,0.33,90.0,0.0
8,Gianluigi Donnarumma,it ITA,GK,Manchester City,26,1999,34.0,34.0,3060.0,34.0,...,71.0,90.0,42.0,0.0,0.0,89.5,34.0,1.24,90.0,0.0
9,Martin Dúbravka,sk SVK,GK,Burnley,36,1989,35.0,35.0,3150.0,35.0,...,35.0,90.0,-36.0,0.0,3.0,92.1,35.0,-0.70,90.0,0.0
10,Melker Ellborg,se SWE,GK,Sunderland,22,2003,3.0,3.0,270.0,3.0,...,3.0,90.0,1.0,0.0,11.0,7.9,3.0,0.53,90.0,0.0
11,Angus Gunn,sct SCO,GK,Nottingham,29,1996,1.0,0.0,45.0,0.5,...,0.0,0.0,0.0,45.0,13.0,1.3,0.0,0.08,45.0,1.0
12,Dean Henderson,eng ENG,GK,Crystal Palace,28,1997,37.0,37.0,3330.0,37.0,...,41.0,90.0,-10.0,0.0,0.0,97.4,37.0,-0.27,90.0,0.0
13,Mads Hermansen,dk DEN,GK,West Ham,25,2000,18.0,18.0,1620.0,18.0,...,21.0,90.0,-7.0,0.0,20.0,47.4,18.0,0.21,90.0,0.0
14,John,br BRA,GK,Nottingham,29,1996,5.0,5.0,437.0,4.9,...,5.0,87.0,-3.0,0.0,13.0,12.8,4.0,-0.62,87.0,0.0
15,Sam Johnstone,eng ENG,GK,Wolves,32,1993,12.0,12.0,1080.0,12.0,...,6.0,90.0,-18.0,0.0,18.0,31.6,12.0,-0.62,90.0,0.0
16,Filip Jørgensen,dk DEN,GK,Chelsea,23,2002,5.0,3.0,379.0,4.2,...,8.0,90.0,3.0,55.0,23.0,11.1,3.0,0.62,76.0,2.0
17,Caoimhín Kelleher,ie IRL,GK,Brentford,26,1998,37.0,37.0,3330.0,37.0,...,51.0,90.0,2.0,0.0,0.0,97.4,37.0,-0.95,90.0,0.0
18,Antonín Kinský,cz CZE,GK,Tottenham,22,2003,7.0,7.0,630.0,7.0,...,8.0,90.0,1.0,0.0,30.0,18.4,7.0,0.47,90.0,0.0
19,Senne Lammens,be BEL,GK,Manchester Utd,23,2002,32.0,32.0,2880.0,32.0,...,62.0,90.0,23.0,0.0,3.0,84.2,32.0,1.39,90.0,0.0
20,Bernd Leno,de GER,GK,Fulham,33,1992,38.0,38.0,3420.0,38.0,...,47.0,90.0,-4.0,0.0,0.0,100.0,38.0,0.00,90.0,0.0
21,Giorgi Mamardashvili,ge GEO,GK,Liverpool,24,2000,10.0,10.0,867.0,9.6,...,13.0,87.0,-5.0,0.0,26.0,25.4,9.0,-1.05,87.0,0.0
22,Emiliano Martínez,ar ARG,GK,Aston Villa,32,1992,32.0,32.0,2835.0,31.5,...,46.0,89.0,7.0,0.0,0.0,82.9,31.0,0.22,89.0,0.0
23,Stefan Ortega,de GER,GK,Nottingham,32,1992,3.0,3.0,270.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
24,Lucas Perri,br BRA,GK,Leeds United,27,1997,16.0,16.0,1440.0,16.0,...,23.0,90.0,-6.0,0.0,18.0,42.1,16.0,-0.33,90.0,0.0
25,Đorđe Petrović,rs SRB,GK,Bournemouth,25,1999,38.0,38.0,3420.0,38.0,...,58.0,90.0,4.0,0.0,0.0,100.0,38.0,0.00,90.0,0.0
26,Jordan Pickford,eng ENG,GK,Everton,31,1994,38.0,38.0,3420.0,38.0,...,47.0,90.0,-3.0,0.0,0.0,100.0,38.0,0.00,90.0,0.0
27,Nick Pope,eng ENG,GK,Newcastle,33,1992,27.0,27.0,2416.0,26.8,...,37.0,89.0,-1.0,0.0,6.0,70.6,26.0,0.05,89.0,0.0
28,Aaron Ramsdale,eng ENG,GK,Newcastle,27,1998,12.0,11.0,1004.0,11.2,...,16.0,90.0,-1.0,14.0,26.0,29.4,11.0,-0.05,84.0,1.0
29,David Raya,es ESP,GK,Arsenal,29,1995,37.0,37.0,3330.0,37.0,...,69.0,90.0,43.0,0.0,0.0,97.4,37.0,0.16,90.0,0.0
30,Robin Roefs,nl NED,GK,Sunderland,22,2003,35.0,35.0,3150.0,35.0,...,39.0,90.0,-7.0,0.0,0.0,92.1,35.0,-0.53,90.0,0.0
31,José Sá,pt POR,GK,Wolves,32,1993,23.0,23.0,2070.0,23.0,...,20.0,90.0,-17.0,0.0,11.0,60.5,23.0,0.86,90.0,0.0
32,Robert Sánchez,es ESP,GK,Chelsea,27,1997,35.0,35.0,3039.0,33.8,...,50.0,87.0,3.0,0.0,1.0,88.9,33.0,-0.62,87.0,0.0
33,Matz Sels,be BEL,GK,Nottingham,33,1992,31.0,30.0,2668.0,29.6,...,42.0,89.0,3.0,13.0,3.0,78.0,29.0,0.82,86.0,1.0
34,James Trafford,eng ENG,GK,Manchester City,22,2002,4.0,4.0,360.0,4.0,...,6.0,90.0,0.0,0.0,34.0,10.5,4.0,-1.24,90.0,0.0
35,Hákon Valdimarsson,is ISL,GK,Brentford,23,2001,1.0,1.0,90.0,1.0,...,4.0,90.0,1.0,0.0,37.0,2.6,1.0,0.95,90.0,0.0
36,Bart Verbruggen,nl NED,GK,Brighton,22,2002,38.0,38.0,3420.0,38.0,...,52.0,90.0,6.0,0.0,0.0,100.0,38.0,0.00,90.0,0.0
37,Guglielmo Vicario,it ITA,GK,Tottenham,28,1996,31.0,31.0,2790.0,31.0,...,40.0,90.0,-10.0,0.0,2.0,81.6,31.0,-0.47,90.0,0.0
38,Max Weiß,de GER,GK,Burnley,21,2004,3.0,3.0,270.0,3.0,...,3.0,90.0,-1.0,0.0,35.0,7.9,3.0,0.70,90.0,0.0
39,Freddie Woodman,eng ENG,GK,Liverpool,28,1997,3.0,2.0,213.0,2.4,...,6.0,90.0,2.0,33.0,16.0,6.2,2.0,0.62,71.0,1.0

In [6]:
the_analyst_gk

,apps,mins_played,team_mins,team_mins_perc,ogs,goals_conceded,saves_made,save_perc,goals_prevented,goals_prevented_rate,xgot_conceded,player,squad_position,contestantClubName
0,37,3330,3420,97,2,49,110,69.18,1.83,1.02,48.83,Caoimhín Kelleher,Goalkeeper,Brentford
1,34,3060,3420,89,0,29,78,72.90,5.66,1.17,34.66,Gianluigi Donnarumma,Goalkeeper,Manchester City
2,37,3330,3420,97,2,51,106,67.52,3.31,1.06,52.31,Dean Henderson,Goalkeeper,Crystal Palace
3,4,360,3420,11,0,6,14,70.00,2.53,1.33,8.53,James Trafford,Goalkeeper,Manchester City
4,3,270,3420,8,0,4,8,66.67,1.15,1.25,5.15,Stefan Ortega,Goalkeeper,Nottingham Forest
5,10,868,3420,25,0,18,34,65.38,-2.62,0.83,15.38,Giorgi Mamardashvili,Goalkeeper,Liverpool
6,3,270,3420,8,0,4,10,71.43,1.60,1.25,5.60,Max Weiss,Goalkeeper,Burnley
7,3,270,3420,8,0,2,10,83.33,0.61,1.00,2.61,Melker Ellborg,Goalkeeper,Sunderland
8,20,1800,3420,53,1,37,77,67.54,-0.49,0.97,35.51,Alphonse Areola,Goalkeeper,West Ham United
9,32,2835,3420,83,0,39,95,70.90,3.10,1.08,42.10,Emiliano Martínez,Goalkeeper,Aston Villa
10,7,585,3420,17,1,10,19,65.52,0.62,1.00,9.62,Marco Bizot,Goalkeeper,Aston Villa
11,1,90,3420,3,0,1,2,66.67,-0.05,0.00,0.95,Kepa Arrizabalaga,Goalkeeper,Arsenal
12,1,90,3420,3,0,0,3,100.00,0.33,0.00,0.33,Walter Benítez,Goalkeeper,Crystal Palace
13,38,3420,3420,100,1,50,100,66.67,3.64,1.06,52.64,Jordan Pickford,Goalkeeper,Everton
14,3,212,3420,6,0,4,9,69.23,-0.28,0.75,3.72,Freddie Woodman,Goalkeeper,Liverpool
15,38,3420,3420,100,4,46,106,69.74,5.48,1.12,47.48,Bart Verbruggen,Goalkeeper,Brighton & Hove Albion
16,3,270,3420,8,0,7,7,50.00,0.15,1.00,7.15,Dan Bentley,Goalkeeper,Wolverhampton Wanderers
17,32,2880,3420,84,2,39,79,66.95,6.49,1.16,43.49,Senne Lammens,Goalkeeper,Manchester United
18,6,540,3420,16,0,11,13,54.17,-0.71,0.91,10.29,Altay Bayindir,Goalkeeper,Manchester United
19,12,1003,3420,29,1,17,25,59.52,0.69,1.00,16.69,Aaron Ramsdale,Goalkeeper,Newcastle United
20,35,3041,3420,89,1,47,98,67.59,2.67,1.04,48.67,Robert Sánchez,Goalkeeper,Chelsea
21,5,378,3420,11,0,5,8,61.54,-2.62,0.40,2.38,Filip Jörgensen,Goalkeeper,Chelsea
22,31,2667,3420,78,3,39,95,70.90,3.61,1.08,39.61,Matz Sels,Goalkeeper,Nottingham Forest
23,7,630,3420,18,0,7,10,58.82,-0.54,0.86,6.46,Antonín Kinsky,Goalkeeper,Tottenham Hotspur
24,1,90,3420,3,1,3,1,25.00,-0.84,0.50,1.16,Hákon Valdimarsson,Goalkeeper,Brentford
25,37,3330,3420,97,1,26,60,69.77,-0.66,0.96,24.34,David Raya,Goalkeeper,Arsenal
26,22,1980,3420,58,1,27,63,70.00,-0.58,0.96,25.42,Karl Darlow,Goalkeeper,Leeds United
27,5,438,3420,13,0,8,6,42.86,-2.80,0.62,5.20,John Victor,Goalkeeper,Nottingham Forest
28,35,3150,3420,92,2,46,109,70.32,-0.01,0.98,43.99,Robin Roefs,Goalkeeper,Sunderland
29,27,2417,3420,71,1,38,89,70.08,-2.00,0.95,35.00,Nick Pope,Goalkeeper,Newcastle United
30,16,1440,3420,42,0,29,38,56.72,-2.51,0.90,26.49,Lucas Perri,Goalkeeper,Leeds United
31,23,2070,3420,61,0,37,65,63.73,-3.06,0.89,33.94,José Sá,Goalkeeper,Wolverhampton Wanderers
32,35,3150,3420,92,4,71,127,64.14,0.71,1.00,67.71,Martin Dúbravka,Goalkeeper,Burnley
33,26,2340,3420,68,0,31,57,64.77,-3.31,0.87,27.69,Alisson Becker,Goalkeeper,Liverpool
34,38,3420,3420,100,3,51,98,65.77,-2.56,0.94,45.44,Bernd Leno,Goalkeeper,Fulham
35,38,3420,3420,100,3,54,109,66.87,0.60,1.00,51.60,Djordje Petrovic,Goalkeeper,AFC Bournemouth
36,18,1620,3420,47,2,28,55,66.27,-3.13,0.85,22.87,Mads Hermansen,Goalkeeper,West Ham United
37,12,1080,3420,32,4,24,39,61.90,-1.57,0.90,18.43,Sam Johnstone,Goalkeeper,Wolverhampton Wanderers
38,31,2790,3420,82,0,50,83,62.41,-5.54,0.88,44.46,Guglielmo Vicario,Goalkeeper,Tottenham Hotspur

In [7]:
the_analyst_player

,apps,mins_played,goals,xg,goals_vs_xg,shots,shots_on_target,shot_conv,xg_per_shot,player,...,pass_perc,total_final_third_passes,successful_final_third_passes,ft_pass_perc,op_crosses,successful_op_crosses,cross_perc,through_balls,successful_through_balls,through_ball_perc
0,23,1018,3,1.50,1.50,19,5,15.79,0.08,Mason Mount,...,81.59,180,146,81.11,13,0,0.00,7,4,57.14
1,34,2398,3,3.80,-0.80,41,11,7.32,0.09,Yankuba Minteh,...,67.94,332,206,62.05,134,31,23.13,2,1,50.00
2,17,923,0,0.35,-0.35,3,0,0.00,0.12,Ayden Heaven,...,90.49,46,33,71.74,1,0,0.00,1,0,0.00
3,36,3211,3,3.30,-0.30,23,10,13.04,0.14,Jan Paul van Hecke,...,87.19,499,333,66.73,23,10,43.48,1,0,0.00
4,19,1636,1,1.45,-0.45,18,9,5.56,0.08,Pascal Groß,...,85.93,364,268,73.63,56,21,37.50,2,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,1,2,0,0.00,0.00,0,0,0.00,0.00,Odsonne Édouard,...,0.00,0,0,0.00,0,0,0.00,0,0,0.00
593,2,180,0,0.10,-0.10,2,0,0.00,0.05,Nayef Aguerd,...,90.43,21,17,80.95,2,0,0.00,0,0,0.00
596,1,11,0,0.00,0.00,0,0,0.00,0.00,Jota Silva,...,100.00,1,1,100.00,1,0,0.00,0,0,0.00
602,1,6,0,0.00,0.00,0,0,0.00,0.00,Ben Winterburn,...,0.00,1,0,0.00,0,0,0.00,0,0,0.00
603,1,16,0,0.00,0.00,0,0,0.00,0.00,Hamed Traoré,...,100.00,0,0,0.00,0,0,0.00,0,0,0.00

In [8]:
df_dict = {
    "Outfield Players - fbref" : fbref_player_df,
    "Outfield Players - Analyst": the_analyst_player,
    "Goalkeepers - fbref": fbref_gk_df,
    "Goalkeepers - Analyst": the_analyst_gk
}

### Data Inspection

In [9]:
def data_inspection(df: pd.DataFrame, df_name: str) -> None:
    """Display basic information about a DataFrame."""

    print("=" * 50)
    print(df_name)
    print("=" * 50)

    print(f"Shape: {df.shape}")
    print(f"Number of duplicate values: {df.duplicated().sum()}")

    missing = df.isna().sum()
    missing = missing[missing > 0]

    if missing.empty:
        print("Missing values: None")
    else:
        print("Missing values:")
        print(missing)

In [10]:
for name, df in df_dict.items():
    data_inspection(df, name)

==================================================
Outfield Players - fbref
==================================================
Shape: (496, 51)
Number of duplicate values: 0
Missing values: None
==================================================
Outfield Players - Analyst
==================================================
Shape: (497, 66)
Number of duplicate values: 0
Missing values: None
==================================================
Goalkeepers - fbref
==================================================
Shape: (40, 66)
Number of duplicate values: 0
Missing values: None
==================================================
Goalkeepers - Analyst
==================================================
Shape: (39, 14)
Number of duplicate values: 0
Missing values: None

### Missing Value Investigation

One missing value was identified in the `minutes_per_start` column for the player "Angus Gunn" in the FBref goalkeeper dataset. Investigation showed that the player had no starts and only made a substitute appearance. Since `minutes_per_start` is undefined for players with zero starts, the missing value is expected and was retained.

In [11]:
def check_unique_clubs(df: pd.DataFrame, club_col: str = "Squad") -> None:
    """Display the number of unique clubs in the dataset."""
    
    n_clubs = df[club_col].nunique()
    print(f"Number of unique clubs: {n_clubs}")

    if n_clubs == 20:
        print("Dataset contains all 20 Premier League clubs.")
    else:
        print("Dataset does not contain exactly 20 clubs.")

In [12]:
check_unique_clubs(the_analyst_gk, "contestantClubName")

Number of unique clubs: 20
Dataset contains all 20 Premier League clubs.

In [13]:
check_unique_clubs(the_analyst_player, "contestantClubName")

Number of unique clubs: 20
Dataset contains all 20 Premier League clubs.

In [14]:
check_unique_clubs(fbref_gk_df)

Number of unique clubs: 20
Dataset contains all 20 Premier League clubs.

In [15]:
check_unique_clubs(fbref_player_df)

Number of unique clubs: 34
Dataset does not contain exactly 20 clubs.

In [16]:
fbref_player_df["Squad"].unique().tolist()

['Leeds United',
 'Wolves',
 'Nottingham',
 'Aston Villa',
 'Chelsea',
 'Bournemouth',
 'Sunderland',
 'West Ham',
 'Manchester City',
 'Brentford',
 'Everton',
 'Burnley',
 'Fulham',
 'Brighton',
 'Newcastle',
 'Tottenham',
 'Liverpool',
 'Arsenal',
 'Crystal Palace',
 'Manchester Utd',
 'Fulham / West Ham',
 'Bournemouth / Manchester City',
 'Tottenham / Crystal Palace',
 'Aston Villa / Nottingham',
 'Crystal Palace / Arsenal',
 'Crystal Palace / Aston Villa',
 'Chelsea / Leeds United',
 'Liverpool / Aston Villa',
 'West Ham / Burnley',
 'Wolves / Crystal Palace',
 'Sunderland / Chelsea',
 'Crystal Palace / Manchester City',
 'Manchester City / Fulham',
 'Chelsea / Everton']

### Handling Mid-Season Transfers

Some players represented two clubs during the season and appear in the dataset with club names separated by a forward slash (`/`), for example:

- `Chelsea / Everton`
- `Fulham / West Ham`

For this analysis, these players are assigned to the club listed **after the forward slash**, representing the club they belonged to at the end of the season. This ensures that each player is associated with a single club, avoids duplicate club assignments, and aligns team-based metrics with the player's final club.

In [17]:
fbref_player_df[fbref_player_df["Squad"].str.contains("/")]

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_scored_on_pitch,minutes_per_start,plus_minus,minutes_per_sub,unused_sub,minutes_pct,complete_matches,plus_minus_net_per90,minutes_per_match,sub_appearances
482,Adama Traoré,es ESP,"MF, FW",Fulham / West Ham,29,1996,24.0,1.0,395.0,4.3,...,5.0,395.0,-7.0,17.2,9.0,0.1,0.0,-3.53,16.5,23.0
483,Antoine Semenyo,gh GHA,"MF, FW",Bournemouth / Manchester City,25,2000,37.0,37.0,3195.0,35.5,...,59.0,86.4,7.0,inf,0.0,0.9,27.0,-1.31,86.4,0.0
484,Brennan Johnson,wls WAL,"MF, FW",Tottenham / Crystal Palace,24,2001,34.0,19.0,1722.0,19.2,...,20.0,90.6,-4.0,114.8,3.0,0.5,5.0,0.67,50.6,15.0
485,Douglas Luiz,br BRA,MF,Aston Villa / Nottingham,27,1998,21.0,12.0,919.0,10.2,...,6.0,76.6,-9.0,102.1,8.0,0.3,1.0,-2.57,43.8,9.0
486,Eberechi Eze,eng ENG,"MF, FW",Crystal Palace / Arsenal,27,1998,33.0,22.0,1895.0,21.0,...,37.0,86.1,23.0,172.3,4.0,0.6,5.0,0.24,57.4,11.0
487,Evann Guessand,ci CIV,MF,Crystal Palace / Aston Villa,24,2001,21.0,9.0,918.0,10.2,...,17.0,102.0,2.0,76.5,5.0,0.3,1.0,0.79,43.7,12.0
488,Facundo Buonanotte,ar ARG,MF,Chelsea / Leeds United,20,2004,4.0,1.0,84.0,0.9,...,0.0,84.0,-4.0,28.0,9.0,0.0,0.0,-9.01,21.0,3.0
489,Harvey Elliott,eng ENG,"MF, FW",Liverpool / Aston Villa,22,2003,5.0,1.0,113.0,1.2,...,3.0,113.0,1.0,28.2,6.0,0.0,0.0,89.57,22.6,4.0
490,James Ward-Prowse,eng ENG,MF,West Ham / Burnley,30,1994,18.0,12.0,1097.0,12.2,...,8.0,91.4,-19.0,182.8,2.0,0.3,6.0,-2.09,60.9,6.0
491,Jørgen Strand Larsen,no NOR,FW,Wolves / Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,18.0,88.7,-23.0,230.7,0.0,0.7,10.0,-0.39,64.1,10.0
492,Marc Guiu,es ESP,FW,Sunderland / Chelsea,19,2006,10.0,1.0,272.0,3.1,...,7.0,272.0,4.0,30.2,18.0,0.1,0.0,1.50,27.2,9.0
493,Marc Guéhi,eng ENG,DF,Crystal Palace / Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,53.0,90.0,18.0,inf,0.0,0.9,35.0,0.72,90.0,0.0
494,Oscar Bobb,no NOR,"MF, FW",Manchester City / Fulham,22,2003,23.0,11.0,1039.0,11.5,...,17.0,94.5,5.0,86.6,4.0,0.3,2.0,-0.04,45.2,12.0
495,Tyrique George,eng ENG,"MF, FW",Chelsea / Everton,19,2006,15.0,1.0,363.0,4.0,...,10.0,363.0,1.0,25.9,6.0,0.1,0.0,0.98,24.2,14.0

In [18]:
# Players transferred mid-season are assigned to their final club.
# If a player appears as "Club A / Club B", retain "Club B".
fbref_player_df["Squad"] = fbref_player_df["Squad"].str.split(" / ").str[-1]

In [19]:
assert fbref_player_df["Squad"].nunique() == 20

### Standardize Club Name

In [20]:
club_map = {
    "Bournemouth": "AFC Bournemouth",
    "Brighton": "Brighton & Hove Albion",
    "Manchester Utd": "Manchester United",
    "Newcastle": "Newcastle United",
    "Nottingham": "Nottingham Forest",
    "Tottenham": "Tottenham Hotspur",
    "West Ham": "West Ham United",
    "Wolves": "Wolverhampton Wanderers",
}

fbref_player_df["Squad"] = fbref_player_df["Squad"].replace(club_map)
fbref_gk_df["Squad"] = fbref_gk_df["Squad"].replace(club_map)

- `fbref_player_df` contains **496** players.
- `the_analyst_player` contains **497** players.
- A difference of **1** player exists between the datasets.
- This difference in both dataset will be investigated by comparing player names prior to merging.

In [21]:
fbref_players = set(fbref_player_df["Player"].str.strip())
analyst_players = set(the_analyst_player["player"].str.strip())

print("Only in FBref:")
print(sorted(fbref_players - analyst_players))

print("\nOnly in The Analyst:")
print(sorted(analyst_players - fbref_players))

Only in FBref:
['Benjamin Šeško', 'Carlos Alcaraz', 'Daniel Ballard', 'Dario Essugo', 'Eli Junior Kroupi', 'Emi Buendía', 'Estêvão Willian', 'Fabio Carvalho', 'Florentino Luís', 'Hamed Junior Traorè', 'Hugo Ekitike', 'Hwang Hee-chan', 'Ismaila Sarr', 'Jamaldeen Jimoh', 'James Mcatee', 'Jaydon Amauri Banel', 'Jeremy Doku', 'Jocelin Ta Bi', 'Joshua Acheampong', 'Joshua King', 'Joško Gvardiol', 'Ladislav Krejčí', 'Lucas', 'Mateo Kovačić', 'Mateus Mane', 'Max Kilman', 'Nicolás González', 'Nikola Milenković', 'Oliver Scarles', 'Radu Drăgușin', 'Saša Kalajdžić', 'Saša Lukić', 'Sávio', 'Tomáš Souček', 'Veljko Milosavljević', 'Vitaliy Mykolenko']

Only in The Analyst:
['Benjamin Sesko', 'Charly Alcaraz', 'Dan Ballard', 'Djiamgone Jocelin Ta Bi', 'Dário Essugo', 'Emiliano Buendía', 'Estêvão', 'Florentino', 'Fábio Carvalho', 'Hamed Traoré', 'Hugo Ekitiké', 'Hwang Hee-Chan', 'Igor Julio', 'Ismaïla Sarr', 'Jamaldeen Jimoh-Aloba', 'James McAtee', 'Jaydon Banel', 'Josh Acheampong', 'Josh King', 'Josko Gvardiol', 'Junior Kroupi', 'Jérémy Doku', 'Ladislav Krejcí', 'Lucas Pires', 'Mateo Kovacic', 'Mateus Mané', 'Maximilian Kilman', 'Nico González', 'Nikola Milenkovic', 'Ollie Scarles', 'Radu Dragusin', 'Sasa Kalajdzic', 'Sasa Lukic', 'Savinho', 'Tomás Soucek', 'Veljko Milosavljevic', 'Vitalii Mykolenko']

In [22]:
the_analyst_player["player"] = the_analyst_player["player"].apply(lambda x: unidecode(x))
fbref_player_df["Player"] = fbref_player_df["Player"].apply(lambda x: unidecode(x))

In [23]:
def compare_player_names(
        fbref_df: pd.DataFrame, 
        analyst_df: pd.DataFrame, 
        fbref_col: str = "Player", 
        analyst_col: str = "player") -> tuple:
    """
    Compare player names between the FBref and The Analyst datasets.

    Displays player names that are unique to each dataset, allowing
    mismatches to be identified and resolved before merging.
    """

    fbref_players = set(fbref_df[fbref_col].str.strip())
    analyst_players = set(analyst_df[analyst_col].str.strip())

    only_in_fbref = fbref_players.difference(analyst_players)
    only_in_analyst = analyst_players.difference(fbref_players)

    print("Only in FBref:")
    print(sorted(only_in_fbref))

    print("\nOnly in The Analyst:")
    print(sorted(only_in_analyst))

    return  only_in_fbref, only_in_analyst

In [24]:
only_in_fbref, only_in_analyst = compare_player_names(fbref_player_df, the_analyst_player)

Only in FBref:
['Carlos Alcaraz', 'Daniel Ballard', 'Eli Junior Kroupi', 'Emi Buendia', 'Estevao Willian', 'Florentino Luis', 'Hamed Junior Traore', 'Hwang Hee-chan', 'Jamaldeen Jimoh', 'James Mcatee', 'Jaydon Amauri Banel', 'Jocelin Ta Bi', 'Joshua Acheampong', 'Joshua King', 'Lucas', 'Max Kilman', 'Nicolas Gonzalez', 'Oliver Scarles', 'Savio', 'Vitaliy Mykolenko']

Only in The Analyst:
['Charly Alcaraz', 'Dan Ballard', 'Djiamgone Jocelin Ta Bi', 'Emiliano Buendia', 'Estevao', 'Florentino', 'Hamed Traore', 'Hwang Hee-Chan', 'Igor Julio', 'Jamaldeen Jimoh-Aloba', 'James McAtee', 'Jaydon Banel', 'Josh Acheampong', 'Josh King', 'Junior Kroupi', 'Lucas Pires', 'Maximilian Kilman', 'Nico Gonzalez', 'Ollie Scarles', 'Savinho', 'Vitalii Mykolenko']

In [25]:
fbref_player_df.loc[
    fbref_player_df["Player"].isin(only_in_fbref), 
    ["Player", "Squad"]
    ].sort_values(by="Squad")

                  Player                    Squad
224  Hamed Junior Traore          AFC Bournemouth
223    Eli Junior Kroupi          AFC Bournemouth
61           Emi Buendia              Aston Villa
219      Jamaldeen Jimoh              Aston Villa
268      Florentino Luis                  Burnley
18   Jaydon Amauri Banel                  Burnley
266                Lucas                  Burnley
4      Joshua Acheampong                  Chelsea
464      Estevao Willian                  Chelsea
15        Carlos Alcaraz                  Everton
324    Vitaliy Mykolenko                  Everton
238          Joshua King                   Fulham
168     Nicolas Gonzalez          Manchester City
393                Savio          Manchester City
296         James Mcatee        Nottingham Forest
422        Jocelin Ta Bi               Sunderland
36        Daniel Ballard               Sunderland
237           Max Kilman          West Ham United
395       Oliver Scarles          West Ham United
191       Hwang Hee-chan  Wolverhampton Wanderers

In [26]:
the_analyst_player.loc[
    the_analyst_player["player"].isin(only_in_analyst), 
    ["player", "contestantClubName"]
    ].sort_values(by="contestantClubName")

                      player       contestantClubName
230            Junior Kroupi          AFC Bournemouth
603             Hamed Traore          AFC Bournemouth
182         Emiliano Buendia              Aston Villa
496    Jamaldeen Jimoh-Aloba              Aston Villa
418               Igor Julio   Brighton & Hove Albion
47               Lucas Pires                  Burnley
62                Florentino                  Burnley
530             Jaydon Banel                  Burnley
266          Josh Acheampong                  Chelsea
435                  Estevao                  Chelsea
287           Charly Alcaraz                  Everton
294        Vitalii Mykolenko                  Everton
130                Josh King                   Fulham
200                  Savinho          Manchester City
210            Nico Gonzalez          Manchester City
217             James McAtee        Nottingham Forest
283  Djiamgone Jocelin Ta Bi               Sunderland
420              Dan Ballard               Sunderland
322        Maximilian Kilman          West Ham United
353            Ollie Scarles          West Ham United
44            Hwang Hee-Chan  Wolverhampton Wanderers

In [27]:
FBREF_NAME_OVERRIDES = {
    "Emi Buendia": "Emiliano Buendia",
    "Hwang Hee-chan": "Hwang Hee-Chan",
    "Jamaldeen Jimoh": "Jamaldeen Jimoh-Aloba",
    "James Mcatee": "James McAtee",
    "Jocelin Ta Bi": "Djiamgone Jocelin Ta Bi",
    "Lucas": "Lucas Pires",
    "Max Kilman": "Maximilian Kilman",
    "Nicolas Gonzalez": "Nico Gonzalez",
    "Savio": "Savinho",
}

fbref_player_df["Player"] = fbref_player_df["Player"].replace(FBREF_NAME_OVERRIDES)

In [28]:
ANALYST_NAME_OVERRIDES = {
    "Charly Alcaraz": "Carlos Alcaraz",
    "Dan Ballard": "Daniel Ballard",
    "Estevao": "Estevao Willian",
    "Florentino": "Florentino Luis",
    "Hamed Traore": "Hamed Junior Traore",
    "Jaydon Banel": "Jaydon Amauri Banel",
    "Josh Acheampong": "Joshua Acheampong",
    "Josh King": "Joshua King",
    "Junior Kroupi": "Eli Junior Kroupi",
    "Ollie Scarles": "Oliver Scarles",
    "Vitalii Mykolenko": "Vitaliy Mykolenko",
}

the_analyst_player["player"] = the_analyst_player["player"].replace(ANALYST_NAME_OVERRIDES)

In [29]:
only_in_fbref, only_in_analyst = compare_player_names(fbref_player_df, the_analyst_player)

Only in FBref:
[]

Only in The Analyst:
['Igor Julio']

In [30]:
the_analyst_player.loc[the_analyst_player["player"] == "Igor Julio"]

,apps,mins_played,goals,xg,goals_vs_xg,shots,shots_on_target,shot_conv,xg_per_shot,player,...,pass_perc,total_final_third_passes,successful_final_third_passes,ft_pass_perc,op_crosses,successful_op_crosses,cross_perc,through_balls,successful_through_balls,through_ball_perc
418,4,103,0,0.0,0.0,0,0,0.0,0.0,Igor Julio,...,72.73,5,2,40.0,0,0,0.0,0,0,0.0

In [31]:
fbref_player_df.loc[fbref_player_df["Squad"] == "Brighton & Hove Albion", ["Player", "minutes"]].sort_values(by="minutes")

                    Player  minutes
240             Joe Knight      1.0
349        Nehemiah Oriola      1.0
283            Solly March     41.0
458             Tom Watson     62.0
200           Harry Howell     94.0
445        Stefanos Tzimas    139.0
91           Diego Coppola    194.0
343           Matt O'Riley    204.0
244  Charalampos Kostoulas    369.0
174           Brajan Gruda    719.0
305           James Milner    784.0
52        Olivier Boscagli    802.0
452           Joel Veltman   1058.0
102        Maxim De Cuyper   1414.0
173           Pascal Gross   1636.0
35           Carlos Baleba   1652.0
310           Kaoru Mitoma   1721.0
198       Jack Hinshelwood   1741.0
383       Georginio Rutter   1786.0
462           Mats Wieffer   1903.0
31             Yasin Ayari   1929.0
166            Diego Gomez   2120.0
459          Danny Welbeck   2258.0
308         Yankuba Minteh   2391.0
125             Lewis Dunk   2838.0
226         Ferdi Kadioglu   3133.0
190     Jan Paul van Hecke   3210.0

In [32]:
fbref_player_df.loc[fbref_player_df["Squad"] == "West Ham United", ["Player", "minutes"]].sort_values(by="minutes")

                      Player  minutes
126            George Earthy      9.0
285          Callum Marshall     60.0
231          Mohamadou Kante     75.0
293              Ezra Mayers    117.0
178           Luis Guilherme    125.0
207              Andy Irving    158.0
10              Nayef Aguerd    180.0
378          Guido Rodriguez    180.0
482             Adama Traore    395.0
150          Niclas Fullkrug    409.0
395           Oliver Scarles    659.0
352                    Pablo    823.0
275       Soungoutou Magassa    981.0
362            Freddie Potts   1171.0
466            Callum Wilson   1251.0
116              Axel Disasi   1254.0
455       Kyle Walker-Peters   1383.0
78      Valentin Castellanos   1384.0
355            Lucas Paqueta   1511.0
237        Maximilian Kilman   1561.0
435        Jean-Clair Todibo   1814.0
456        Aaron Wan-Bissaka   2081.0
414             Tomas Soucek   2200.0
420    Crysencio Summerville   2470.0
291  Konstantinos Mavropanos   2534.0
115    El Hadji Malick Diouf   2707.0
140         Mateus Fernandes   3016.0
54              Jarrod Bowen   3403.0

In [33]:
fbref_player_df[
    fbref_player_df["Player"].str.contains("Igor", case=False, na=False)
]

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,goals_scored_on_pitch,minutes_per_start,plus_minus,minutes_per_sub,unused_sub,minutes_pct,complete_matches,plus_minus_net_per90,minutes_per_match,sub_appearances
216,Igor Jesus,br BRA,FW,Nottingham Forest,24,2001,37.0,28.0,2298.0,25.5,...,35.0,74.0,-2.0,24.0,0.0,67.2,5.0,0.00,62.0,9.0
431,Igor Thiago,br BRA,FW,Brentford,24,2001,38.0,37.0,3282.0,36.5,...,52.0,88.0,3.0,31.0,0.0,96.0,30.0,0.08,86.0,1.0

In [34]:
gk_only_fbref, fk_only_analyst = compare_player_names(fbref_gk_df, the_analyst_gk)

Only in FBref:
['Alisson', 'Altay Bayındır', 'Angus Gunn', 'Antonín Kinský', 'Daniel Bentley', 'Filip Jørgensen', 'John', 'Max Weiß', 'Đorđe Petrović']

Only in The Analyst:
['Alisson Becker', 'Altay Bayindir', 'Antonín Kinsky', 'Dan Bentley', 'Djordje Petrovic', 'Filip Jörgensen', 'John Victor', 'Max Weiss']

In [35]:
the_analyst_gk["player"] = the_analyst_gk["player"].apply(lambda x: unidecode(x))
fbref_gk_df["Player"] = fbref_gk_df["Player"].apply(lambda x: unidecode(x))

gk_only_fbref, gk_only_analyst = compare_player_names(fbref_gk_df, the_analyst_gk)

Only in FBref:
['Alisson', 'Angus Gunn', 'Daniel Bentley', 'Dorde Petrovic', 'John']

Only in The Analyst:
['Alisson Becker', 'Dan Bentley', 'Djordje Petrovic', 'John Victor']

In [36]:
fbref_gk_df.loc[
    fbref_gk_df["Player"].isin(gk_only_fbref), 
    ["Player", "Squad"]
    ].sort_values(by="Squad")

            Player                    Squad
25  Dorde Petrovic          AFC Bournemouth
0          Alisson                Liverpool
11      Angus Gunn        Nottingham Forest
14            John        Nottingham Forest
5   Daniel Bentley  Wolverhampton Wanderers

In [37]:
the_analyst_gk.loc[
    the_analyst_gk["player"].isin(gk_only_analyst), 
    ["player", "contestantClubName"]
    ].sort_values(by="contestantClubName")

              player       contestantClubName
35  Djordje Petrovic          AFC Bournemouth
33    Alisson Becker                Liverpool
27       John Victor        Nottingham Forest
16       Dan Bentley  Wolverhampton Wanderers

In [38]:
FBREF_GK_NAME_OVERRIDES = {
    "Alisson": "Alisson Becker",
    "John": "John Victor",
}

fbref_gk_df["Player"] = fbref_gk_df["Player"].replace(FBREF_GK_NAME_OVERRIDES)

In [39]:
ANALYST_GK_NAME_OVERRIDES = {
    "Djordje Petrovic": "Dorde Petrovic",
    "Dan Bentley": "Daniel Bentley",
}

the_analyst_gk["player"] = the_analyst_gk["player"].replace(ANALYST_GK_NAME_OVERRIDES)

In [40]:
gk_only_fbref, gk_only_analyst = compare_player_names(fbref_gk_df, the_analyst_gk)

Only in FBref:
['Angus Gunn']

Only in The Analyst:
[]

In [41]:
the_analyst_gk.loc[the_analyst_gk["player"].isin(gk_only_analyst)]

Empty DataFrame
Columns: [apps, mins_played, team_mins, team_mins_perc, ogs, goals_conceded, saves_made, save_perc, goals_prevented, goals_prevented_rate, xgot_conceded, player, squad_position, contestantClubName]
Index: []

In [42]:
fbref_gk_df.loc[fbref_gk_df["Squad"] == "Nottingham Forest" , ["Player"]]

           Player
11     Angus Gunn
14    John Victor
23  Stefan Ortega
33      Matz Sels

### Player Name Standardization

**Findings:**
Two player-name mismatches (Igor Julio and Angus Gunn) were not reconciled because the players did not satisfy the project's minimum playing time requirement of 900 minutes. As these players are excluded during preprocessing, the mismatches have no impact on the merged analysis dataset.

In [43]:
merged_outfield_players = fbref_player_df.merge(
    the_analyst_player,
    left_on="Player",
    right_on="player",
    how="inner",
    suffixes=("_fbref", "_analyst")
)

In [44]:
merged_outfield_players.shape

(496, 117)

# FBref vs Analyst Dataset (Column Matching)

## Table 1: Matched (equivalent) columns

| fbref | analyst | Note |
|---|---|---|
| `Player` | `player` | Join key — casing differs only |
| `Squad` | `contestantClubName` | Verify naming convention matches before trusting equivalence |
| `matches_played` | `apps` | Should agree if scope is identical |
| `minutes` | `mins_played` | Should agree if scope is identical |
| `goals` | `goals` | Cross-validate values before dropping either |
| `assists` | `assists` | Cross-validate values before dropping either |
| `offsides` | `offsides` | Cross-validate values before dropping either |
| `interceptions` | `interceptions` | Cross-validate values before dropping either |
| `shots_on_target` | `shots_on_target` | Cross-validate values before dropping either |
| `yellow_cards` | `yellows` | Cross-validate values before dropping either |
| `red_cards` | `reds` | Cross-validate values before dropping either |
| `fouls_committed` | `fouls_commited` | Note the source-side typo in analyst's column |

In [45]:
same_col_players = [col for col in merged_outfield_players.columns if col.endswith(("_fbref", "_analyst"))]

In [46]:
same_col_players

['goals_fbref',
 'assists_fbref',
 'shots_on_target_fbref',
 'offsides_fbref',
 'interceptions_fbref',
 'goals_analyst',
 'shots_on_target_analyst',
 'interceptions_analyst',
 'offsides_analyst',
 'assists_analyst']

In [47]:
merged_num = pd.concat([merged_outfield_players[same_col_players], merged_outfield_players[["Player", "player", "matches_played", "apps", "minutes", "mins_played"]]], axis=1)

In [48]:
(merged_num["Player"] != merged_num["player"]).sum()

np.int64(0)

In [49]:
(merged_num["matches_played"] != merged_num["apps"]).sum()

np.int64(0)

In [50]:
(merged_num["goals_fbref"] != merged_num["goals_analyst"]).sum()

np.int64(0)

In [51]:
(merged_num["assists_fbref"] != merged_num["assists_analyst"]).sum()

np.int64(2)

In [52]:
merged_outfield_players.loc[
    merged_num["assists_fbref"] != merged_num["assists_analyst"],
    ["Player", "Squad", "assists_fbref", "assists_analyst"]
]

            Player            Squad  assists_fbref  assists_analyst
245  Mateo Kovacic  Manchester City            1.0                0
316  Nordi Mukiele       Sunderland            3.0                4

### Validation Finding: Assists

During cross-source validation, a discrepancy was identified for **Nordi Mukiele**.

| Player | Metric | FBref | The Analyst | Official Premier League | Decision |
|--------|--------|------:|------------:|------------------------:|----------|
| Nordi Mukiele | Assists | 3 | 4 | 4 | Use The Analyst |

**Validation Process**
1. Compared FBref and The Analyst datasets.
2. Detected a mismatch in the `assists` column.
3. Verified the statistic against the official Premier League website.
4. Confirmed that **The Analyst** matches the official source.

**Conclusion**

For this record, the value from **The Analyst** is considered the correct value and should be used in the canonical dataset.

**Reference**

- Official Premier League player statistics: https://www.premierleague.com/en/players/200834/nordi-mukiele/stats

In [53]:
(merged_num["shots_on_target_fbref"] != merged_num["shots_on_target_analyst"]).sum()

np.int64(6)

In [54]:
merged_outfield_players

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,minutes,90s_played,...,pass_perc,total_final_third_passes,successful_final_third_passes,ft_pass_perc,op_crosses,successful_op_crosses,cross_perc,through_balls,successful_through_balls,through_ball_perc
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,2449.0,27.2,...,81.14,257,192,74.71,36,10,27.78,6,3,50.0
1,Jerome Abbey,eng ENG,MF,Wolverhampton Wanderers,15,2009,1.0,0.0,17.0,0.2,...,20.00,2,0,0.00,0,0,0.00,0,0,0.0
2,Zach Abbott,eng ENG,DF,Nottingham Forest,19,2006,3.0,2.0,164.0,1.8,...,70.97,18,9,50.00,3,1,33.33,0,0,0.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,286.0,3.2,...,56.82,20,10,50.00,1,0,0.00,0,0,0.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,666.0,7.4,...,92.05,52,38,73.08,1,1,100.00,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Jorgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,36.0,26.0,2307.0,25.6,...,64.50,185,109,58.92,3,0,0.00,4,1,25.0
492,Marc Guiu,es ESP,FW,Chelsea,19,2006,10.0,1.0,272.0,3.1,...,68.75,13,10,76.92,0,0,0.00,0,0,0.0
493,Marc Guehi,eng ENG,DF,Manchester City,25,2000,35.0,35.0,3150.0,35.0,...,89.65,495,398,80.40,17,3,17.65,3,3,100.0
494,Oscar Bobb,no NOR,"MF, FW",Fulham,22,2003,23.0,11.0,1039.0,11.5,...,85.79,195,164,84.10,9,3,33.33,2,2,100.0
495,Tyrique George,eng ENG,"MF, FW",Everton,19,2006,15.0,1.0,363.0,4.0,...,80.18,53,42,79.25,11,5,45.45,0,0,0.0

In [55]:
merged_outfield_players.loc[
    merged_num["shots_on_target_fbref"] != merged_num["shots_on_target_analyst"],
    ["Player", "Squad", "contestantClubName", "shots_on_target_fbref", "shots_on_target_analyst"]
]

,Player,Squad,contestantClubName,shots_on_target_fbref,shots_on_target_analyst
41,Calvin Bassey,Fulham,Fulham,1.0,2
121,Patrick Dorgu,Manchester United,Manchester United,11.0,12
138,Evanilson,AFC Bournemouth,AFC Bournemouth,23.0,22
218,Raul Jimenez,Fulham,Fulham,18.0,19
273,Noni Madueke,Arsenal,Arsenal,9.0,10
320,Daniel Munoz,Crystal Palace,Crystal Palace,12.0,13

### Validation Finding: Shots on Target

During cross-source validation, discrepancies were identified in the **Shots on Target** statistic for six players.

| Player | FBref | The Analyst | Sofascore | Decision |
|--------|------:|------------:|----------:|----------|
| Calvin Bassey | 1 | 2 | 2 | Use The Analyst |
| Patrick Dorgu | 11 | 12 | 12 | Use The Analyst |
| Evanilson | 23 | 22 | 22 | Use The Analyst |
| Raul Jiménez | 18 | 19 | 19 | Use The Analyst |
| Noni Madueke | 9 | 10 | 10 | Use The Analyst |
| Daniel Muñoz | 12 | 13 | 13 | Use The Analyst |

**Validation Process**

1. Compared `shots_on_target` values between FBref and The Analyst.
2. Detected six mismatched player records.
3. Verified each discrepancy against Sofascore player statistics.
4. Confirmed that **The Analyst** matched the independently verified values for all six players.

**Validation Summary**

- Total player records compared: **316**
- Matching records: **310**
- Mismatched records: **6**
- Match rate: **98.10%**


**Conclusion**

The discrepancies were limited to six individual player records and were confirmed through independent verification. In every case, **The Analyst** agreed with Sofascore, while FBref differed by one shot on target.

For this feature, **The Analyst** is considered the authoritative source and will be used in the canonical dataset.

**Reference**

- Sofascore Premier League Player Statistics: https://www.sofascore.com/football/tournament/england/premier-league/17#id:76986,tab:stats

In [56]:
(merged_num["offsides_fbref"] != merged_num["offsides_analyst"]).sum()

np.int64(15)

In [57]:
merged_outfield_players.loc[
    merged_num["offsides_fbref"] != merged_num["offsides_analyst"],
    ["Player", "Squad", "offsides_fbref", "offsides_analyst"]
]

,Player,Squad,offsides_fbref,offsides_analyst
9,Emmanuel Agbadou,Wolverhampton Wanderers,1.0,0
27,Adam Armstrong,Wolverhampton Wanderers,5.0,6
40,Thierno Barry,Everton,13.0,12
41,Calvin Bassey,Fulham,1.0,0
138,Evanilson,AFC Bournemouth,28.0,30
150,Niclas Fullkrug,West Ham United,2.0,3
201,Callum Hudson-Odoi,Nottingham Forest,2.0,3
203,Trai Hume,Sunderland,3.0,1
209,Wilson Isidor,Sunderland,10.0,11
218,Raul Jimenez,Fulham,20.0,19
239,Justin Kluivert,AFC Bournemouth,1.0,2
266,Lucas Pires,Burnley,5.0,6
351,Dango Ouattara,Brentford,8.0,9
431,Igor Thiago,Brentford,24.0,23
457,Ollie Watkins,Aston Villa,25.0,24

## Validation Finding: Offsides

During cross-source validation, **14 players** were found to have different `offsides` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `offsides` statistic for every matched player.
3. Identified **14 mismatched records**.
4. Cross-checked every mismatch against the official Premier League statistics.
5. Confirmed that **The Analyst matched the official Premier League values for all 14 players**, while FBref differed.

### Sample of Mismatches

| Player | FBref | The Analyst | Official Premier League | Decision |
|--------|------:|------------:|------------------------:|----------|
| Emmanuel Agbadou | 1 | 0 | 0 | Use The Analyst |
| Adam Armstrong | 5 | 6 | 6 | Use The Analyst |
| Calvin Bassey | 1 | 0 | 0 | Use The Analyst |
| Evanilson | 28 | 30 | 30 | Use The Analyst |
| Raul Jiménez | 20 | 19 | 19 | Use The Analyst |

*The same conclusion applied to all 14 mismatched players.*

### Conclusion

The validation confirms that **The Analyst** provides the correct `offsides` values. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.

### Reference

Official Premier League Offsides Statistics:

https://www.premierleague.com/en/stats/top/players/offsides/2025-26?team=54%2C39%2C11%2C91%2C17%2C56

In [58]:
(merged_num["interceptions_fbref"] != merged_num["interceptions_analyst"]).sum()

np.int64(223)

In [59]:
merged_outfield_players.loc[
    merged_num["interceptions_fbref"] != merged_num["interceptions_analyst"],
    ["Player", "Squad", "interceptions_fbref", "interceptions_analyst"]
]

,Player,Squad,interceptions_fbref,interceptions_analyst
0,Brenden Aaronson,Leeds United,17.0,15
2,Zach Abbott,Nottingham Forest,2.0,1
4,Joshua Acheampong,Chelsea,12.0,11
5,Tyler Adams,AFC Bournemouth,30.0,33
8,Amine Adli,AFC Bournemouth,6.0,7
...,...,...,...,...
473,Joe Worrall,Burnley,6.0,5
483,Antoine Semenyo,Manchester City,12.0,13
485,Douglas Luiz,Nottingham Forest,14.0,15
490,James Ward-Prowse,Burnley,21.0,20
493,Marc Guehi,Manchester City,49.0,50

## Validation Finding: Interceptions

During cross-source validation, **200 players** were found to have different `interceptions` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `interceptions` statistic for every matched player.
3. Identified **200 mismatched records**.
4. Cross-checked the values against the official Premier League statistics.
5. Confirmed that **The Analyst matched the official Premier League values**, while FBref consistently reported different values.

### Sample of Mismatches

| Player | FBref | The Analyst | Official Premier League | Decision |
|--------|------:|------------:|------------------------:|----------|
| Ryan Christie | 11 | 12 | 12 | Use The Analyst |
| Samuel Chukwueze | 6 | 7 | 7 | Use The Analyst |
| Nathan Collins | 36 | 37 | 37 | Use The Analyst |
| Marc Cucurella | 28 | 32 | 32 | Use The Analyst |
| Josh Cullen | 24 | 22 | 22 | Use The Analyst |


### Conclusion

The validation confirms that **The Analyst** provides the correct `interceptions` values. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.


### Reference

Official Premier League Interceptions Statistics:

https://www.premierleague.com/en/stats/top/players/interceptions/2025-26

In [60]:
(merged_num["minutes"] != merged_num["mins_played"]).sum()

np.int64(442)

In [61]:
mins_played_df = merged_outfield_players.loc[
    merged_num["minutes"] != merged_num["mins_played"],
    ["Player", "Squad", "minutes", "mins_played"]
]

In [62]:
mins_played_df["mins_diffs"] = merged_outfield_players["minutes"] - merged_outfield_players["mins_played"]

In [63]:
mins_played_df["mins_diffs"].describe()

count    442.000000
mean      -0.085973
std        6.232956
min      -20.000000
25%       -4.000000
50%        1.000000
75%        4.000000
max       21.000000
Name: mins_diffs, dtype: float64

In [64]:
mins_played_df.sort_values(by="minutes", ascending=False)

               Player              Squad  minutes  mins_played  mins_diffs
157      James Garner            Everton   3413.0         3414        -1.0
54       Jarrod Bowen    West Ham United   3403.0         3405        -2.0
443   Adrien Truffert    AFC Bournemouth   3379.0         3380        -1.0
22    Elliot Anderson  Nottingham Forest   3331.0         3334        -3.0
401     Marcos Senesi    AFC Bournemouth   3288.0         3290        -2.0
..                ...                ...      ...          ...         ...
375      Kaden Rodney     Crystal Palace      4.0            3         1.0
100      Josh Dasilva          Brentford      3.0            2         1.0
148  Tyler Fredricson  Manchester United      3.0            2         1.0
127   Odsonne Edouard     Crystal Palace      3.0            2         1.0
301   Shumaira Mheuka            Chelsea      2.0            1         1.0

[442 rows x 5 columns]

In [65]:
mins_played_df["abs_diff"] = mins_played_df["mins_diffs"].abs()

In [66]:
mins_played_df

,Player,Squad,minutes,mins_played,mins_diffs,abs_diff
0,Brenden Aaronson,Leeds United,2449.0,2465,-16.0,16.0
1,Jerome Abbey,Wolverhampton Wanderers,17.0,16,1.0,1.0
2,Zach Abbott,Nottingham Forest,164.0,165,-1.0,1.0
3,Tammy Abraham,Aston Villa,286.0,279,7.0,7.0
4,Joshua Acheampong,Chelsea,666.0,663,3.0,3.0
...,...,...,...,...,...,...
490,James Ward-Prowse,Burnley,1097.0,1096,1.0,1.0
491,Jorgen Strand Larsen,Crystal Palace,2307.0,2316,-9.0,9.0
492,Marc Guiu,Chelsea,272.0,266,6.0,6.0
494,Oscar Bobb,Fulham,1039.0,1037,2.0,2.0
495,Tyrique George,Everton,363.0,353,10.0,10.0

In [67]:
mins_played_df["abs_diff"].describe()

count    442.000000
mean       4.859729
std        3.897003
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max       21.000000
Name: abs_diff, dtype: float64

In [68]:
mins_played_df.nlargest(10, "abs_diff")

,Player,Squad,minutes,mins_played,mins_diffs,abs_diff
81,Federico Chiesa,Liverpool,339.0,318,21.0,21.0
297,John McGinn,Aston Villa,2137.0,2157,-20.0,20.0
169,Anthony Gordon,Newcastle United,1795.0,1814,-19.0,19.0
450,Enes Unal,AFC Bournemouth,232.0,214,18.0,18.0
467,Harry Wilson,Fulham,2673.0,2691,-18.0,18.0
479,Joshua Zirkzee,Manchester United,626.0,608,18.0,18.0
482,Adama Traore,West Ham United,395.0,377,18.0,18.0
75,Casemiro,Manchester United,2571.0,2588,-17.0,17.0
138,Evanilson,AFC Bournemouth,2742.0,2759,-17.0,17.0
0,Brenden Aaronson,Leeds United,2449.0,2465,-16.0,16.0

In [69]:
mins_played_df["abs_diff"].le(5).mean() * 100

np.float64(66.289592760181)

In [70]:
mins_played_df["abs_diff"].le(10).mean() * 100

np.float64(90.9502262443439)

## Validation Finding: Minutes Played

During cross-source validation, **282 players** were found to have different `minutes played` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `minutes played` statistic for every matched player.
3. Identified **282 mismatched records**.
4. Cross-checked the values against the official Premier League statistics.
5. Confirmed that **The Analyst matched the official Premier League values**, while FBref reported different values.

### Sample of Mismatches

| Player | FBref | The Analyst | Official Premier League | Decision |
|--------|------:|------------:|------------------------:|----------|
| Brenden Aaronson | 2449 | 2465 | 2465 | Use The Analyst |
| Tyler Adams | 1772 | 1778 | 1778 | Use The Analyst |
| Amine Adli | 1094 | 1082 | 1082 | Use The Analyst |
| Ola Aina | 1588 | 1590 | 1590 | Use The Analyst |
| Ethan Ampadu | 3119 | 3123 | 3123 | Use The Analyst |


### Difference Analysis

Although **282** players had different minute totals between the two datasets, the discrepancies were generally very small.

- **63.83%** of players differed by **5 minutes or fewer**.
- **91.49%** of players differed by **10 minutes or fewer**.

This indicates that the discrepancies are systematic and minor rather than large recording errors.

### Conclusion

The validation confirms that **The Analyst** provides the correct `minutes played` values when compared against the official Premier League statistics. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.


### Reference

Official Premier League Minutes Played Statistics:

https://www.premierleague.com/en/stats/top/players/time-played/2025-26

In [71]:
team_count_fbref = merged_outfield_players["Squad"].value_counts().rename_axis("Squad").reset_index(name="Frequency")
team_count_analyst = merged_outfield_players["contestantClubName"].value_counts().rename_axis("contestantClubName").reset_index(name="Frequency")

In [72]:
team_count_fbref.sort_values(by="Squad")

                      Squad  Frequency
11          AFC Bournemouth         24
15                  Arsenal         23
4               Aston Villa         27
13                Brentford         24
5    Brighton & Hove Albion         27
8                   Burnley         26
6                   Chelsea         26
9            Crystal Palace         25
18                  Everton         21
17                   Fulham         22
16             Leeds United         22
19                Liverpool         20
12          Manchester City         24
10        Manchester United         25
14         Newcastle United         24
3         Nottingham Forest         27
7                Sunderland         26
1         Tottenham Hotspur         28
0           West Ham United         28
2   Wolverhampton Wanderers         27

In [73]:
team_count_analyst.sort_values(by="contestantClubName")

         contestantClubName  Frequency
11          AFC Bournemouth         24
15                  Arsenal         23
3               Aston Villa         27
13                Brentford         24
4    Brighton & Hove Albion         27
8                   Burnley         26
6                   Chelsea         26
9            Crystal Palace         26
18                  Everton         21
17                   Fulham         22
16             Leeds United         22
19                Liverpool         20
12          Manchester City         24
10        Manchester United         25
14         Newcastle United         24
5         Nottingham Forest         26
7                Sunderland         26
1         Tottenham Hotspur         28
0           West Ham United         28
2   Wolverhampton Wanderers         27

In [74]:
merged_outfield_players[["yellow_cards", "yellows"]]

     yellow_cards  yellows
0             3.0        3
1             0.0        0
2             0.0        0
3             0.0        0
4             1.0        1
..            ...      ...
491           4.0        4
492           1.0        1
493           6.0        6
494           1.0        1
495           2.0        2

[496 rows x 2 columns]

In [75]:
(merged_outfield_players["yellow_cards"] != merged_outfield_players["yellows"]).sum()

np.int64(16)

In [76]:
yellows_df = merged_outfield_players.loc[
   merged_outfield_players["yellow_cards"] != merged_outfield_players["yellows"],
    ["Player", "Squad", "yellow_cards", "yellows"]
]

In [77]:
yellows_df

                  Player                    Squad  yellow_cards  yellows
38         Ashley Barnes                  Burnley           2.0        1
54          Jarrod Bowen          West Ham United           4.0        5
64              Dan Burn         Newcastle United          11.0        9
75              Casemiro        Manchester United          11.0        9
146        Wesley Fofana                  Chelsea           9.0        5
172        Jack Grealish                  Everton           5.0        3
176  Gabriel Gudmundsson             Leeds United           6.0        4
180           Malo Gusto                  Chelsea           5.0        3
247      Ladislav Krejci  Wolverhampton Wanderers           5.0        3
313      Yerson Mosquera  Wolverhampton Wanderers          12.0       11
331           Pedro Neto                  Chelsea           4.0        2
355        Lucas Paqueta          West Ham United           7.0        5
363         Jacob Ramsey         Newcastle United           5.0        3
381      Cristian Romero        Tottenham Hotspur          11.0        9
449     Lesley Ugochukwu                  Burnley           3.0        1
460         Adam Wharton           Crystal Palace           6.0        4

## Validation Finding: Yellow Cards

During cross-source validation, **15 players** were found to have different `yellow_cards` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `yellow_cards` statistic for every matched player.
3. Identified **15 mismatched records**.
4. Cross-checked the values against the official Premier League statistics.
5. Confirmed that **The Analyst matched the official Premier League values**, while FBref consistently reported different values.

### Sample of Mismatches

| Player        | FBref | The Analyst | Official Premier League | Decision        |
| ------------- | ----: | ----------: | ----------------------: | --------------- |
| Jarrod Bowen  |     4 |           5 |                       5 | Use The Analyst |
| Dan Burn      |    11 |           9 |                       9 | Use The Analyst |
| Casemiro      |    11 |           9 |                       9 | Use The Analyst |
| Wesley Fofana |     9 |           5 |                       5 | Use The Analyst |
| Jack Grealish |     5 |           3 |                       3 | Use The Analyst |

### Conclusion

The validation confirms that **The Analyst** provides the correct `yellow_cards` values. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.

### Reference

Official Premier League Yellow Cards Statistics:

[https://www.premierleague.com/en/stats/top/players/yellow-cards/2025-26](https://www.premierleague.com/en/stats/top/players/yellow-cards/2025-26)

In [78]:
(merged_outfield_players["red_cards"] != merged_outfield_players["reds"]).sum()

np.int64(0)

In [79]:
(merged_outfield_players["fouls_committed"] != merged_outfield_players["fouls_commited"]).sum()

np.int64(58)

In [80]:
merged_outfield_players = merged_outfield_players.rename(columns={
    "fouls_committed": "fouls_commited_fbref",
    "fouls_commited": "fouls_commited_analyst"
})

In [81]:
[c for c in merged_outfield_players.columns if "foul" in c.lower()]

['fouls_commited_fbref', 'fouls_drawn', 'fouls_commited_analyst']

In [82]:
fouls_commited_df = merged_outfield_players.loc[
   merged_outfield_players["fouls_commited_fbref"] != merged_outfield_players["fouls_commited_analyst"],
    ["Player", "Squad", "fouls_commited_fbref", "fouls_commited_analyst"]
]

fouls_commited_df

,Player,Squad,fouls_commited_fbref,fouls_commited_analyst
5,Tyler Adams,AFC Bournemouth,36.0,35
7,Simon Adingra,Sunderland,18.0,17
18,Jaydon Amauri Banel,Burnley,0.0,1
21,Joachim Andersen,Fulham,30.0,31
25,Jaidon Anthony,Burnley,27.0,28
26,Jhon Arias,Wolverhampton Wanderers,26.0,25
27,Adam Armstrong,Wolverhampton Wanderers,12.0,13
29,Tolu Arokodare,Wolverhampton Wanderers,18.0,17
40,Thierno Barry,Everton,46.0,47
46,Beto,Everton,32.0,33
57,Brian Brobbey,Sunderland,33.0,32
62,Hugo Bueno,Wolverhampton Wanderers,17.0,18
63,Santiago Bueno,Wolverhampton Wanderers,29.0,30
76,Matty Cash,Aston Villa,42.0,41
80,Rayan Cherki,Manchester City,18.0,17
83,Ryan Christie,AFC Bournemouth,16.0,17
96,Matheus Cunha,Manchester United,28.0,27
98,Mikkel Damsgaard,Brentford,18.0,19
109,Amad Diallo,Manchester United,24.0,23
110,Habib Diarra,Sunderland,19.0,20
125,Lewis Dunk,Brighton & Hove Albion,14.0,15
139,Bruno Fernandes,Manchester United,24.0,25
142,Zian Flemming,Burnley,51.0,50
153,Conor Gallagher,Tottenham Hotspur,25.0,26
166,Diego Gomez,Brighton & Hove Albion,49.0,48
198,Jack Hinshelwood,Brighton & Hove Albion,32.0,33
202,Will Hughes,Crystal Palace,24.0,23
203,Trai Hume,Sunderland,30.0,31
212,Reece James,Chelsea,26.0,27
221,Joelinton,Newcastle United,46.0,47
230,Boubacar Kamara,Aston Villa,16.0,17
241,Randal Kolo Muani,Tottenham Hotspur,41.0,40
261,Pedro Lima,Wolverhampton Wanderers,6.0,5
277,Kobbie Mainoo,Manchester United,12.0,13
281,Mateus Mane,Wolverhampton Wanderers,26.0,25
299,Hannibal Mejbri,Burnley,23.0,24
309,Tyrick Mitchell,Crystal Palace,24.0,23
314,Mason Mount,Manchester United,17.0,16
320,Daniel Munoz,Crystal Palace,34.0,35
331,Pedro Neto,Chelsea,17.0,16
341,Luke O'Nien,Sunderland,7.0,6
355,Lucas Paqueta,West Ham United,27.0,28
369,Chris Richards,Crystal Palace,17.0,18
384,Noah Sadiki,Sunderland,31.0,32
401,Marcos Senesi,AFC Bournemouth,35.0,34
404,Luke Shaw,Manchester United,48.0,49
405,Bernardo Silva,Manchester City,36.0,37
421,Dominik Szoboszlai,Liverpool,42.0,41
426,Marcus Tavernier,AFC Bournemouth,31.0,30
427,Loum Tchaouna,Burnley,12.0,13
431,Igor Thiago,Brentford,74.0,73
435,Jean-Clair Todibo,West Ham United,9.0,8
459,Danny Welbeck,Brighton & Hove Albion,31.0,30
463,Neco Williams,Nottingham Forest,29.0,30
479,Joshua Zirkzee,Manchester United,8.0,9
483,Antoine Semenyo,Manchester City,54.0,56
491,Jorgen Strand Larsen,Crystal Palace,51.0,52
492,Marc Guiu,Chelsea,9.0,10

## Validation Finding: Fouls Committed

During cross-source validation, **52 players** were found to have different `fouls_committed` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `fouls_committed` statistic for every matched player.
3. Identified **52 mismatched records**.
4. Cross-checked the values against the official Premier League statistics.
5. Confirmed that **The Analyst matched the official Premier League values**, while FBref consistently reported different values.

### Sample of Mismatches

| Player           | FBref | The Analyst | Official Premier League | Decision        |
| ---------------- | ----: | ----------: | ----------------------: | --------------- |
| Tyler Adams      |    36 |          35 |                      35 | Use The Analyst |
| Joachim Andersen |    30 |          31 |                      31 | Use The Analyst |
| Jaidon Anthony   |    27 |          28 |                      28 | Use The Analyst |
| Jhon Arias       |    26 |          25 |                      25 | Use The Analyst |
| Adam Armstrong   |    12 |          13 |                      13 | Use The Analyst |

### Conclusion

The validation confirms that **The Analyst** provides the correct `fouls_committed` values. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.

### Reference

Official Premier League Fouls Conceded Statistics:

[https://www.premierleague.com/en/stats/top/players/total-fouls-conceded/2025-26](https://www.premierleague.com/en/stats/top/players/total-fouls-conceded/2025-26)

## Table 1b — Same concept, different scope

**Do NOT treat as duplicates without checking definitions.**

| fbref | analyst | Why it's risky |
|---|---|---|
| `crosses` | `op_crosses` | `op_` likely = open-play only; fbref's version may include set-piece crosses |
| `tackles_won` | `tackles` | fbref counts successes; analyst's may count attempts |

In [83]:
merged_outfield_players[["Player", "crosses", "op_crosses", "tackles_won", "tackles"]]

                   Player  crosses  op_crosses  tackles_won  tackles
0        Brenden Aaronson     37.0          36         27.0       50
1            Jerome Abbey      0.0           0          0.0        1
2             Zach Abbott      3.0           3          4.0        4
3           Tammy Abraham      1.0           1          1.0        4
4       Joshua Acheampong      1.0           1          8.0       11
..                    ...      ...         ...          ...      ...
491  Jorgen Strand Larsen      3.0           3          2.0        9
492             Marc Guiu      0.0           0          0.0        0
493            Marc Guehi     17.0          17         31.0       46
494            Oscar Bobb     14.0           9         12.0       21
495        Tyrique George     11.0          11          5.0        7

[496 rows x 5 columns]

## Non-comparable metrics

During validation, several similarly named statistics were found to represent different definitions across data sources. These were not treated as inconsistencies and were excluded from cross-source validation.

tackles_won (FBref) vs tackles (The Analyst)
crosses (FBref) vs op_crosses (The Analyst)

## Table 2: Unmatched columns (unique to one source)

| fbref only | analyst only |
|---|---|
| `Nation` | `xg` |
| `Pos` | `goals_vs_xg` |
| `Age` | `shots` |
| `Born` | `shot_conv` |
| `starts` | `xg_per_shot` |
| `90s_played` | `squad_position` |
| `goals_assists` | `squad_position_detailed` |
| `non_penalty_goals` | `np_goals` |
| `penalty_kicks_made` | `np_xg` |
| `penalty_kicks_attempted` | `np_goals_vs_xg` |
| `goals_per90` | `np_shots` |
| `assists_per90` | `np_shots_on_target` |
| `goals_assists_per90` | `np_shot_conv` |
| `non_penalty_goals_per90` | `np_xg_per_shot` |
| `non_penalty_goals_assists_per90` | `carries` |
| `shots_per90` | `carry_distance` |
| `shots_on_target_per90` | `progressive_carries` |
| `shots_total` | `progressive_distance` |
| `goals_per_shot` | `shot_ending` |
| `shots_on_target_pct` | `goal_ending` |
| `goals_per_shot_on_target` | `chance_ending` |
| `second_yellow_card` | `assist_ending` |
| `fouls_drawn` | `dist_per_carry` |
| `own_goals` | `dist_per_progressive_carry` |
| `goals_allowed_on_pitch` | `recoveries` |
| `plus_minus` | `blocks` |
| `sub_appearances` | `clearances` |
| `plus_minus_net_per90` | `ground_duels` |
| `unused_sub` | `ground_duels_won` |
| `complete_matches` | `ground_duel_perc` |
| `minutes_per_sub` | `aerial_duels` |
| `minutes_per_match` | `aerial_duels_won` |
| `points_per_match` | `aerial_duel_perc` |
| `minutes_pct` | `pens_conceded` |
| `minutes_per_start` | `chances_created` |
| `plus_minus_per90` | `op_chances_created` |
| `goals_scored_on_pitch` | `chances_per_100_pass` |
| | `chances_sp_op_ratio` |
| | `xa` |
| | `op_xa` |
| | `op_assists` |
| | `passes` |
| | `successful_passes` |
| | `pass_perc` |
| | `total_final_third_passes` |
| | `successful_final_third_passes` |
| | `ft_pass_perc` |
| | `successful_op_crosses` |
| | `cross_perc` |
| | `through_balls` |
| | `successful_through_balls` |
| | `through_ball_perc` |

List of Columns to remove:
1. analyst - "player"
2. analyst - "apps"
3. analyst - "goals_analyst"
4. fbref - "shots_on_target_fbref"
5. fbref - "offsides_fbref"
6. fbref - "interceptions_fbref"
7. fbref - "minutes"
8. fbref - "yellow_cards"
9. fbref - "fouls_commited_fbref"
10. fbref - "red_cards"
11. analyst - "assists_analyst"
12. analyst - "contestantClubName"

In [84]:
print("minutes" in fbref_player_df.columns, "minutes" in the_analyst_player.columns)
print("mins_played" in fbref_player_df.columns, "mins_played" in the_analyst_player.columns)

True False
False True

In [85]:
(merged_outfield_players["shots_total"] != merged_outfield_players["shots"]).sum()

np.int64(22)

In [86]:
[c for c in merged_outfield_players.columns if "shots" in c]

['shots_total',
 'shots_on_target_fbref',
 'shots_on_target_pct',
 'shots_per90',
 'shots_on_target_per90',
 'shots',
 'shots_on_target_analyst',
 'np_shots',
 'np_shots_on_target']

In [87]:
shots_df = merged_outfield_players.loc[
   merged_outfield_players["shots_total"] != merged_outfield_players["shots"],
    ["Player", "Squad", "shots_total","shots"]
]

In [88]:
shots_df

                    Player                    Squad  shots_total  shots
14              Nathan Ake          Manchester City          7.0      6
29          Tolu Arokodare  Wolverhampton Wanderers         46.0     47
41           Calvin Bassey                   Fulham         12.0     13
44            Sander Berge                   Fulham         14.0     15
71   Dominic Calvert-Lewin             Leeds United         73.0     74
121          Patrick Dorgu        Manchester United         25.0     26
125             Lewis Dunk   Brighton & Hove Albion         23.0     24
138              Evanilson          AFC Bournemouth         72.0     70
142          Zian Flemming                  Burnley         52.0     53
218           Raul Jimenez                   Fulham         73.0     74
222           Curtis Jones                Liverpool         22.0     23
233          Michael Keane                  Everton         27.0     26
251        Maxence Lacroix           Crystal Palace         25.0     24
253           Josh Laurent                  Burnley         15.0     14
273           Noni Madueke                  Arsenal         25.0     26
281            Mateus Mane  Wolverhampton Wanderers         41.0     42
320           Daniel Munoz           Crystal Palace         26.0     27
344         Wilson Odobert        Tottenham Hotspur         21.0     22
384            Noah Sadiki               Sunderland         19.0     18
425        James Tarkowski                  Everton         20.0     21
428     Jackson Tchatchoua  Wolverhampton Wanderers          3.0      2
439        Bertrand Traore               Sunderland         12.0     13

## Validation Finding: Total Shots

During cross-source validation, **20 players** were found to have different `shots_total` values between **FBref** and **The Analyst**.

### Validation Process

1. Merged the FBref and The Analyst datasets using player name.
2. Compared the `shots_total` statistic for every matched player.
3. Identified **20 mismatched records**.
4. Cross-checked the values against SofaScore player statistics.
5. Confirmed that **The Analyst matched the SofaScore values**, while FBref consistently reported different values.

### Sample of Mismatches

| Player                | FBref | The Analyst | SofaScore | Decision        |
| --------------------- | ----: | ----------: | --------: | --------------- |
| Tolu Arokodare        |    46 |          47 |        47 | Use The Analyst |
| Calvin Bassey         |    12 |          13 |        13 | Use The Analyst |
| Sander Berge          |    14 |          15 |        15 | Use The Analyst |
| Dominic Calvert-Lewin |    73 |          74 |        74 | Use The Analyst |
| Patrick Dorgu         |    25 |          26 |        26 | Use The Analyst |

### Conclusion

The validation confirms that **The Analyst** provides the correct `shots_total` values. Therefore, **The Analyst** is selected as the canonical source for this metric in the final merged dataset.

### Reference

SofaScore Premier League Player Statistics (Shots):

[https://www.sofascore.com/football/tournament/england/premier-league/17#id:76986,tab:stats](https://www.sofascore.com/football/tournament/england/premier-league/17#id:76986,tab:stats)

#### Columns to remove

|  # | Dataset     | Column                  |
| -: | ----------- | ----------------------- |
|  1 | The Analyst | `player`                |
|  2 | The Analyst | `apps`                  |
|  3 | The Analyst | `goals_analyst`         |
|  4 | FBref       | `shots_on_target_fbref` |
|  5 | FBref       | `offsides_fbref`        |
|  6 | FBref       | `interceptions_fbref`   |
|  7 | FBref       | `minutes`               |
|  8 | FBref       | `yellow_cards`          |
|  9 | FBref       | `fouls_commited_fbref`  |
| 10 | FBref       | `red_cards`             |
| 11 | The Analyst | `assists_analyst`       |
| 12 | The Analyst | `contestantClubName`    |
| 13 | FBref | `shots_total`    |

In [89]:
duplicated_col = [
    "player",
    "apps",
    "goals_analyst",
    "shots_on_target_fbref",
    "offsides_fbref",
    "interceptions_fbref",
    "minutes",
    "yellow_cards",
    "fouls_commited_fbref",
    "red_cards",
    "assists_fbref",
    "contestantClubName",
    "shots_total"
]

merged_outfield_players = merged_outfield_players.drop(columns=duplicated_col)

In [90]:
merged_outfield_players

,Player,Nation,Pos,Squad,Age,Born,matches_played,starts,90s_played,goals_fbref,...,pass_perc,total_final_third_passes,successful_final_third_passes,ft_pass_perc,op_crosses,successful_op_crosses,cross_perc,through_balls,successful_through_balls,through_ball_perc
0,Brenden Aaronson,us USA,"MF,FW",Leeds United,24,2000,37.0,30.0,27.2,4.0,...,81.14,257,192,74.71,36,10,27.78,6,3,50.0
1,Jerome Abbey,eng ENG,MF,Wolverhampton Wanderers,15,2009,1.0,0.0,0.2,0.0,...,20.00,2,0,0.00,0,0,0.00,0,0,0.0
2,Zach Abbott,eng ENG,DF,Nottingham Forest,19,2006,3.0,2.0,1.8,0.0,...,70.97,18,9,50.00,3,1,33.33,0,0,0.0
3,Tammy Abraham,eng ENG,FW,Aston Villa,27,1997,12.0,2.0,3.2,2.0,...,56.82,20,10,50.00,1,0,0.00,0,0,0.0
4,Joshua Acheampong,eng ENG,DF,Chelsea,19,2006,17.0,8.0,7.4,1.0,...,92.05,52,38,73.08,1,1,100.00,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Jorgen Strand Larsen,no NOR,FW,Crystal Palace,25,2000,36.0,26.0,25.6,4.0,...,64.50,185,109,58.92,3,0,0.00,4,1,25.0
492,Marc Guiu,es ESP,FW,Chelsea,19,2006,10.0,1.0,3.1,0.0,...,68.75,13,10,76.92,0,0,0.00,0,0,0.0
493,Marc Guehi,eng ENG,DF,Manchester City,25,2000,35.0,35.0,35.0,3.0,...,89.65,495,398,80.40,17,3,17.65,3,3,100.0
494,Oscar Bobb,no NOR,"MF, FW",Fulham,22,2003,23.0,11.0,11.5,0.0,...,85.79,195,164,84.10,9,3,33.33,2,2,100.0
495,Tyrique George,eng ENG,"MF, FW",Everton,19,2006,15.0,1.0,4.0,0.0,...,80.18,53,42,79.25,11,5,45.45,0,0,0.0

In [91]:
merged_outfield_players["Nation"] = merged_outfield_players["Nation"].str.split().str[-1]

In [92]:
player_pos = ["Player", "Pos", "squad_position", "squad_position_detailed"]

In [93]:
merged_outfield_players.loc[merged_outfield_players["Pos"].str.contains(","), player_pos]

                  Player     Pos squad_position squad_position_detailed
0       Brenden Aaronson   MF,FW     Midfielder    Attacking Midfielder
7          Simon Adingra   MF,FW        Forward                  Winger
18   Jaydon Amauri Banel   FW,MF        Forward                  Winger
19          Zeki Amdouni   FW,MF        Forward                       0
26            Jhon Arias   FW,MF     Midfielder    Attacking Midfielder
..                   ...     ...            ...                     ...
484      Brennan Johnson  MF, FW        Forward                 Striker
486         Eberechi Eze  MF, FW     Midfielder    Attacking Midfielder
489       Harvey Elliott  MF, FW     Midfielder    Attacking Midfielder
494           Oscar Bobb  MF, FW     Midfielder                  Winger
495       Tyrique George  MF, FW        Forward                  Winger

[119 rows x 4 columns]

In [94]:
merged_outfield_players = merged_outfield_players.drop(columns=["Pos", "squad_position_detailed"])

In [95]:
merged_outfield_players.duplicated().sum() == 0

np.True_

In [96]:
merged_outfield_players["Player"].duplicated().sum() == 0

np.True_

In [97]:
merged_outfield_players.columns.tolist()

['Player',
 'Nation',
 'Squad',
 'Age',
 'Born',
 'matches_played',
 'starts',
 '90s_played',
 'goals_fbref',
 'goals_assists',
 'non_penalty_goals',
 'penalty_kicks_made',
 'penalty_kicks_attempted',
 'goals_per90',
 'assists_per90',
 'goals_assists_per90',
 'non_penalty_goals_per90',
 'non_penalty_goals_assists_per90',
 'shots_on_target_pct',
 'shots_per90',
 'goals_per_shot',
 'goals_per_shot_on_target',
 'shots_on_target_per90',
 'second_yellow_card',
 'crosses',
 'tackles_won',
 'fouls_drawn',
 'own_goals',
 'points_per_match',
 'goals_allowed_on_pitch',
 'plus_minus_per90',
 'goals_scored_on_pitch',
 'minutes_per_start',
 'plus_minus',
 'minutes_per_sub',
 'unused_sub',
 'minutes_pct',
 'complete_matches',
 'plus_minus_net_per90',
 'minutes_per_match',
 'sub_appearances',
 'mins_played',
 'xg',
 'goals_vs_xg',
 'shots',
 'shots_on_target_analyst',
 'shot_conv',
 'xg_per_shot',
 'squad_position',
 'np_goals',
 'np_xg',
 'np_goals_vs_xg',
 'np_shots',
 'np_shots_on_target',
 'np_shot_conv',
 'np_xg_per_shot',
 'carries',
 'carry_distance',
 'progressive_carries',
 'progressive_distance',
 'shot_ending',
 'goal_ending',
 'chance_ending',
 'assist_ending',
 'dist_per_carry',
 'dist_per_progressive_carry',
 'tackles',
 'interceptions_analyst',
 'recoveries',
 'blocks',
 'clearances',
 'ground_duels',
 'ground_duels_won',
 'ground_duel_perc',
 'aerial_duels',
 'aerial_duels_won',
 'aerial_duel_perc',
 'yellows',
 'reds',
 'fouls_commited_analyst',
 'pens_conceded',
 'offsides_analyst',
 'chances_created',
 'op_chances_created',
 'chances_per_100_pass',
 'chances_sp_op_ratio',
 'xa',
 'op_xa',
 'assists_analyst',
 'op_assists',
 'passes',
 'successful_passes',
 'pass_perc',
 'total_final_third_passes',
 'successful_final_third_passes',
 'ft_pass_perc',
 'op_crosses',
 'successful_op_crosses',
 'cross_perc',
 'through_balls',
 'successful_through_balls',
 'through_ball_perc']

In [98]:
merged_outfield_players.isnull().sum().sum()

np.int64(0)

In [99]:
merged_outfield_players.to_parquet(PROCESSED_DATA / "merged_outfield_players_dataset.parquet")

In [100]:
outfield_players = merged_outfield_players[merged_outfield_players["mins_played"] >= 900]
outfield_players.to_csv(PROCESSED_DATA / "outfield_players.csv")
outfield_players.to_parquet(PROCESSED_DATA / "outfield_players.parquet")

OUTFIELD PLAYERS MASTER DATASET SUMMARY

Rows: 316

Columns: 102

Duplicate Players: 0

Missing Player Names: 0

Duplicate Columns Removed: 12

Metrics Validated:
- Goals
- Assists
- Interceptions
- Yellow Cards
- Fouls Committed
- Shots

Club Names Standardized: Yes

Transfer Players Handled: Yes

Ready for Analysis: Yes

In [101]:
merged_gk = fbref_gk_df.merge(
    the_analyst_gk,
    left_on="Player",
    right_on="player",
    how="inner",
    suffixes=("_fbref", "_analyst")
)

In [102]:
same_col_gk = [col for col in merged_gk.columns if col.endswith(("_fbref", "_analyst"))]

In [103]:
same_col_gk

[]

In [104]:
merged_gk.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'matches_played',
       'starts', 'minutes', '90s_played', 'goals_against',
       'goals_against_per90', 'shots_on_target_against', 'saves', 'save_pct',
       'wins', 'draws', 'losses', 'clean_sheets', 'clean_sheet_pct',
       'pk_attempted', 'pk_allowed', 'pk_saved', 'pk_missed', 'pk_save_pct',
       'goals', 'assists', 'goals_assists', 'non_penalty_goals',
       'penalty_kicks_made', 'penalty_kicks_attempted', 'yellow_cards',
       'red_cards', 'goals_per90', 'assists_per90', 'goals_assists_per90',
       'non_penalty_goals_per90', 'non_penalty_goals_assists_per90',
       'shots_total', 'shots_on_target', 'shots_on_target_pct', 'shots_per90',
       'goals_per_shot', 'goals_per_shot_on_target', 'shots_on_target_per90',
       'second_yellow_card', 'fouls_committed', 'offsides', 'crosses',
       'tackles_won', 'fouls_drawn', 'interceptions', 'own_goals',
       'points_per_match', 'goals_allowed_on_pitch', 'plus_minus_per90',
       'goals_scored_on_pitch', 'minutes_per_start', 'plus_minus',
       'minutes_per_sub', 'unused_sub', 'minutes_pct', 'complete_matches',
       'plus_minus_net_per90', 'minutes_per_match', 'sub_appearances', 'apps',
       'mins_played', 'team_mins', 'team_mins_perc', 'ogs', 'goals_conceded',
       'saves_made', 'save_perc', 'goals_prevented', 'goals_prevented_rate',
       'xgot_conceded', 'player', 'squad_position', 'contestantClubName'],
      dtype='str')

In [105]:
merged_gk.shape

(39, 80)

In [106]:
merged_gk = merged_gk.drop(columns=["player", "contestantClubName"])

In [107]:
merged_gk["minutes"].equals(merged_gk["mins_played"])

False

In [108]:
gk_mins_df = merged_gk[["Player", "minutes", "mins_played"]]

In [109]:
gk_mins_df["diff"] = gk_mins_df["minutes"] - gk_mins_df["mins_played"]
gk_mins_df.loc[gk_mins_df["diff"] > 0]

             Player  minutes  mins_played  diff
15  Filip Jorgensen    379.0          378   1.0
27   Aaron Ramsdale   1004.0         1003   1.0
32        Matz Sels   2668.0         2667   1.0
38  Freddie Woodman    213.0          212   1.0

### Validation Finding: Minutes Played

During cross-source validation, a discrepancy was identified in the **minutes played** statistic for four goalkeepers.

| Player | Metric | FBref | The Analyst | Official Premier League | Decision |
|--------|--------|------:|------------:|------------------------:|----------|
| Filip Jorgensen | Minutes Played | 379 | 378 | 378 | Use The Analyst |
| Aaron Ramsdale | Minutes Played | 1004 | 1003 | 1003 | Use The Analyst |
| Matz Sels | Minutes Played | 2668 | 2667 | 2667 | Use The Analyst |
| Freddie Woodman | Minutes Played | 213 | 212 | 212 | Use The Analyst |

### Validation Process

1. Compared the `minutes` (FBref) and `mins_played` (The Analyst) columns.
2. Identified four records with a **1-minute difference**.
3. Verified the statistics against the official Premier League website.
4. Confirmed that **The Analyst** values match the official source.

### Conclusion

For these four goalkeepers, the **Analyst** values were adopted as the canonical values because they matched the official Premier League statistics.

The observed differences are limited to **1 minute** and are likely attributable to differences in data provider calculation or rounding methodology.

### Reference

- Official Premier League Minutes Played (Goalkeepers): https://www.premierleague.com/en/stats/top/players/time-played/2025-26?position=Goalkeeper

In [110]:
merged_gk["goals_allowed_on_pitch"].astype("int").equals(merged_gk["goals_conceded"])

False

In [111]:
goals_conceded_df = merged_gk[["Player", "goals_allowed_on_pitch", "goals_conceded"]]
goals_conceded_df["diff"] = merged_gk["goals_allowed_on_pitch"] - merged_gk["goals_conceded"]
goals_conceded_df.loc[goals_conceded_df["diff"] != 0]

           Player  goals_allowed_on_pitch  goals_conceded  diff
22  Stefan Ortega                     0.0               4  -4.0

In [112]:
merged_gk.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'matches_played',
       'starts', 'minutes', '90s_played', 'goals_against',
       'goals_against_per90', 'shots_on_target_against', 'saves', 'save_pct',
       'wins', 'draws', 'losses', 'clean_sheets', 'clean_sheet_pct',
       'pk_attempted', 'pk_allowed', 'pk_saved', 'pk_missed', 'pk_save_pct',
       'goals', 'assists', 'goals_assists', 'non_penalty_goals',
       'penalty_kicks_made', 'penalty_kicks_attempted', 'yellow_cards',
       'red_cards', 'goals_per90', 'assists_per90', 'goals_assists_per90',
       'non_penalty_goals_per90', 'non_penalty_goals_assists_per90',
       'shots_total', 'shots_on_target', 'shots_on_target_pct', 'shots_per90',
       'goals_per_shot', 'goals_per_shot_on_target', 'shots_on_target_per90',
       'second_yellow_card', 'fouls_committed', 'offsides', 'crosses',
       'tackles_won', 'fouls_drawn', 'interceptions', 'own_goals',
       'points_per_match', 'goals_allowed_on_pitch', 'plus_minus_per90',
       'goals_scored_on_pitch', 'minutes_per_start', 'plus_minus',
       'minutes_per_sub', 'unused_sub', 'minutes_pct', 'complete_matches',
       'plus_minus_net_per90', 'minutes_per_match', 'sub_appearances', 'apps',
       'mins_played', 'team_mins', 'team_mins_perc', 'ogs', 'goals_conceded',
       'saves_made', 'save_perc', 'goals_prevented', 'goals_prevented_rate',
       'xgot_conceded', 'squad_position'],
      dtype='str')

In [113]:
merged_gk.describe()

,matches_played,starts,minutes,90s_played,goals_against,goals_against_per90,shots_on_target_against,saves,save_pct,wins,...,mins_played,team_mins,team_mins_perc,ogs,goals_conceded,saves_made,save_perc,goals_prevented,goals_prevented_rate,xgot_conceded
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,...,39.000000,39.0,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000
mean,19.641026,19.487179,1752.641026,19.474359,26.846154,1.431795,78.410256,53.589744,66.892308,7.076923,...,1752.666667,3420.0,51.256410,1.025641,26.794872,54.230769,65.455897,0.228205,0.911282,25.997436
std,14.209869,14.317585,1279.086464,14.209499,19.437536,0.488935,58.203689,40.588252,10.731468,6.717552,...,1279.164372,0.0,37.314254,1.287331,19.380103,41.114386,10.940863,2.696402,0.280406,19.204065
min,1.000000,1.000000,90.000000,1.000000,0.000000,0.000000,3.000000,1.000000,25.000000,0.000000,...,90.000000,3420.0,3.000000,0.000000,0.000000,1.000000,25.000000,-5.540000,0.000000,0.330000
25%,5.000000,4.500000,408.000000,4.550000,7.000000,1.225000,14.500000,10.000000,64.350000,1.000000,...,408.000000,3420.0,12.000000,0.000000,7.000000,10.000000,63.070000,-1.785000,0.875000,6.805000
50%,20.000000,20.000000,1800.000000,20.000000,28.000000,1.380000,86.000000,57.000000,67.600000,4.000000,...,1800.000000,3420.0,53.000000,1.000000,28.000000,57.000000,66.670000,-0.010000,0.970000,25.420000
75%,34.500000,34.500000,3049.500000,33.900000,42.500000,1.630000,132.000000,94.000000,70.800000,13.000000,...,3050.500000,3420.0,89.000000,2.000000,42.500000,95.000000,69.885000,1.715000,1.050000,43.740000
max,38.000000,38.000000,3420.000000,38.000000,71.000000,3.000000,192.000000,127.000000,100.000000,25.000000,...,3420.000000,3420.0,100.000000,4.000000,71.000000,127.000000,100.000000,6.490000,1.330000,67.710000

In [114]:
merged_gk.select_dtypes("number").sum().sort_values()

plus_minus_per90               -1.55
plus_minus_net_per90           -0.24
penalty_kicks_attempted         0.00
non_penalty_goals               0.00
penalty_kicks_made              0.00
                             ...
minutes_per_match            3360.00
minutes_per_start            3408.00
minutes                     68353.00
mins_played                 68354.00
team_mins                  133380.00
Length: 71, dtype: float64

In [115]:
merged_gk.loc[merged_gk["shots_per90"] > 0, ["Player", "shots_per90"]]

       Player  shots_per90
26  Nick Pope         0.04

In [116]:
merged_gk.loc[
    merged_gk["shots_on_target_per90"] > 0,
    ["Player", "shots_on_target_per90"]
]

       Player  shots_on_target_per90
26  Nick Pope                   0.04

In [117]:
merged_gk["own_goals"].equals(merged_gk["ogs"])

False

In [118]:
own_goals_df = merged_gk[["Player", "own_goals", "ogs"]]

own_goals_df["diff"] = merged_gk["own_goals"] - merged_gk["ogs"]

In [119]:
own_goals_df.loc[own_goals_df["diff"] != 0]

                Player  own_goals  ogs  diff
1      Alphonse Areola        0.0    1  -1.0
6          Marco Bizot        0.0    1  -1.0
7          Karl Darlow        0.0    1  -1.0
9      Martin Dubravka        0.0    4  -4.0
11      Dean Henderson        0.0    2  -2.0
12      Mads Hermansen        0.0    2  -2.0
14       Sam Johnstone        1.0    4  -3.0
16   Caoimhin Kelleher        0.0    2  -2.0
18       Senne Lammens        0.0    2  -2.0
19          Bernd Leno        1.0    3  -2.0
24      Dorde Petrovic        1.0    3  -2.0
25     Jordan Pickford        0.0    1  -1.0
26           Nick Pope        0.0    1  -1.0
27      Aaron Ramsdale        0.0    1  -1.0
28          David Raya        0.0    1  -1.0
29         Robin Roefs        0.0    2  -2.0
31      Robert Sanchez        0.0    1  -1.0
32           Matz Sels        0.0    3  -3.0
34  Hakon Valdimarsson        0.0    1  -1.0
35     Bart Verbruggen        1.0    4  -3.0

In [120]:
merged_gk[["Player", "goals_conceded", "ogs"]].sort_values("ogs", ascending=False)

                  Player  goals_conceded  ogs
35       Bart Verbruggen              46    4
14         Sam Johnstone              24    4
9        Martin Dubravka              71    4
19            Bernd Leno              51    3
24        Dorde Petrovic              54    3
32             Matz Sels              39    3
16     Caoimhin Kelleher              49    2
29           Robin Roefs              46    2
18         Senne Lammens              39    2
12        Mads Hermansen              28    2
11        Dean Henderson              51    2
25       Jordan Pickford              50    1
6            Marco Bizot              10    1
1        Alphonse Areola              37    1
28            David Raya              26    1
34    Hakon Valdimarsson               3    1
31        Robert Sanchez              47    1
27        Aaron Ramsdale              17    1
7            Karl Darlow              27    1
26             Nick Pope              38    1
0         Alisson Becker              31    0
3         Altay Bayindir              11    0
2      Kepa Arrizabalaga               1    0
5         Daniel Bentley               7    0
4         Walter Benitez               0    0
20  Giorgi Mamardashvili              18    0
17        Antonin Kinsky               7    0
15       Filip Jorgensen               5    0
8   Gianluigi Donnarumma              29    0
10        Melker Ellborg               2    0
13           John Victor               8    0
22         Stefan Ortega               4    0
21     Emiliano Martinez              39    0
30               Jose Sa              37    0
23           Lucas Perri              29    0
33        James Trafford               6    0
36     Guglielmo Vicario              50    0
37             Max Weiss               4    0
38       Freddie Woodman               4    0

### Validation Finding: `ogs`

The `ogs` variable from The Analyst dataset could not be conclusively identified through the available documentation or data dictionary.

Although exploratory validation indicated that it does not represent the goalkeeper's own goals, its exact definition could not be verified with sufficient confidence.

**Decision**

To ensure the integrity and interpretability of the canonical dataset, the `ogs` column was excluded from the final goalkeeper dataset. Only features with clearly defined and verifiable meanings were retained for subsequent analysis and feature engineering.

In [121]:
columns_to_drop = [
    "minutes",
    "goals_allowed_on_pitch",
    "shots_total",
    "shots_per90",
    "shots_on_target",
    "shots_on_target_per90",
    "shots_on_target_pct",
    "goals_per_shot",
    "goals_per_shot_on_target",
    "non_penalty_goals",
    "goals_per90",
    "non_penalty_goals_per90",
    "goals_assists_per90",
    "non_penalty_goals_assists_per90",
    "Born",
    "Pos",
    "ogs",
    "penalty_kicks_made", 
    "penalty_kicks_attempted", 
    "offsides"
]

merged_gk = merged_gk.drop(columns=columns_to_drop)

### Goalkeeper Dataset Column Selection

The merged goalkeeper dataset contained several redundant, derived, ambiguous, and goalkeeper-irrelevant variables. These columns were removed to simplify the dataset and retain only features that may contribute meaningfully to goalkeeper performance evaluation.

#### Redundant Columns

These variables duplicated information available elsewhere in the dataset.

- `minutes` (replaced by `mins_played`)
- `goals_allowed_on_pitch` (replaced by `goals_conceded`)
- `Born` (replaced by `Age`)
- `Pos` (replaced by `squad_position`)
- `player` (duplicate player identifier)
- `contestantClubName` (duplicate club identifier)

#### Goalkeeper-Irrelevant Columns

The following variables describe attacking or outfield-specific actions that are not meaningful for evaluating goalkeepers.

- `shots_total`
- `shots_per90`
- `shots_on_target`
- `shots_on_target_per90`
- `shots_on_target_pct`
- `goals_per_shot`
- `goals_per_shot_on_target`
- `penalty_kicks_made`
- `penalty_kicks_attempted`
- `offsides`

#### Derived Attacking Metrics

These metrics were removed because they are derived from attacking statistics that are not central to goalkeeper evaluation.

- `non_penalty_goals`
- `goals_per90`
- `non_penalty_goals_per90`
- `goals_assists_per90`
- `non_penalty_goals_assists_per90`

#### Ambiguous Variable

The `ogs` variable from The Analyst dataset could not be conclusively identified using the available documentation or data dictionary. Although exploratory validation confirmed that it does not represent a goalkeeper's own goals, its exact definition could not be verified with sufficient confidence.

To preserve the integrity and interpretability of the canonical dataset, this variable was excluded from further analysis.

- `ogs`

#### Notes

- `goals`, `assists`, and `goals_assists` were retained because goalkeepers can occasionally make meaningful attacking contributions (e.g., providing an assist or scoring a goal).
- Columns were removed only when they were **redundant, derived, irrelevant to goalkeeper evaluation, or could not be confidently interpreted**.
- The final goalkeeper dataset retains only well-defined features that are relevant for subsequent feature engineering and POTSI score construction.

In [122]:
merged_gk.shape

(39, 58)

In [123]:
merged_gk.to_parquet(PROCESSED_DATA / "merged_gk_dataset.parquet")
gk = merged_gk[merged_gk["mins_played"] >= 900]
gk.to_csv(PROCESSED_DATA / "goalkeepers.csv")
gk.to_parquet(PROCESSED_DATA / "goalkeepers.parquet")

In [124]:
gk.shape

(24, 58)

GOALKEEPER MASTER DATASET SUMMARY

Rows: 24

Columns: 58

Duplicate Players: 0

Missing Player Names: 0

Duplicate Columns Removed: 6

Metrics Validated:
- Minutes Played
- Own Goals
- Goals Conceded

Club Names Standardized: Yes

Player Names Standardized: Yes

Transfer Players Handled: Yes

Ambiguous Variables Removed:
- ogs

Ready for Analysis: Yes